.AUTODEPEND

#               *Translator Definitions*
CC = bcc +SCAN.CFG
TASM = TASM
TLIB = tlib
TLINK = tlink
LIBPATH = D:\BC\LIB
INCLUDEPATH = D:\BC\INCLUDE


#               *Implicit Rules*
.c.obj:
  $(CC) -c {$< }

.cpp.obj:
  $(CC) -c {$< }

#               *List Macros*


EXE_dependencies =  \
 vscanner.obj \
 memory.obj \
 xscanner.obj \
 ratcatch.obj \
 scanner.obj \
 sysdos.obj \
 cmdline.obj

#               *Explicit Rules*
build: ratcatch.exe clean

ratcatch.exe: scan.exe
  tdstrip scan.exe
  ww scan.exe
  ren scan.exe ratcatch.exe

clean:
  del *.obj
  del scan.cfg
  del scan.old
  del scan.exe
  del *.sym

scan.exe: scan.cfg $(EXE_dependencies)
  $(TLINK) /v/x/c/P-/L$(LIBPATH) @&&|
c0l.obj+
vscanner.obj+
memory.obj+
xscanner.obj+
ratcatch.obj+
scanner.obj+
sysdos.obj+
cmdline.obj
scan
                # no map file
fp87.lib+
mathl.lib+
cl.lib
|


#               *Individual File Dependencies*
vscanner.obj: scan.cfg vscanner.cpp

memory.obj: scan.cfg memory.cpp

xscanner.obj: scan.cfg xscanner.cpp

ratcatch.obj: scan.cfg ratcatch.cpp

scanner.obj: scan.cfg scanner.cpp

sysdos.obj: scan.cfg sysdos.cpp

cmdline.obj: scan.cfg cmdline.cpp

#               *Compiler Configuration File*
scan.cfg: makefile.
  copy &&|
-ml
-3
-f287
-v
-G
-d
-vi-
-H=SCAN.SYM
-I$(INCLUDEPATH)
-L$(LIBPATH)
| scan.cfg


