/*
	Author: Know v3.0
	Twitter: @KnowV3
	Email: know [dot] omail [dot] pro
	Website: knowlegend.ws / knowlegend.me

	(c) 2013 - Know v3.0 alias Knowlgend
*/
#pragma once
#include <Windows.h>
#include <tchar.h>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <cstring>
using namespace std;

enum INSTRUCTIONS_E { // enum with all available instructions as static number
		PUSH_EAX,
		PUSH_EBX,
		PUSH_ECX,
		PUSH_EDX,
		PUSH_EEX,
		PUSH_EFX,
		PUSH_EGX,

		POP_EAX,
		POP_EBX,
		POP_ECX,
		POP_EDX,
		POP_EEX,
		POP_EFX,
		POP_EGX,

		CALL_EAX,
		CALL_EBX,
		CALL_ECX,
		CALL_EDX,
		CALL_EEX,
		CALL_EFX,
		CALL_EGX,

		MOV_EAX_EAX,
		MOV_EAX_EBX,
		MOV_EAX_ECX,
		MOV_EAX_EDX,
		MOV_EAX_EEX,
		MOV_EAX_EFX,
		MOV_EAX_EGX,

		MOV_EAX__EAX_, // __ == [ or ] that means that this instruction looks like: mov eax, [eax]
		MOV_EAX__EBX_,
		MOV_EAX__ECX_,
		MOV_EAX__EDX_,
		MOV_EAX__EEX_,
		MOV_EAX__EFX_,
		MOV_EAX__EGX_,

		MOV_EAX__EAX_4_, // mov eax, [eax+4]
		MOV_EAX__EBX_4_,
		MOV_EAX__ECX_4_,
		MOV_EAX__EDX_4_,
		MOV_EAX__EEX_4_,
		MOV_EAX__EFX_4_,
		MOV_EAX__EGX_4_,

		MOV_EBX_EBX,
		MOV_EBX_EAX,
		MOV_EBX_ECX,
		MOV_EBX_EDX,
		MOV_EBX_EEX,
		MOV_EBX_EFX,
		MOV_EBX_EGX,

		MOV_EBX__EBX_,
		MOV_EBX__EAX_,
		MOV_EBX__ECX_,
		MOV_EBX__EDX_,
		MOV_EBX__EEX_,
		MOV_EBX__EFX_,
		MOV_EBX__EGX_,

		MOV_EBX__EBX_4_,
		MOV_EBX__EAX_4_,
		MOV_EBX__ECX_4_,
		MOV_EBX__EDX_4_,
		MOV_EBX__EEX_4_,
		MOV_EBX__EFX_4_,
		MOV_EBX__EGX_4_,

		MOV_ECX_ECX,
		MOV_ECX_EAX,
		MOV_ECX_EBX,
		MOV_ECX_EDX,
		MOV_ECX_EEX,
		MOV_ECX_EFX,
		MOV_ECX_EGX,

		MOV_ECX__ECX_,
		MOV_ECX__EAX_,
		MOV_ECX__EBX_,
		MOV_ECX__EDX_,
		MOV_ECX__EEX_,
		MOV_ECX__EFX_,
		MOV_ECX__EGX_,

		MOV_ECX__ECX_4_,
		MOV_ECX__EAX_4_,
		MOV_ECX__EBX_4_,
		MOV_ECX__EDX_4_,
		MOV_ECX__EEX_4_,
		MOV_ECX__EFX_4_,
		MOV_ECX__EGX_4_,

		MOV_EDX_EDX,
		MOV_EDX_EAX,
		MOV_EDX_EBX,
		MOV_EDX_ECX,
		MOV_EDX_EEX,
		MOV_EDX_EFX,
		MOV_EDX_EGX,
		
		MOV_EDX__EDX_,
		MOV_EDX__EAX_,
		MOV_EDX__EBX_,
		MOV_EDX__ECX_,
		MOV_EDX__EEX_,
		MOV_EDX__EFX_,
		MOV_EDX__EGX_,

		MOV_EDX__EDX_4_,
		MOV_EDX__EAX_4_,
		MOV_EDX__EBX_4_,
		MOV_EDX__ECX_4_,
		MOV_EDX__EEX_4_,
		MOV_EDX__EFX_4_,
		MOV_EDX__EGX_4_,

		MOV_EEX_EEX,
		MOV_EEX_EAX,
		MOV_EEX_EBX,
		MOV_EEX_ECX,
		MOV_EEX_EDX,
		MOV_EEX_EFX,
		MOV_EEX_EGX,
		
		MOV_EEX__EEX_,
		MOV_EEX__EAX_,
		MOV_EEX__EBX_,
		MOV_EEX__ECX_,
		MOV_EEX__EDX_,
		MOV_EEX__EFX_,
		MOV_EEX__EGX_,

		MOV_EEX__EEX_4_,
		MOV_EEX__EAX_4_,
		MOV_EEX__EBX_4_,
		MOV_EEX__ECX_4_,
		MOV_EEX__EDX_4_,
		MOV_EEX__EFX_4_,
		MOV_EEX__EGX_4_,

		MOV_EFX_EFX,
		MOV_EFX_EAX,
		MOV_EFX_EBX,
		MOV_EFX_ECX,
		MOV_EFX_EDX,
		MOV_EFX_EEX,
		MOV_EFX_EGX,

		MOV_EFX__EFX_,
		MOV_EFX__EAX_,
		MOV_EFX__EBX_,
		MOV_EFX__ECX_,
		MOV_EFX__EDX_,
		MOV_EFX__EEX_,
		MOV_EFX__EGX_,

		MOV_EFX__EFX_4_,
		MOV_EFX__EAX_4_,
		MOV_EFX__EBX_4_,
		MOV_EFX__ECX_4_,
		MOV_EFX__EDX_4_,
		MOV_EFX__EEX_4_,
		MOV_EFX__EGX_4_,

		MOV_EGX_EGX,
		MOV_EGX_EAX,
		MOV_EGX_EBX,
		MOV_EGX_ECX,
		MOV_EGX_EDX,
		MOV_EGX_EEX,
		MOV_EGX_EFX,

		MOV_EGX__EGX_,
		MOV_EGX__EAX_,
		MOV_EGX__EBX_,
		MOV_EGX__ECX_,
		MOV_EGX__EDX_,
		MOV_EGX__EEX_,
		MOV_EGX__EFX_,

		MOV_EGX__EGX_4_,
		MOV_EGX__EAX_4_,
		MOV_EGX__EBX_4_,
		MOV_EGX__ECX_4_,
		MOV_EGX__EDX_4_,
		MOV_EGX__EEX_4_,
		MOV_EGX__EFX_4_,

		MOV_EAX_0,
		MOV_EBX_0,
		MOV_ECX_0,
		MOV_EDX_0,
		MOV_EEX_0,
		MOV_EFX_0,
		MOV_EGX_0,

		XOR_EAX_EAX,
		XOR_EAX_EBX,
		XOR_EAX_ECX,
		XOR_EAX_EDX,
		XOR_EAX_EEX,
		XOR_EAX_EFX,
		XOR_EAX_EGX,

		XOR_EBX_EBX,
		XOR_EBX_EAX,
		XOR_EBX_ECX,
		XOR_EBX_EDX,
		XOR_EBX_EEX,
		XOR_EBX_EFX,
		XOR_EBX_EGX,

		XOR_ECX_ECX,
		XOR_ECX_EAX,
		XOR_ECX_EBX,
		XOR_ECX_EDX,
		XOR_ECX_EEX,
		XOR_ECX_EFX,
		XOR_ECX_EGX,

		XOR_EDX_EDX,
		XOR_EDX_EAX,
		XOR_EDX_EBX,
		XOR_EDX_ECX,
		XOR_EDX_EEX,
		XOR_EDX_EFX,
		XOR_EDX_EGX,

		XOR_EEX_EEX,
		XOR_EEX_EAX,
		XOR_EEX_EBX,
		XOR_EEX_ECX,
		XOR_EEX_EDX,
		XOR_EEX_EFX,
		XOR_EEX_EGX,

		XOR_EFX_EFX,
		XOR_EFX_EAX,
		XOR_EFX_EBX,
		XOR_EFX_ECX,
		XOR_EFX_EDX,
		XOR_EFX_EEX,
		XOR_EFX_EGX,

		XOR_EGX_EGX,
		XOR_EGX_EAX,
		XOR_EGX_EBX,
		XOR_EGX_ECX,
		XOR_EGX_EDX,
		XOR_EGX_EEX,
		XOR_EGX_EFX,

		ADD_EAX_EAX,
		ADD_EAX_EBX,
		ADD_EAX_ECX,
		ADD_EAX_EDX,
		ADD_EAX_EEX,
		ADD_EAX_EFX,
		ADD_EAX_EGX,

		ADD_EBX_EBX,
		ADD_EBX_EAX,
		ADD_EBX_ECX,
		ADD_EBX_EDX,
		ADD_EBX_EEX,
		ADD_EBX_EFX,
		ADD_EBX_EGX,

		ADD_ECX_ECX,
		ADD_ECX_EAX,
		ADD_ECX_EBX,
		ADD_ECX_EDX,
		ADD_ECX_EEX,
		ADD_ECX_EFX,
		ADD_ECX_EGX,

		ADD_EDX_EDX,
		ADD_EDX_EAX,
		ADD_EDX_EBX,
		ADD_EDX_ECX,
		ADD_EDX_EEX,
		ADD_EDX_EFX,
		ADD_EDX_EGX,

		ADD_EEX_EEX,
		ADD_EEX_EAX,
		ADD_EEX_EBX,
		ADD_EEX_ECX,
		ADD_EEX_EDX,
		ADD_EEX_EFX,
		ADD_EEX_EGX,

		ADD_EFX_EFX,
		ADD_EFX_EAX,
		ADD_EFX_EBX,
		ADD_EFX_ECX,
		ADD_EFX_EDX,
		ADD_EFX_EEX,
		ADD_EFX_EGX,

		ADD_EGX_EGX,
		ADD_EGX_EAX,
		ADD_EGX_EBX,
		ADD_EGX_ECX,
		ADD_EGX_EDX,
		ADD_EGX_EEX,
		ADD_EGX_EFX,
	

		ADD_EAX_4,
		ADD_EBX_4,
		ADD_ECX_4,
		ADD_EDX_4,
		ADD_EEX_4,
		ADD_EFX_4,
		ADD_EGX_4,

		SUB_EAX_EBX,
		SUB_EAX_ECX,
		SUB_EAX_EDX,
		SUB_EAX_EEX,
		SUB_EAX_EFX,
		SUB_EAX_EGX,

		SUB_EBX_EAX,
		SUB_EBX_ECX,
		SUB_EBX_EDX,
		SUB_EBX_EEX,
		SUB_EBX_EFX,
		SUB_EBX_EGX,

		SUB_ECX_EAX,
		SUB_ECX_EBX,
		SUB_ECX_EDX,
		SUB_ECX_EEX,
		SUB_ECX_EFX,
		SUB_ECX_EGX,

		SUB_EDX_EAX,
		SUB_EDX_EBX,
		SUB_EDX_ECX,
		SUB_EDX_EEX,
		SUB_EDX_EFX,
		SUB_EDX_EGX,

		SUB_EEX_EAX,
		SUB_EEX_EBX,
		SUB_EEX_ECX,
		SUB_EEX_EDX,
		SUB_EEX_EFX,
		SUB_EEX_EGX,

		SUB_EFX_EAX,
		SUB_EFX_EBX,
		SUB_EFX_ECX,
		SUB_EFX_EDX,
		SUB_EFX_EEX,
		SUB_EFX_EGX,

		SUB_EGX_EAX,
		SUB_EGX_EBX,
		SUB_EGX_ECX,
		SUB_EGX_EDX,
		SUB_EGX_EEX,
		SUB_EGX_EFX,

		SUB_EAX_4,
		SUB_EBX_4,
		SUB_ECX_4,
		SUB_EDX_4,
		SUB_EEX_4,
		SUB_EFX_4,
		SUB_EGX_4

};
