
// RFC 1459

#define RPL_ENDOFMOTD           376
#define RPL_NAMREPLY            353
#define RPL_WHOISUSER           311
#define RPL_ENDOFWHOIS          318
#define RPL_WHOREPLY            352
#define RPL_ENDOFWHO            315

#define ERR_NICKNAMEINUSE       433
#define ERR_NICKCOLLISION       436
#define ERR_YOUREBANNEDCREEP    465
#define ERR_NOSUCHNICK          401
#define ERR_ERRONEUSNICKNAME    432
