
# V make file
#
v.exe :	c0v.obj v.lib
 tlink c0v.obj , v , v.map , v.lib /s /v /c /e
#
.C.OBJ :
 bcc -mt -f- -N- -g5 -j5  -c -3 -v -y $<
#
c0v.obj : c0v.asm
 tasm /mx c0v.asm
#
VMAIN.OBJ :  v.h v_std.h vmain.c
vv.obj : v.h v_std.h vv.c
vlib.obj : v.h v_std.h vlib.c
vdoslib.obj : v.h v_std.h vdoslib.c
v_dir.obj : v.h v_std.h v_dir.c
v_sctree.obj : v.h v_std.h  v_sctree.c
v_io.obj : v.h v_std.h v_io.c
getvect.obj : v.h v_std.h
scan_mcb.obj: v.h v_std.h
#
getch.obj : getch.asm
 tasm /mx getch.asm
#
v.lib : v.rsp vmain.obj vv.obj vlib.obj vdoslib.obj vdoslib2.obj v_dir.obj\
	v_sctree.obj v_io.obj getvect.obj scan_mcb.obj getch.obj v_chdir.obj\
	v_ftime.obj
 del v.lib
 tlib v.lib /C @v.rsp , nul
#
