.autodepend

NAME = heretic
OBJS = $(NAME).obj

IMPORT=c:\bin\tasm\import32

$(NAME).EXE: $(OBJS)
        tlink32 /Tpe /aa /c $(OBJS),$(NAME),,$(IMPORT),
        pewrsec $(NAME).exe
.asm.obj:
        tasm32 $(TASMDEBUG) /ml /m $&.asm
