
; the only imported win32 api function names are defined here

import                  GetProcAddress
import                  SetFileTime
import                  FindClose
import                  FindFirstFileA
import                  CloseHandle
import                  GetFileSize
import                  SetFileAttributesA
import                  WriteFile
import                  ReadFile
import                  SetFilePointer
import                  CreateFileA
import                  GetLastError
import                  SetLastError
import                  GetTickCount
import                  GlobalAlloc
import                  CreateThread
import                  FindNextFileA
import                  GetEnvironmentVariableA
import                  GetWindowsDirectoryA   
import                  GetDriveTypeA          
