#   Make file for Turbo Assembler WAP32 example.
#   Copyright (c) 1996 by Borland International, Inc.

#       make -B                 Will build wap32.exe
#       make -B -DDEBUG         Will build the debug version of wap32.exe

NAME = POWERFUL
OBJS = $(NAME).obj

!if $d(DEBUG)
TASMDEBUG=/zi
LINKDEBUG=/v
!else
TASMDEBUG=
LINKDEBUG=
!endif

!if $d(MAKEDIR)
IMPORT=$(MAKEDIR)\..\lib\import32
!else
IMPORT=import32
!endif


$(NAME).EXE: $(OBJS) $(DEF)
  tlink32 /Tpe /aa /c /x $(LINKDEBUG) $(OBJS),$(NAME),, $(IMPORT)
  @del *.obj

.asm.obj:
   tasm32 /m9 $(TASMDEBUG) /ml $&.asm
