Path: ames!lll-winken!csustan!jeffy (Jeffrey Youngstrom)
Newsgroups: comp.binaries.ibm.pc.d
Subject: Life patterns for AAALIFE
Date: 18 Jul 89 03:18:45 GMT
Keywords: life aaalife

I've been playing with Anibal Acero's (acero@tank.uchicago.edu)
AAALIFE for a couple of days, and I took the time to pound a bunch of 
the niftyer patterns from William Poundstone's book _The_Recursive_
Universe_ (William Morrow and Company, NY : 1985, 252pp.) (A very 
interesting book if LIFE caught your interest.  Life isn't by any 
means all of what the book is about, but there is a lot of stuff 
about Life in there.)  Anyway, I don't figure most of you have a lot 
of time on your hands to type in long series of meaningless numbers 
so I thought I'd share these.

jeffy
