//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Poetry.rc
//
#define IDR_MAINFRAME                   2
#define ID_CHECKTIMER                   105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
