 foldersTree = gFld("<i>Issue1</i>                                       " , "javascript:;"                       )
        aux1 = insFld(foldersTree, gFld("I N F O                         " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"Bevezetô                             " , "bevezeto.htm"                       ))
               insDoc(aux1, gLnk(0,"Kontakt                              " , "./fcf/kontakt.htm"                  ))
               insDoc(aux1, gLnk(0,"Az FCF-rôl                           " , "./fcf/fcf.htm"                      ))
               insDoc(aux1, gLnk(0,"Greetz                               " , "./fcf/greetz.htm"                   ))
               insDoc(aux1, gLnk(0,"<B>Members wanted</B>                " , "./fcf/wanted.htm"                   ))
        aux1 = insFld(foldersTree, gFld("A S S E M B L E R               " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"ASM bevezetô                         " , "./asm/bevezeto.htm"                 ))
               insDoc(aux1, gLnk(0,"Assembler Rulez 1. rész              " , "./asm/asm-tut1.htm"                 ))
               insDoc(aux1, gLnk(0,"Assembler Rulez 2. rész              " , "./asm/asm-tut2.htm"                 ))
               insDoc(aux1, gLnk(0,"Assembler Rulez 3. rész              " , "./asm/asm-tut3.htm"                 ))
               insDoc(aux1, gLnk(0,"Assembler Rulez 4. rész              " , "./asm/asm-tut4.htm"                 ))
               insDoc(aux1, gLnk(0,"Assembler Rulez 5. rész              " , "./asm/asm-tut5.htm"                 ))
               insDoc(aux1, gLnk(0,"Verseny - Nem kezdôknek...           " , "./asm/contest.htm"                  ))
        aux1 = insFld(foldersTree, gFld("V I R I I                       " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"ASM Vírusíró tanfolyam I.            " , "./virus/virus1.htm"                 ))
               insDoc(aux1, gLnk(0,"BATch virii készítése - 1. rész      " , "./virus/batvwtut.htm"               ))
               insDoc(aux1, gLnk(0,"Vírusinfo - 1.rész                   " , "./virus/vcollect.htm"               ))
               insDoc(aux1, gLnk(0,"TBMon disszaszembly                  " , "./virus/tbmon.htm"                  ))
               insDoc(aux1, gLnk(0,"TBAV rezidens részeinek gyilkolása..." , "./virus/tbavkill.htm"               ))
               aux2 = insFld(aux1, gFld("Vírus források                  " , "javascript:;"                       ))
                      insDoc(aux2, gLnk(0,"AIDS                          " , "./virus/aids.pas"                   ))
                      insDoc(aux2, gLnk(0,"CIH 1.4                       " , "./virus/cih14.asm"                  ))
                      insDoc(aux2, gLnk(0,"GaLaDRieL                     " , "./virus/corel.csc"                  ))
                      insDoc(aux2, gLnk(0,"Melissa                       " , "./virus/melissa.src"                ))
                      insDoc(aux2, gLnk(0,"Yankee Doodle                 " , "./virus/yankee2.asm"                ))
                      insDoc(aux2, gLnk(0,"Win32.Cabanas.2999            " , "./virus/cabanas.asm"                ))
        aux1 = insFld(foldersTree, gFld("C R A C K                       " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"Riport Lukundoo-val a HPA-ból        " , "./crack/lukundoo.htm"               ))
               insDoc(aux1, gLnk(0,"Bevezetés a crack világába...        " , "./crack/crk_bev.htm"                ))
               insDoc(aux1, gLnk(0,"A HPA Crack Tutor-okról              " , "./crack/crktutrol.htm"              ))
               aux2 = insFld(aux1, gFld("HPA Kezdô tutoriálok            " , "javascript:;"                       ))
                      insDoc(aux2, gLnk(0,"1. HPA Crack Tutoriál         " , "./crack/crktut1.htm"                ))
                      insDoc(aux2, gLnk(0,"2. HPA Crack Tutoriál         " , "./crack/crktut2.htm"                ))
                      insDoc(aux2, gLnk(0,"3. HPA Crack Tutoriál         " , "./crack/crktut3.htm"                ))
                      insDoc(aux2, gLnk(0,"4. HPA Crack Tutoriál         " , "./crack/crktut4.htm"                ))
                      insDoc(aux2, gLnk(0,"5. HPA Crack Tutoriál         " , "./crack/crktut5.htm"                ))
                      insDoc(aux2, gLnk(0,"6. HPA Crack Tutoriál         " , "./crack/crktut6.htm"                ))
               aux2 = insFld(aux1, gFld("HPA Haladó tutoriálok           " , "javascript:;"                       ))
                      insDoc(aux2, gLnk(0,"18. HPA Crack Tutoriál        " , "./crack/crktut18.htm"               ))
        aux1 = insFld(foldersTree, gFld("H A C K                         " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"H0gy szerezzünk IP-t OP j0g nélkül?  " , "./hack/iponmsn.txt"                 ))
               insDoc(aux1, gLnk(0,"PWL HACKING TUTORIAL v2.0            " , "./hack/BSA.htm"                     ))
               aux2 = insFld(aux1, gFld("Programok, scriptek             " , "javascript:;"                       ))
                      insDoc(aux2, gLnk(0,"Network Security Scanner      " , "./hack/programs/Nss_2000pre1.tar.gz"))
                      insDoc(aux2, gLnk(0,"Hackelt kernelmodul - part 1  " , "./hack/programs/ide.c"              ))
                      insDoc(aux2, gLnk(0,"Hackelt kernelmodul - part 2  " , "./hack/programs/hide.c"             ))
                      insDoc(aux2, gLnk(0,"Sniffer Log Analyzer by cyrax " , "./hack/programs/analized.c"         ))
               aux2 = insFld(aux1, gFld("Feltört oldalak                 " , "javascript:;"                       ))
                      insDoc(aux2, gLnk(0,"www.centralauto.hu            " , "./hack/hacked/centralauto.hu.htm"   ))
                      insDoc(aux2, gLnk(0,"www.cool.com                  " , "./hack/hacked/cool.com.htm"         ))
                      insDoc(aux2, gLnk(0,"www.mrs.com                   " , "./hack/hacked/mrs.com.htm"          ))
                      insDoc(aux2, gLnk(0,"www.adulttv.com               " , "./hack/hacked/adulttv.com.htm"      ))
       aux1 =  insFld(foldersTree, gFld("H U M O R                       " , "javascript:;"                       ))
               insDoc(aux1, gLnk(0,"Mielôtt röhögnél, azaz readme.1st    " , "./humor/humor.htm"                  ))
               insDoc(aux1, gLnk(0,"101 Things you do NOT want your System Administrator to say." , "./humor/100.things.sysadmin.says.htm"))
               insDoc(aux1, gLnk(0,"Forgotten Assembly Language Commands " , "./humor/AssemblyLanguageCommands.htm"))
               insDoc(aux1, gLnk(0,"You know you've been hacking too long when..." , "./humor/hack-too-long.htm"  ))
               insDoc(aux1, gLnk(0,'Hacker Horror 1:"Tell-Tale Voltage Regulator"' , "./humor/hkhorr1.htm"        ))
               insDoc(aux1, gLnk(0,"Human DNA                            " , "./humor/human.dna.htm"              ))
               insDoc(aux1, gLnk(0,"The Top 50+ Geek T-Shirt Slogans     " , "./humor/top.50.geek.slogans.htm"    ))
       aux1 = insDoc(foldersTree, gLnk(0,"That's all folks! CUL8R!!!     " , "javascript:;"                       ))