@echo off
cls
echo .                                                                  .
echo      ‹‹                  €
echo     ﬂﬂﬂ  Virus Magazine  € Box 10, Kiev 148, Ukraine       IV  1996
echo     ﬂ€€ ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ € ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ ﬂ ﬂﬂﬂﬂﬁﬂﬂﬂ  €ﬂﬂﬂﬂﬂﬂ€
echo      ﬁ€ €ﬂ‹ €ﬂﬂ ‹ﬂﬂ ‹ﬂﬂ ‹€‹ ‹ﬂﬂ €ﬂ€    › € ‹ﬂ€ € ‹ﬂﬂ €‹‹   € €ﬂﬂ€ €
echo       € € € €ﬂ  €ﬂ  €    €  €ﬂ  € €    € € € € € €   €     € ﬂﬂﬂ€ €
echo       € ﬁ ﬁ ﬁ   ﬁ‹‹ ﬁ‹‹  ﬁ  ﬁ‹‹ ﬁ‹ﬂ     ﬂ€ ﬂ‹€ ﬁ ﬁ‹‹ ﬁ‹‹‹  € €‹‹€ €
echo       ﬁ ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹ ‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹  €‹‹‹‹‹‹€
echo       (C) Copyright, 1994-96, by STEALTH group WorldWide, unLtd.
echo .                                                                  .
tasm demo.asm/m2
tasm emspe.asm/m2
tlink  demo+emspe/t
echo [Polimorphic Demo] (c) Eternal Maverick (1996)