COMMENT |

DESINFECTOR source for free spreading.

(c) 1993-96 by Andrew V. Basharimoff (2:454/2.175@fidonet)

|

; Names of viruses

; Files

Andy			db	'[Andy]/492$'
AntiBAS 		db	'[AntiBAS]/351$'
BrPi			db	'[BrPi]/555$'
AIW2			db	'[AIW]/572$'
Nutcracker		db	'[Nutcracker(AB3)]/2293$'
Day24th 		db	'[Day24h]/140$'
BootEXE 		db	'[BootEXE]/451$'
Viktoria		db	'[Viktoria]/480$'
EXE			db	'[EXE]/3XX$'
Baby_L			db	'[Baby_L(AB)]/674$'
April1st		db	'[April1st]/483$'
MosEven 		db	'[MoscowEvenings]/586$'
Avenger 		db	'[Dark Avenger]/1800$'
S_Nut			db	'[Sombre Nutcracker(AB4)]/3100$'
Juny24th		db	'[June24th]/570$'
October15th		db	'[Friday]/763$'
Day13th 		db	'[Day13th]/200$'
BrPi2			db	'[BrPi]/511$'
Sunday			db	'[Sunday]/202$'
Snowfall		db	'[Snowfall]/1015$'
Radio			db	'[Rdo_Phs]/2000$'
Coder			db	'[Coder1992]/1922$'
Vienna			db	'[Vienna]/648$'
Yankee			db	'[Yankee Doodle(2C)]/2885$'
SVC			db	'[SVC-5]/3103$'
SVC_X			db	'[SVC-5.1]/3103$'
Cascade 		db	'[Cascade]/1701$'
AB1			db	'[Kind Nutcracker(AB1)]/1924$'
AB5			db	'[Gloomy Nutcracker(AB5)]/2900$'
AB5_1			db	'[Gloomy Nutcracker(AB5)]/3139$'
Sv10			db	'[Svetlana v1.0]/1100$'
Sv11			db	'[Svetlana v1.1]/2060$'
Sv12			db	'[Svetlana v1.2]/3410$'
Sv13			db	'[Svetlana v1.3]/4734$'
XAM			db	'[XAM]/797(821)$'
ZAK			db	'[ZAK]/1839$'
Case			db	'[Case]/927$'
AB6			db	'[Dreary Nutcracker(AB6)]/3500$'
Zar			db	'[Zarin]/489$'
Zar1			db	'[Zarin]/491$'
Eddie			db	'[Eddie]/2000$'
Hymn			db	'[Hymn]/2144$'
Atn			db	'[Attention]/394$'
Jmp165			db	'[Jmp]/165$'
Vien534 		db	'[Vienna]/534$'
Alex			db	'[ALEX]/599$'
SVC_4			db	'[SVC-4]/1689$'
SVC_4_X 		db	'[SVC-4]/1740$'
Hope			db	'[Gloomy Nutcracker(AB5)]/2725$'
Frodo			db	'[Frodo]/369$'
Wishes			db	'[Wishes]/981$'
Retn155 		db	'[Retn]/155$'
NoExec			db	'[NoEXEC]/224$'
MSmall			db	'[MSmall]/409$'
KosKon			db	'[KosKon]/313$'
Exit			db	'[Exit]/376$'
ATrace			db	'[AntiTrace]/1946$'
ATrace1 		db	'[AntiTrace]/1864$'
Ng2_1			db	'[NG-2.1]/706$'
Ng2_3			db	'[NG-2.3]/1036$'
PrtScr			db	'[PrintScr]/1024$'
FBug			db	'[FBug]/699$'
DM			db	'[DM]/400$'
Tiny114 		db	'[Tiny]/114$'
Tiny118 		db	'[Tiny]/118$'
Tiny141 		db	'[Tiny]/141$'
Tiny132 		db	'[Tiny]/132$'
AT			db	'[AT]/144$'
Ninja			db	'[Ninja]/1376$'
Try			db	'[Try]/1074$'
Crazy			db	'[CrazyImp v1.5]/1402$'
AntiARJ 		db	'[AntiARJ]/348$'
AntiARJ_1		db	'[AntiARJ]/333$'
AB7			db	'[Nutcracker(AB7)]/2000$'
Noril			db	'[Norilsk]/502$'
Info			db	'[INFO]/2259$'
BootEXE2		db	'[BootEXE]/452$'
InfoSYS 		db	'[INFOSYS]/2191$'
TaiPan			db	'[Tai-Pan]/438$'
LoveBuzz		db	'[LoveBuzz]/591$'
Viktoria2		db	'[Viktoria]/550$'
NLA			db	'[NLA]/383$'
Ambul			db	'[Ambulance]/796$'
SVC_3			db	'[SVC-3]/1064$'
ATrace2 		db	'[AntiTrace]/2122$'
Snowfall3		db	'[Snowfall]/945$'
MRTI557 		db	'[MRTI]/557$'
MRTI576 		db	'[MRTI]/576$'
MRTI644 		db	'[MRTI]/644$'
Metal400		db	'[MetallicA]/400$'
Metal500		db	'[MetallicA]/500$'
Licee944		db	'[Licee]/944$'
Licee1888		db	'[Licee]/1888$'
Info2			db	'[INFOSYS]/2142$'

; Boot

Veronika		db	'[Veronika]/MBR$'
AndrewII		db	'[Andrew_II]/Boot$'
AndrewII1		db	'[Andrew_II"]/Boot$'
Andrew			db	'[Andrew]/MBR$'
Andrew1 		db	'[Andrew"]/MBR$'
BootEXE1		db	'[BootEXE]/Boot$'
Ball			db	'[Italian bouncing]/Boot$'
S_Nut1			db	'[Sombre Nutcracker]/MBR$'
AntiEXE 		db	'[AntiEXE]/MBR$'
Keydrop 		db	'[Keydrop]/MBR$'
Stoned			db	'[Stoned]/MBR$'
GNut1			db	'[Gloomy Nutcracker(AB5)]/MBR$'
Punish			db	'[Punisher]/MBR$'
Murky			db	'[Murky]/MBR$'
D_Nut			db	'[Dreary Nutcracker(AB6)]/MBR$'
SVK			db	'[SVK]/MBR$'
Mich			db	'[Michaelangelo]/MBR$'
Bloody			db	'[Bloody]/MBR$'
Antigame		db	'[Antigame]/MBR$'
AntiTel 		db	'[AntiTel]/MBR$'
Abs_2			db	'[Abs-2]/MBR$'
Monkey			db	'[Monkey1992]/MBR$'
AB7_1			db	'[Nutcracker(AB7)]/MBR$'
AntiCMOS		db	'[AntiCMOS]/MBR$'
Spirit			db	'[Spirit]/MBR$'
Super			db	'[Superunknown]/MBR$'
Ripper			db	'[JackRipper]/MBR$'
BUPT			db	'[BUPT]/MBR$'

; Viruses signatures

; Signature of viruses in files

File_Signature: 	;20 bytes for virus

;Memory Resident viruses

;April1st
		db	2	;type of virus
;0 - write to begin(old begin to end saved)
;1 - write to exe header(zero lenght)
;2 - write to end
;3 - encrypted virus(need decrypt)
;4 - AB7 virus(no data stored)
;5 - worm virus(INFO)
;7F - AB1 virus
;80 - Boot virus
		db	0	;offset signature at entry point
		db	0E8h,0,0,5Eh,81h,0EEh,3,2,8Ch,0D8h,2Eh,1,84h,0AAh,2
		db	2Eh	;signature
		dw	April1st	;offset string of name of the virus
		dw	April1st_Table	;lenght of virus(0,1) or offset
					;data table(2,3)
Len_Struc	equ	$-File_Signature
;BrPI
		db	2
		db	1Ah
		db	6,1Eh,0B4h,0FEh,0CDh,21h,80h,0FCh,0,74h,53h,0A1h,2,0
		db	2Dh,0
		dw	BrPI
		dw	BrPI_Table
;AIW2
		db	2
		db	0
		db	0E8h,0,0,5Dh,81h,0EDh,3,1,0C6h,86h,0DAh,2,0,0B4h,0F6h,0CDh
		dw	AIW2
		dw	AIW2_Table
;Viktoria
		db	0
		db	0
		db	0FCh,0B8h,0DDh,0F0h,0CDh,21h,3Ch,50h,74h,69h,8Bh,0Eh,2
		db	0,2Bh,0C0h
		dw	Viktoria
		dw	480
;Nutcracker
		db	2
		db	0
		db	0E8h,0,0,5Eh,81h,0EEh,3,0,9Ch,50h,53h,51h,52h,57h,55h,1Eh
		dw	Nutcracker
		dw	Nutcracker_Table
;Baby_L
		db	2
		db	0
		db	0E8h,0,0,5Eh,83h,0EEh,3,9Ch,50h,53h,51h,52h,57h,1Eh,6,0B4h
		dw	Baby_L
		dw	BabyL_Table
;BootEXE
		db	1
		db	0
		db	0A1h,2,0,0BAh,80h,0,2Bh,0C2h,0BEh,0,1,0BBh,92h,1
		db	0EBh,21h
		dw	BootEXE
		dw	-1
;Avenger
		db	2
		db	0
		db	0E8h,0,0,5Eh,81h,0EEh,6Bh,0,0FCh,2Eh,81h,0BCh,5,7,4Dh
		db	5Ah
		dw	Avenger
		dw	Avenger_Table
;S_Nut
		db	2
		db	0
		db	0E8h,0,0,5Eh,81h,0EEh,77h,0Ah,9Ch,50h,53h,51h,52h,57h
		db	1Eh,6
		dw	S_Nut
		dw	SNut_Table
;Juny24th
		db	2
		db	0
		db	2Bh,0DBh,53h,9Dh,0E8h,0,0,0B4h,2Ah,0CDh,21h,5Eh,81h
		db	0EEh,7,1
		dw	Juny24th
		dw	Juny24th_Table
;EXE
		db	1
		db	0
		db	0FCh,0FAh,8Bh,16h,2,0,2Bh,0C0h,8Eh,0C0h,26h,0C5h,6,4Ch
		db	0,0BFh
		dw	EXE
		dw	-1
;October15th
		db	2
		db	0
		db	0E8h,0,0,5Eh,81h,0EEh,3,1,8Ch,0D8h,2Eh,1,84h,0AEh,1,2Eh
		dw	October15th
		dw	October15th_Table
;BrPi2
		db	2
		db	8
		db	5Eh,81h,0EEh,3,2,8Ch,0D8h,2Eh,1,84h,6,2,2Eh,83h,84h,6
		dw	BrPi2
		dw	BrPi2_Table
;Snowfall
		db	2
		db	0FFh
		db	2,8Ch,6,22h,0,0C7h,6,84h,0,0FFh,2,8Ch,6,86h,0,0E9h
		dw	Snowfall
		dw	Snowfall_Table
;Radio
		db	3
		db	0
		db	0FCh,1Eh,6,33h,0F6h,9Ch,56h,0Eh,8Eh,0DEh,0C7h,6,4,0
		db	62h,1
		dw	Radio
		dw	Radio_Ens
;Coder
		db	3
		db	4
		db	50h,6,1Eh,0E8h,0,0,5Eh,2Eh,8Ah,44h,0F9h,3Ch,0,74h,11h
		db	8Bh
		dw	Coder
		dw	Coder_Ens

;Yankee
		db	2
		db	0
		db	0E8h,0,0,5Bh,81h,0EBh,0D4h,7,2Eh,0C6h,87h,5Ch,0,0FFh
		db	0FCh,2Eh
		dw	Yankee
		dw	Yankee_Table
;SVC
		db	3
		db	0
		db	0E8h,0,0,5Eh,83h,0EEh,3,2Eh,89h,84h,11h,0Ch,6,56h,33h
		db	0D2h
		dw	SVC
		dw	SVC_Ens
;Cascade
		db	3
		db	0
		db	0FAh,8Bh,0ECh,0E8h,0,0,5Bh,81h,0EBh,31h,1,2Eh,0F6h,87h
		db	2Ah,1
		dw	Cascade
		dw	Cascade_Ens
;AB5
		db	2
		db	0
		db	2Bh,0FFh,57h,9Dh,0E8h,43h,0,4Fh,6Eh,6Ch,79h,20h,74h,68h
		db	65h,20h
		dw	AB5
		dw	AB5_table
;Sv10
		db	3
		db	20h
		db	33h,0C0h,8Eh,0D8h,0C4h,6,84h,0,2Eh,89h,84h,0EFh,3,2Eh
		db	8Ch,84h
		dw	Sv10
		dw	Sv10_Ens
;Sv11
		db	3
		db	20h
		db	5Eh,56h,6,33h,0C0h,8Eh,0D8h,0C4h,6,84h,0,2Eh,89h,84h
		db	0F6h,6
		dw	Sv11
		dw	Sv11_Ens
;Sv12
		db	3
		db	20h
		db	5Eh,56h,6,33h,0C0h,8Eh,0D8h,0C4h,6,84h,0,2Eh,89h,84h
		db	0EAh,0Bh
		dw	Sv12
		dw	Sv12_Ens
;Sv13
		db	3
		db	20h
		db	5Eh,56h,6,33h,0C0h,8Eh,0D8h,0C4h,6,84h,0,2Eh,89h,84h
		db	64h,10h
		dw	Sv13
		dw	Sv13_Ens
;AB5_1
		db	2
		db	0
		db	2Bh,0FFh,57h,9Dh,0E8h,29h,0,55h,8Bh,0ECh,2Eh,81h,3Eh,8Bh
		db	1,0
		dw	AB5_1
		dw	AB5_1_table
;XAM_COM
		db	2
		db	74h
		db	33h,0F6h,0E8h,9Ah,0FFh,8Ch,0C0h,5,10h,0,2Eh,1,6,2Bh,3,2Eh
		dw	XAM
		dw	XAM_table
;ZAK
		db	3
		db	0
		db	0E8h,0,0,5Eh,81h,0EEh,1Bh,3,56h,50h,50h,58h,6,0Eh,1Fh,8Ch
		dw	ZAK
		dw	ZAK_Ens
;Case
		db	3
		db	0
		db	0FAh,0E8h,0,0,5Bh,81h,0EBh,0Ch,1,8Dh,0B7h,1Fh,1,0B9h
		db	88h,3
		dw	Case
		dw	Case_Ens
;AB1
		db	7Fh
		db	1D3h-185h
		db	80h,3Dh,4Dh,74h,1,0C3h,0F9h,13h,45h,3,0EBh,0EDh,0B9h
		db	1Eh,1,8Bh
		dw	AB1
		dw	0
;AB6
		db	2
		db	10h
		db	0C4h,6,4Ch,0,2Eh,89h,84h,38h,2,2Eh,8Ch,84h,3Ah,2,0C4h,6
		dw	AB6
		dw	AB6_table
;Eddie
		db	2
		db	0
		db	0FCh,0E8h,0,0,5Eh,83h,0EEh,64h,90h,2Eh,0F6h,94h,89h,7,2Eh
		db	81h
		dw	Eddie
		dw	Eddie_Table
;AB6_1
		db	2
		db	10h
		db	0C4h,6,4Ch,0,2Eh,89h,84h,3Bh,2,2Eh,8Ch,84h,3Dh,2,0C4h,6
		dw	AB6
		dw	AB6_1_table
;Himn
		db	3
		db	12h
		db	1Eh,6,33h,0C0h,8Eh,0D8h,0FBh,2Eh,8Bh,94h,10h,0,0ECh,34h
		db	3,0EEh
		dw	Hymn
		dw	Hymn_Ens
;Atn
		db	2
		db	30h
		db	50h,53h,51h,52h,57h,56h,1Eh,6,80h,0FCh,4Bh,74h,0Dh,7
		db	1Fh,5Eh
		dw	Atn
		dw	Atn_table
;Veronika
		db	80h
		db	0
		db	0FAh,33h,0C0h,8Eh,0D8h,8Eh,0C0h,8Eh,0D0h,48h,48h,8Bh,0E0h
		db	0FBh,32h,0E4h
		dw	Veronika
		dw	Sub_Veronika
;AndrewII
		db	80h
		db	0
		db	0BDh,4Ah,00h,0BEh,00h,7Ch,2Bh,0FFh,0FAh,8Eh,0D7h,8Bh,0E6h
		db	0FBh,8Eh,0DFh
		dw	AndrewII
		dw	Sub_AndrewII
;AndrewII1
		db	80h
		db	0
		db	0BBh,4Ah,00h,0BEh,00h,7Ch,2Bh,0FFh,0FAh,8Eh,0D7h,8Bh,0E6h
		db	0FBh,8Eh,0DFh
		dw	AndrewII1
		dw	Sub_AndrewII1
;Andrew
		db	80h
		db	52h-1Eh
		db	0C4h,0Eh,4Ch,0,89h,0Eh,0B7h,1,8Ch,6,0B9h,1,7,26h,8Ch
		db	1Eh
		dw	Andrew
		dw	Sub_Andrew
;Andrew1
		db	80h
		db	52h-1Eh
		db	0C4h,16h,4Ch,0,89h,16h,0B3h,1,8Ch,6,0B5h,1,7,26h,8Ch
		db	1Eh
		dw	Andrew1
		dw	Sub_Andrew
;Ball
		db	80h
		db	0
		db	33h,0C0h,8Eh,0D0h,0BCh,00h,7Ch,8Eh,0D8h,0A1h,13h,04h,2Dh
		db	2,0,0A3h
		dw	Ball
		dw	Sub_Ball
;AntiEXE
		db	80h
		db	0
		db	33h,0FFh,8Eh,0DFh,0C4h,16h,4Ch,0,89h,16h,4Ch,3,8Ch
		db	6,4Eh,3
		dw	AntiEXE
		dw	Sub_AntiEXE
;Keydrop
		db	80h
		db	7Eh-38h
		db	33h,0D2h,8Eh,0C2h,0BFh,0,7Ch,0Eh,1Fh,8Bh,1Eh,36h,0,0E8h
		db	0BBh,0
		dw	Keydrop
		dw	Sub_Keydrop
;Stoned
		db	80h
		db	0A1h
		db	33h,0C0h,8Eh,0D8h,0FAh,8Eh,0D0h,0BCh,0,7Ch,0FBh,0A1h
		db	4Ch,0,0A3h,9
		dw	Stoned
		dw	Sub_Stoned
;Punisher
		db	80h
		db	0
		db	2Bh,0DBh,53h,9Dh,0B8h,40h,0,8Eh,0D8h,0BEh,0,78h,8Eh,0D0h
		db	8Bh,0E6h
		dw	Punish
		dw	Sub_Punish
;Murky
		db	80h
		db	0
		db	0FCh,0FAh,0BEh,0,7Ch,2Bh,0FFh,2Bh,0DBh,2Bh,0EDh,8Eh
		db	0D3h,8Bh,0E6h,8Eh
		dw	Murky
		dw	Sub_Murky
;SVK
		db	80h
		db	0
		db	0Eh,0E8h,0ABh,0,50h,0D1h,0E8h,0FEh,0CCh,74h,3,0E9h,6Ch
		db	1,53h,51h
		dw	SVK
		dw	Sub_SVK
;Mich
		db	80h
		db	0
		db	33h,0C0h,8Eh,0D8h,0FAh,8Eh,0D0h,0B8h,0,7Ch,8Bh,0E0h,0FBh
		db	1Eh,50h,0A1h
		dw	Mich
		dw	Sub_Mich
;Bloody
		db	80h
		db	0C0h
		db	33h,0C0h,8Eh,0D8h,0FAh,8Eh,0D0h,0BCh,0,7Ch,0FBh,0A1h,4Ch
		db	0,0A3h,0Bh
		dw	Bloody
		dw	Sub_Bloody
;Antigame
		db	80h
		db	0
		db	33h,-1,8Eh,0DFh,0FAh,0C4h,16h,4Ch,0,89h,16h,0Ch,3,8Ch,6
		db	0Eh
		dw	Antigame
		dw	Sub_Antigame
;SVC_4
		db	2
		db	29h
		db	2Eh,89h,84h,45h,6,2Eh,8Ch,9Ch,47h,6,7,0B8h,0,49h,0CDh
		db	21h
		dw	SVC_4
		dw	SVC_4_table
;Hope
		db	2
		db	30h
		db	0CDh,21h,8Eh,0DBh,83h,0C3h,10h,2Eh,1,9Ch,61h,1,2Eh,1,9Ch
		db	59h
		dw	Hope
		dw	Hope_table
;AntiTel
		db	80h
		db	0
		db	0BBh,0,7Ch,33h,0C0h,0FAh,8Eh,0D0h,8Bh,0E3h,0FBh,8Eh,0D8h
		db	0A1h,13h,4
		dw	AntiTel
		dw	Sub_AntiTel
;Wishes
		db	2
		db	10h
		db	81h,0EEh,33h,1,8Bh,0EEh,1,0C6h,0BFh,0,1,2Eh,83h,0BEh,0Eh
		db	0
		dw	Wishes
		dw	Wishes_Table
;NoEXEC
		db	2
		db	10h
		db	0ECh,8Bh,5Eh,0,83h,0EBh,0Fh,0B4h,0F6h,0CDh,21h,3Dh,34h
		db	12h,75h,5
		dw	NoEXEC
		dw	NoEXEC_Table
;MSmall
		db	2
		db	51h-4
		db	0BFh,0DEh,0,0B1h,2,0F3h,0A5h,0E8h,0DAh,0,0FAh,0C7h,44h
		db	0FCh,84h,0
		dw	MSmall
		dw	MSmall_Table
;KosKon
		db	2
		db	0Bh
		db	5Bh,83h,0EBh,0Bh,0B8h,0CCh,0CCh,0CDh,21h,3Dh,0BBh,0BBh
		db	74h,50h,0FCh,8Ch
		dw	KosKon
		dw	KosKon_Table
;Exit
		db	2
		db	10h
		db	8,2,0E8h,0,74h,17h,0BFh,8,2,0B9h,78h,1,0FCh,0F3h,0A4h,0BFh
		dw	Exit
		dw	Exit_Table
;ATrace
		db	2
		db	9Ch
		db	0B9h,9Ah,7,0FCh,0F3h,0A4h,0BFh,0A0h,0,0FAh,33h,0D2h,8Eh
		db	0DAh,0BAh,0E3h
		dw	ATrace
		dw	ATrace_Table
;ATrace1
		db	2
		db	5Ah
		db	48h,7,0F3h,0A4h,0FAh,33h,0D2h,8Eh,0DAh,8Bh,16h,84h,0,26h
		db	89h,16h
		dw	ATrace1
		dw	ATrace1_Table
;Abs_2
		db	80h
		db	0
		db	31h,0C0h,8Eh,0D8h,8Eh,0D0h,0BCh,0,7Ch,0A1h,4Ch,0,0A3h,6Ch
		db	7Ch,0A1h
		dw	Abs_2
		dw	Sub_Abs_2
;Ng2_3
		db	0
		db	3Ch
		db	1Eh,33h,0C0h,8Eh,0D8h,8Ch,0C8h,3Bh,6,82h,0,1Fh,72h,0Ah
		db	0B8h,0F6h
		dw	Ng2_3
		dw	1036
;Ng2_1
		db	0
		db	0ACh
		db	0FAh,2Bh,0C0h,8Eh,0C0h,26h,0FFh,36h,4Ch,0,8Fh,6,2,2,26h
		db	0FFh
		dw	Ng2_1
		dw	706
;PrtScr
		db	0
		db	60h
		db	0D8h,0A1h,13h,4,2Dh,2,0,0A3h,13h,4,6,1Fh,0B8h,21h,35h,0CDh
		dw	PrtScr
		dw	1024
;FBug
		db	2
		db	3
		db	5Bh,33h,0FFh,8Bh,0F3h,83h,0EEh,3,0B8h,4,4Bh,0CDh,21h,3Dh
		db	4Bh,4
		dw	FBug
		dw	FBug_Table
;DM
		db	2
		db	3
		db	5Dh,6,1Eh,33h,0C0h,8Eh,0C0h,26h,80h,3Eh,0,2,6,74h,20h,0BEh
		dw	DM
		dw	DM_Table
;Tiny114
		db	0
		db	10h
		db	0F3h,0A4h,8Eh,0D9h,74h,8,50h,87h,1,0ABh,58h,87h,1,0ABh
		db	1Fh,0ADh
		dw	Tiny114
		dw	114
;Tiny118
		db	0
		db	10h
		db	0F3h,0A5h,8Eh,0DBh,74h,0Ch,50h,87h,5,0ABh,58h,87h,5,0ABh
		db	29h,3Eh
		dw	Tiny118
		dw	118
;Tiny141
		db	2
		db	0
		db	60h,8Bh,0FEh,0E8h,0,0,5Eh,83h,0C6h,2Dh,90h,0A4h,0A5h,0B8h
		db	36h,0
		dw	Tiny141
		dw	Tiny141_Table
;Tiny132
		db	2
		db	0
		db	60h,8Bh,0FEh,3,74h,1,0B0h,31h,3,0F0h,0A4h,0A5h,8Eh,0C0h
		db	33h,0FFh
		dw	Tiny132
		dw	Tiny132_Table
;AT
		db	2
		db	0
		db	60h,8Bh,0FEh,0E8h,0,0,5Eh,83h,0C6h,31h,0A4h,0A5h,0B8h,24h
		db	0,8Eh
		dw	AT
		dw	AT_Table
;Eddie1
		db	2
		db	0
		db	0E8h,0,0,5Eh,90h,90h,81h,0EEh,63h,0,0FCh,2Eh,0F6h,94h,89h,7
		dw	Eddie
		dw	Eddie_Table
;Ninja
		db	3
		db	20h
		db	51h,0E8h,0A8h,3,3Dh,72h,19h,74h,49h,0E8h,50h,4,8Ch,0C0h
		db	48h,8Eh
		dw	Ninja
		dw	Ninja_Ens
;Try
		db	0
		db	90h
		db	4,0,8Bh,44h,89h,3Bh,46h,4,75h,0Bh,8Bh,46h,2,89h,44h,87h
		dw	Try
		dw	1074
;Monkey
		db	80h
		db	63h
		db	0E8h,41h,1,80h,0FCh,2,75h,0Eh,52h,2Bh,0C0h,0CDh,1Ah,80h
		db	0FAh,40h
		dw	Monkey
		dw	Sub_Monkey
;Crazy
		db	0
		db	10h
		db	0,4,50h,52h,56h,57h,1Eh,6,0B0h,74h,0E6h,43h,0B0h,80h,0E6h
		db	41h
		dw	Crazy
		dw	1402
;AntiARJ
		db	1
		db	0D0h-0A4h
		db	89h,45h,0FEh,0Eh,7,83h,0EAh,31h,8Ch,0CBh,0F7h,0DBh,3,0DAh
		db	0B4h,4Ah
		dw	AntiARJ
		dw	AntiARJ_cure
;AntiARJ_1
		db	1
		db	0E2h-0B3h
		db	83h,0EAh,30h,2Eh,89h,57h,2,0C7h,47h,4Ch,67h,2,89h,57h,4Eh
		db	8Ch
		dw	AntiARJ_1
		dw	AntiARJ_cure
;AB7
		db	4
		db	0
		db	8Bh,36h,1,1,8Dh,84h,3,1,2Dh,21h,0,50h,0B1h,4,0D3h,0E8h
		dw	AB7
		dw	2000
;AntiCMOS
		db	80h
		db	2Fh-1Eh
		db	0A3h,7,7Ch,8Ch,6,9,7Ch,0A1h,13h,4,48h,48h,0A3h,13h,4,0B1h
		dw	AntiCMOS
		dw	Sub_AntiCMOS
;Spirit
		db	80h
		db	4Ch-3Eh
		db	0E8h,0FFh,0FFh,0Ch,0ADh,0B1h,6,0D3h,0E0h,8Eh,0C0h,0B8h
		db	0EBh,3Ch,0ABh,5Eh
		dw	Spirit
		dw	Sub_Spirit
;AB6_2
		db	2
		db	10h
		db	0C4h,6,84h,0,2Eh,89h,84h,0ECh,9,2Eh,8Ch,84h,0EEh,9,2Eh,89h
		dw	AB6
		dw	AB6_2_table
;Super
		db	80h
		db	13h
		db	80h,3Eh,87h,0,7Bh,74h,11h,0BFh,3,0,2Ah,0E4h,0CDh,13h,0B8h,5
		dw	Super
		dw	Sub_Super
;Super1
		db	80h
		db	13h
		db	3,0,2Ah,0E4h,0CDh,13h,0B8h,5,2,0CDh,13h,73h,0Bh,4Fh,75h,0F2h
		dw	Super
		dw	Sub_Super1
;Info
		db	5
		db	45h
		db	8Bh,84h,16h,0FFh,8Eh,0C0h,26h,2Bh,84h,16h,0FFh,0BEh,0FDh
		db	1,0B9h,0D6h
		dw	Info
		dw	0
;AB6_3
		db	2
		db	10h
		db	0C4h,6,84h,0,2Eh,89h,84h,3Bh,0Ah,2Eh,8Ch,84h,3Dh,0Ah,2Eh,89h
		dw	AB6
		dw	AB6_3_table
;BootEXE_2
		db	1
		db	0
		db	0A1h,2,0,0BAh,80h,0,2Bh,0C2h,0BEh,0,1,0BBh,95h,1
		db	0EBh,21h
		dw	BootEXE2
		dw	-1
;InfoSys
		db	5
		db	45h
		db	8Bh,84h,16h,0FFh,8Eh,0C0h,26h,2Bh,84h,16h,0FFh,13h,0F9h
		db	2Bh,85h,1
		dw	InfoSys
		dw	0
;TaiPan
		db	2
		db	0Ch
		db	3Dh,0CEh,7Bh,75h,17h,0Eh,1Fh,81h,0C6h,0ACh,1,0BFh,0ACh
		db	1,0B9h,0Ah
		dw	TaiPan
		dw	TaiPan_Table
;Ripper
		db	80h
		db	0
		db	0FAh,33h,0C0h,8Eh,0D0h,0BCh,0,7Ch,0FBh,0BEh,50h,7Ch,0Eh
		db	0E8h,92h,0
		dw	Ripper
		dw	Sub_Ripper
;BUPT
		db	80h
		db	2
		db	0C0h,8Eh,0D0h,0BCh,0,7Ch,8Eh,0D8h,8Eh,0C0h,50h,50h,50h
		db	0FBh,0EBh,0D6h
		dw	BUPT
		dw	Sub_BUPT
;LoveBuzz
		db	2
		db	3Bh
		db	0C4h,6,4Ch,0,2Eh,89h,84h,0A5h,0,2Eh,8Ch,84h,0A7h,0,0C4h,6
		dw	LoveBuzz
		dw	LoveBuzz_Table
;Snowfall2
		db	2
		db	0FFh
		db	0C7h,6,20h,0,19h,2,8Ch,6,22h,0,0C7h,6,84h,0,0FFh,2
		dw	Snowfall
		dw	Snowfall2_Table
;Viktoria2
		db	0
		db	61h
		db	0BAh,8Bh,1,0B0h,21h,0CDh,21h,1Eh,7,0Eh,1Fh,29h,4Fh,2,0BEh,0
		dw	Viktoria2
		dw	550
;NLA
		db	1
		db	0D6h
		db	0C7h,47h,4Ch,63h,2,89h,47h,4Eh,0Eh,1Fh,29h,4Fh,2,0BFh,0,1
		dw	NLA
		dw	-1
;SVC_3
		db	2
		db	20h
		db	1Fh,33h,0C0h,8Eh,0D8h,0C5h,6,84h,0,2Eh,89h,84h,0DAh,3,2Eh,8Ch
		dw	SVC_3
		dw	SVC_3_table
;ATrace2
		db	3
		db	30h
		db	0,2Eh,1,9Fh,36h,1,2Eh,0C7h,87h,27h,1,0DDh,0,2Eh,1,9Fh
		dw	ATrace2
		dw	ATrace2_Ens
;Snowfall3
		db	2
		db	90h
		db	0C4h,45h,70h,89h,86h,0Ah,1,8Ch,86h,0Ch,1,0C4h,6,84h,0,89h
		dw	Snowfall3
		dw	Snowfall3_Table
;SVC_X
		db	3
		db	0
		db	6,29h,0D2h,0E8h,0,0,5Eh,83h,0EEh,6,2Eh,89h,84h,11h,0Ch,0B4h
		dw	SVC_X
		dw	SVC_Ens
;SVC_4_X
		db	2
		db	29h
		db	2Eh,89h,84h,78h,6,2Eh,8Ch,9Ch,7Ah,6,7,0B8h,0,49h,0CDh,21h
		dw	SVC_4_X
		dw	SVC_4_X_table
;MRTI557
		db	2
		db	30h
		db	7,26h,0A3h,0D0h,2,0B8h,0BBh,1,89h,7,8Bh,47h,2,8Ch,47h,2
		dw	MRTI557
		dw	MRTI557_table
;MRTI576
		db	2
		db	30h
		db	0A5h,1,87h,7,26h,0A3h,0C2h,2,8Ch,0C0h,87h,47h,2,26h,0A3h,0C4h
		dw	MRTI576
		dw	MRTI576_table
;MRTI644
		db	2
		db	30h
		db	87h,7,26h,0A3h,0E5h,2,8Ch,0C0h,87h,47h,2,26h,0A3h,0E7h,2,0BBh
		dw	MRTI644
		dw	MRTI644_table
;Metal400
		db	2
		db	0
		db	8Bh,36h,1,1,0FCh,0B9h,3,0,0BFh,0,1,3,0F7h,0F3h,0A4h,8Ch
		dw	Metal400
		dw	Metal400_table
;Metal500
		db	2
		db	0
		db	0FCh,0B9h,3,0,0BFh,1,1,8Bh,35h,4Fh,0Eh,57h,3,0F7h,0F3h,0A4h
		dw	Metal500
		dw	Metal500_table
;Licee944
		db	2
		db	30h
		db	56h,33h,0FFh,0B9h,0B0h,3,0F3h,0A4h,5Eh,6,1Fh,0B8h,21h,35h,0CDh,21h
		dw	Licee944
		dw	Licee944_table
;Licee1888
		db	2
		db	30h
		db	0Eh,1Fh,56h,33h,0FFh,0B9h,60h,7,0F3h,0A4h,83h,0EEh,4Ch,0B4h,2Ch,0CDh
		dw	Licee1888
		dw	Licee1888_table
;Info2
		db	5
		db	48h
		db	0FFh,8Eh,0C0h,26h,2Bh,84h,16h,0FFh,8Dh,0B4h,41h,1,0B9h,1Dh,7,56h
		dw	Info2
		dw	0

;No - resident viruses

;Andy
		db	0
		db	0
		db	8Bh,2Eh,0A4h,2,0B4h,2Ah,0CDh,21h,80h,0FAh,17h,75h,34h
		db	55h,0B9h,1Dh
		dw	Andy
		dw	492
;AntiBAS
		db	0
		db	0
		db	0BAh,0,0FFh,0B4h,1Ah,0CDh,21h,8Bh,2Eh,1Eh,1,0BAh,0D8h
		db	1,0B8h,24h
		dw	AntiBAS
		dw	351
;MoscowEvenings
		db	0
		db	0
		db	0BAh,0,0FAh,0B4h,1Ah,0CDh,21h,0E8h,44h,1,0B8h,24h
		db	35h,0CDh,21h,53h
		dw	MosEven
		dw	586
;Day24th
		db	0
		db	0
		db	0BFh,0,1,0BAh,0,0FFh,0B4h,1Ah,0CDh,21h,8Bh,2Eh,8Ah,1
		db	0BAh,84h
		dw	Day24th
		dw	140
;Day13th
		db	0
		db	0
		db	0BFh,1Eh,0FEh,0A1h,0BAh,1,0A3h,0BCh,1,0BAh,0,0FEh,0B4h
		db	1Ah,0CDh,21h
		dw	Day13th
		dw	200
;Sunday
		db	0
		db	0
		db	0BFh,1Eh,0FEh,0BAh,0,0FEh,0A1h,0C6h,1,0A3h,0C8h,1,0B4h
		db	1Ah,0CDh,21h
		dw	Sunday
		dw	202
;Vienna
		db	2
		db	4
		db	0FCh,8Bh,0F2h,81h,0C6h,0Ah,0,0BFh,0,1,0B9h,3,0,0F3h
		db	0A4h,8Bh
		dw	Vienna
		dw	Vienna_Table
;XAM_EXE
		db	2
		db	0
		db	33h,0F6h,0E8h,9Ah,0FFh,8Ch,0C0h,5,10h,0,2Eh,1,6,2Bh,3,2Eh
		dw	XAM
		dw	XAM_table
;Zarin
		db	0
		db	16h
		db	21h,80h,0FAh,0Bh,74h,7,80h,0FAh,17h,74h,2,0EBh,0Bh,0E9h
		db	0D1h,0
		dw	Zar
		dw	489
;Zarin1
		db	0
		db	16h
		db	0A3h,44h,1,89h,1Eh,46h,1,7,0B0h,24h,0BAh,0C1h,2,0B4h
		db	25h,0CDh
		dw	Zar1
		dw	491
;S_Nut1
		db	80h
		db	0
		db	33h,0C0h,8Eh,0C0h,8Eh,0D8h,0BBh,0,7Ch,0FAh,8Eh,0D0h,8Bh
		db	0E3h,0FBh,50h
		dw	S_Nut1
		dw	Sub_SNut1
;GNut1
		db	80h
		db	18h
		db	0B9h,3Bh,1,0F3h,0A4h,0C3h,99h,0CDh,13h,80h,0CAh,80h
		db	0FFh,6,3Bh,7Dh
		dw	GNut1
		dw	Sub_GNut1
;GNut1_1
		db	80h
		db	18h
		db	0B9h,46h,1,0F3h,0A4h,0C3h,0BAh,80h,0,0CDh,13h,0FFh,6
		db	46h,7Dh,81h
		dw	GNut1
		dw	Sub_GNut1_1
;BootEXE
		db	80h
		db	1Eh
		db	0BBh,7Ah,1,8Eh,0C0h,0FCh,0BFh,0,1,0B9h,0,2,0F3h,0A4h,6,53h
		dw	BootEXE1
		dw	Sub_BootEXE1
;AB7_1
		db	80h
		db	11h
		db	2Ah,0E4h,0CDh,13h,0B8h,4,2,0CDh,13h,72h,0F5h,0EAh,0F5h
		db	0,0,7Ch
		dw	AB7_1
		dw	Sub_AB7_1
;D_Nut
		db	80h
		db	0
		db	2Bh,0DBh,53h,9Dh,8Eh,0D3h,0BCh,0,7Ch,0BAh,40h,0,8Eh,0DAh
		db	83h,6Fh
		dw	D_Nut
		dw	Sub_DNut
;Jmp165
		db	2
		db	0
		db	0B9h,3,0,0FCh,33h,0DBh,8Bh,0BFh,1,1,83h,0C7h,3,57h,8Dh
		db	0B5h
		dw	Jmp165
		dw	Jmp165_Table
;Retn155
		db	2
		db	0
		db	50h,53h,52h,0B4h,1Ah,0BAh,0D0h,0,0CDh,21h,83h,6Dh,0FEh
		db	3,0E8h,0
		dw	Retn155
		dw	Retn155_Table
;Vien534
		db	2
		db	0Bh
		db	0B9h,3,0,0BFh,0,1,0F3h,0A4h,8Bh,0FAh,0B4h,30h,0CDh,21h
		db	3Ch,0
		dw	Vien534
		dw	Vien534_Table
;ALEX
		db	2
		db	0
		db	50h,8Bh,2Eh,1,1,8Dh,96h,62h,3,0B4h,1Ah,0CDh,21h,0BFh,0
		db	1
		dw	ALEX
		dw	ALEX_Table
;Hope1
		db	80h
		db	20h
		db	13h,80h,0CAh,80h,-1,6,39h,7Dh,81h,26h,39h,7Dh,-1,1,74h
		db	19h
		dw	GNut1
		dw	Sub_Hope
;Frodo
		db	2
		db	13
		db	56h,0FCh,83h,0C6h,88h,0BFh,0,1,0B9h,3,0,0F3h,0A4h,5Eh
		db	0B4h,1Ah
		dw	Frodo
		dw	Frodo_table
;D_Nut_1
		db	80h
		db	0
		db	2Bh,0C0h,0FAh,8Eh,0D0h,0BCh,0,7Ch,8Eh,0C4h,0FBh,8Bh,0D8h,0CDh
		db	13h,0B9h
		dw	D_Nut
		dw	Sub_DNut
;Noril
		db	2
		db	3
		db	0E8h,0B2h,1,51h,0FCh,8Dh,77h,13h,0BFh,0,1,0B9h,3,0,0F3h,0A4h
		dw	Noril
		dw	Noril_Table
;D_Nut_2
		db	80h
		db	0
		db	33h,0C0h,0FAh,8Eh,0D0h,0BCh,0,7Ch,0FBh,8Eh,0C4h,8Bh,0D8h
		db	0CDh,13h,0B9h
		dw	D_Nut
		dw	Sub_DNut
;BootEXE_2
		db	80h
		db	1Eh
		db	0BBh,79h,1,8Eh,0C0h,0FCh,0BFh,0,1,0B9h,0,2,0F3h,0A4h,6,53h
		dw	BootEXE1
		dw	Sub_BootEXE2
;Ambulance
		db	2
		db	10h
		db	0D2h,1,8Dh,9Ch,19h,4,0BFh,0,1,8Ah,7,88h,5,8Bh,47h,1
		dw	Ambul
		dw	Ambul_Table
;Metal500_EXE
		db	2
		db	10h
		db	0FCh,6,0FAh,33h,0DBh,8Eh,0C3h,0BFh,0,2,26h,83h,3Dh,3Dh,74h,1Dh
		dw	Metal500
		dw	Metal500_table

		dw	-1		; end word

Kind_Sign	db	2Bh,0FFh,57h,9Dh,0E8h,25h,0,44h,65h,64h,69h,63h,61h,74h
		db	65h,64h

; Memory Signature

Mem_Signature:

;April1st
num_sign	db	0
off_in_seg	dw	200h
hooked_ints	db	21h
old_addr	dw	2DAh,-1
new_addr	dw	2CAh
		db	-1	; end
;BrPI
		db	1
		dw	21Ah
		db	21h
		dw	2D9h,-1
		dw	2C9h
		db	-1
;AIW2
		db	2
		dw	100h
		db	21h
		dw	338h,-1
		dw	2DBh
		db	-1
;Viktoria
		db	3
		dw	100h
		db	21h
		dw	1ECh,0
		dw	183h
		db	-1
;Nutcracker
		db	4
		dw	0
		db	21h
		dw	257h,-1
		dw	1EEh
		db	10h
		dw	640h,-1
		dw	636h
		db	-1
;Baby_L
		db	5
		dw	0
		db	21h
		dw	198h,0
		dw	0D1h
		db	-1
;BootEXE
		db	6
		dw	13Bh
		db	13h
		dw	0,-1
		dw	201h
		db	-1
;Avenger
		db	7
		dw	68h
		db	21h
		dw	74Fh,-1
		dw	2EEh
		db	27h
		dw	74Bh,-1
		dw	2A9h
		db	-1
;S_Nut
		db	8
		dw	0A74h
		db	21h
		dw	83h,-1
		dw	0
		db	-1
;Juny24th
		db	9
		dw	100h
		db	21h
		dw	1B8h,-1
		dw	192h
		db	-1
;EXE
		db	10
		dw	17Fh
		db	13h
		dw	7Dh*4,0
		dw	276h
		db	-1
;October15th
		db	11
		dw	100h
		db	21h
		dw	20Fh,-1
		dw	1DFh
		db	-1
;BrPi2
		db	12
		dw	208h
		db	21h
		dw	2CDh,-1
		dw	2BDh
		db	-1
;Snowfall
		db	13
		dw	1FFh
		db	8
		dw	216h,-1
		dw	214h
		db	21h
		dw	4C0h,-1
		dw	2FFh
		db	-1
;Radio
		db	14
		dw	0
		db	21h
		dw	1E6h,-1
		dw	1B0h
		db	28h
		dw	63Dh,-1
		dw	5DCh
		db	-1
;Coder
		db	15
		dw	4
		db	21h
		dw	5DFh,-1
		dw	5F6h
		db	-1
;Yankee
		db	16
		dw	7D1h
		db	21h
		dw	2Ah,-1
		dw	3C8h
		db	1Ch
		dw	36h,-1
		dw	237h
		db	-1
;SVC
		db	17
		dw	0
		db	21h
		dw	0BA6h,-1
		dw	142h
		db	8
		dw	0BA2h,-1
		dw	7A2h
		db	-1
;Cascade
		db	18
		dw	101h
		db	21h
		dw	137h,-1
		dw	31Ch
		db	1Ch
		dw	133h,-1
		dw	6B0h
		db	28h
		dw	13Bh,-1
		dw	722h
		db	-1
;AB5
		db	19
		dw	8B6h
		db	21h
		dw	212h,-1
		dw	198h
		db	-1
;Sv10
		db	20
		dw	20h
		db	21h
		dw	3EFh,-1
		dw	10Ch
		db	-1
;Sv11
		db	21
		dw	20h
		db	8
		dw	6FAh,-1
		dw	277h
		db	9
		dw	6FEh,-1
		dw	2ADh
		db	21h
		dw	6F6h,-1
		dw	156h
		db	-1
;Sv12
		db	22
		dw	20h
		db	8
		dw	0BEEh,-1
		dw	6FCh
		db	9
		dw	0BF6h,-1
		dw	60Ah
		db	1Ch
		dw	0BF2h,-1
		dw	341h
		db	21h
		dw	0BEAh,-1
		dw	7C8h
		db	-1
;Sv13
		db	23
		dw	20h
		db	8
		dw	1068h,-1
		dw	6FCh
		db	9
		dw	1070h,-1
		dw	60Ah
		db	1Ch
		dw	106Ch,-1
		dw	341h
		db	21h
		dw	1064h,-1
		dw	7C8h
		db	-1
;AB5_1
		db	24
		dw	942h
		db	21h
		dw	26Eh,-1
		dw	1A0h
		db	-1
;XAM
		db	25
		dw	3+74h
		db	21h
		dw	0DDh,-1
		dw	0ABh
		db	-1
;ZAK
		db	26
		dw	318h
		db	21h
		dw	0Ah,-1
		dw	42Ch
		db	-1
;Case
		db	27
		dw	0
		db	21h
		dw	3A5h,-1
		dw	0F6h
		db	28h
		dw	3A9h,-1
		dw	361h
		db	1Ch
		dw	3A1h,-1
		dw	314h
		db	-1
;AB1
		db	28
		dw	100h+1D3h-185h
		db	21h
		dw	3A4h,-1
		dw	2B8h
		db	-1
;AB6
		db	29
		dw	0B4Fh
		db	13h
		dw	238h,-1
		dw	216h
		db	17h
		dw	312h,-1
		dw	2D6h
		db	21h
		dw	3E8h,-1
		dw	31Eh
		db	-1
;Eddie
		db	30
		dw	60h
		db	21h
		dw	818h,-1
		dw	359h
		db	27h
		dw	814h,-1
		dw	331h
		db	-1
;AB6_1
		db	31
		dw	0B56h
		db	13h
		dw	23Bh,-1
		dw	219h
		db	17h
		dw	315h,-1
		dw	2D9h
		db	21h
		dw	3EBh,-1
		dw	321h
		db	-1
;Hymn
		db	32
		dw	17h
		db	21h
		dw	8A8h,-2
		dw	Hymn_Mem
		db	-1
;Atn
		db	33
		dw	40h
		db	21h
		dw	15h,-1
		dw	40h
		db	-1
;Veronika
		db	34
		dw	40h
		db	13h
		dw	5Eh,-1
		dw	0BBh
		db	-1
;AndrewII
		db	35
		dw	0B9h
		db	13h
		dw	1ACh,0
		dw	1Eh
		db	-1
;AndrewII1
		db	36
		dw	0B9h
		db	13h
		dw	1ACh,0
		dw	1Eh
		db	-1
;Andrew
		db	37
		dw	52h
		db	13h
		dw	1B7h,-1
		dw	0FEh
		db	-1
;Andrew1
		db	38
		dw	52h
		db	13h
		dw	1B3h,-1
		dw	0FDh
		db	-1
;Ball
		db	39
		dw	1Eh
		db	13h
		dw	12Ah,-1
		dw	0D0h
		db	-1
;AntiEXE
		db	40
		dw	117h
		db	13h
		dw	0D3h*4,0
		dw	27h
		db	-1
;Keydrop
		db	41
		dw	7Eh
		db	13h
		dw	24h,-1
		dw	592h
		db	-1
;Stoned
		db	42
		dw	0A1h
		db	13h
		dw	9,-1
		dw	15h
		db	-1
;Punisher
		db	43
		dw	0
		db	8
		dw	1A6h,-1
		dw	1A4h
		db	9
		dw	2BFh,-1
		dw	266h
		db	10h
		dw	2D5h,-1
		dw	2C3h
		db	13h
		dw	348h,-1
		dw	2D9h
		db	15h
		dw	39Bh,-1
		dw	380h
		db	21h
		dw	3F3h,-1
		dw	3E8h
		db	2Fh
		dw	45Ch,-1
		dw	41Ah
		db	40h
		dw	3A5h,-1
		dw	39Fh
		db	-1
;Murky
		db	44
		dw	1Eh
		db	13h
		dw	1F9h,-1
		dw	0BBh
		db	-1
;SVK
		db	45
		dw	40h
		db	13h
		dw	1BCh,-1
		dw	44h
		db	-1
;Mich
		db	46
		dw	0AFh
		db	13h
		dw	0Ah,-1
		dw	0Eh
		db	-1
;Bloody
		db	47
		dw	0C0h
		db	13h
		dw	0Bh,-1
		dw	1Fh
		db	-1
;Antigame
		db	48
		dw	0CAh
		db	13h
		dw	0C3h*4,0
		dw	1Eh
		db	-1
;SVC_4
		db	49
		dw	29h
		db	21h
		dw	645h,-1
		dw	0EBh
		db	-1
;Hope
		db	50
		dw	314Fh-(3126h-926h)
		db	21h
		dw	218h,-1
		dw	19Eh
		db	-1
;AntiTel
		db	51
		dw	1Eh
		db	13h
		dw	0AEh,-1
		dw	29Fh
		db	-1
;Wishes
		db	52
		dw	143h
		db	21h
		dw	0,-1
		dw	14h
		db	-1
;NoEXEC
		db	53
		dw	110h
		db	21h
		dw	1CCh,-1
		dw	154h
		db	-1
;MSmall
		db	54
		dw	51h
		db	21h
		dw	0DEh,-1
		dw	84h
		db	-1
;KosKon
		db	55
		dw	0Bh
		db	21h
		dw	0A0h,-1
		dw	8Eh
		db	-1
;Exit
		db	56
		dw	218h
		db	20h
		dw	288h,-1
		dw	282h
		db	21h
		dw	29Dh,-1
		dw	28Ch
		db	-1
;ATrace
		db	57
		dw	9Ch
		db	21h
		dw	17Bh,-1
		dw	1E3h
		db	-1
;ATrace1
		db	58
		dw	5Ah
		db	21h
		dw	3EBh,-1
		dw	35Bh
		db	-1
;Abs_2
		db	59
		dw	8Eh
		db	13h
		dw	6Ch,-1
		dw	0Bh
		db	-1
;Ng2_3
		db	60
		dw	13Ch
		db	13h
		dw	2FFh,-1
		dw	306h
		db	20h
		dw	2A1h,-1
		dw	2ABh
		db	21h
		dw	2D1h,-1
		dw	2D5h
		db	27h
		dw	2B6h,-1
		dw	2BCh
		db	28h
		dw	31Bh,-1
		dw	31Fh
		db	-1
;Ng2_1
		db	61
		dw	1ACh
		db	13h
		dw	202h,-1
		dw	209h
		db	28h
		dw	21Eh,-1
		dw	222h
		db	-1
;PrtScr
		db	62
		dw	60h
		db	21h
		dw	9,-1
		dw	0BFh
		db	-1
;FBug
		db	63
		dw	3
		db	8
		dw	0D9h,-1
		dw	0B4h
		db	13h
		dw	122h,-1
		dw	0DDh
		db	21h
		dw	13Ah,-1
		dw	126h
		db	-1
;DM
		db	64
		dw	32Ah
		db	21h
		dw	378h,-1
		dw	200h
		db	-1
;Tiny114
		db	65
		dw	280h
		db	21h
		dw	270h+70h,-1
		dw	270h+27h
		db	-1
;Tiny118
		db	66
		dw	2B0h
		db	21h
		dw	2A0h+74h,-1
		dw	2A0h+2Ah
		db	-1
;Tiny141
		db	67
		dw	360h
		db	21h
		dw	360h+0BAh,-1
		dw	360h+63h
		db	-1
;Tiny132
		db	68
		dw	310h
		db	21h
		dw	310h+0B1h,-1
		dw	310h+5Eh
		db	-1
;AT
		db	69
		dw	240h
		db	21h
		dw	240h+0BDh,-1
		dw	240h+67h
		db	-1
;Eddie1
		db	70
		dw	60h
		db	21h
		dw	818h,-1
		dw	359h
		db	27h
		dw	814h,-1
		dw	331h
		db	-1
;Ninja
		db	71
		dw	20h
		db	21h
		dw	54Ah,-1
		dw	0C2h
		db	-1
;Try
		db	72
		dw	90h
		db	21h
		dw	0Ah,-1
		dw	1FDh
		db	-1
;Monkey
		db	73
		dw	83h
		db	13h
		dw	1FCh,-1
		dw	7Dh
		db	-1
;Crazy
		db	74
		dw	110h
		db	1Ch
		dw	6A3h,-1
		dw	64Dh
		db	21h
		dw	6A7h,-1
		dw	1CFh
		db	-1
;AntiARJ
		db	75
		dw	1D0h
		db	13h
		dw	7Dh*4,0
		dw	266h
		db	-1
;AntiARJ_1
		db	76
		dw	1E2h
		db	13h
		dw	7Dh*4,0
		dw	267h
		db	-1
;AB7
		db	77
		dw	21h
		db	9
		dw	1D4h,-1
		dw	194h
		db	13h
		dw	249h,-1
		dw	1D8h
		db	15h
		dw	2A8h,-1
		dw	281h
		db	21h
		dw	36Ah,-1
		dw	343h
		db	2Fh
		dw	42Bh,-1
		dw	3E9h
		db	40h
		dw	2FAh,-1
		dw	2E5h
		db	-1
;AntiCMOS
		db	78
		dw	2Fh
		db	13h
		dw	7,-1
		dw	52h
		db	-1
;Spirit
		db	79
		dw	4Ch
		db	13h
		dw	1F0h,-1
		dw	1B9h
		db	-1
;AB6_2
		db	80
		dw	0B71h
		db	13h
		dw	1D4h,-1
		dw	1B2h
		db	17h
		dw	2C4h,-1
		dw	288h
		db	21h
		dw	3ACh,-1
		dw	2D0h
		db	-1
;Super
		db	81
		dw	13h
		db	8
		dw	2A6h,-1
		dw	238h
		db	40h
		dw	771h,-1
		dw	3F9h
		db	15h
		dw	340h,-2
		dw	Super_Mem
		db	-1
;Super1
		db	82
		dw	13h
		db	8
		dw	29Eh,-1
		dw	230h
		db	40h
		dw	742h,-1
		dw	3DCh
		db	15h
		dw	32Eh,-2
		dw	Super1_Mem
		db	-1
;INFO
		db	83
		dw	145h
		db	1Ch
		dw	951h,-1
		dw	915h
		db	21h
		dw	466h,-1
		dw	415h
		db	-1
;AB6_3
		db	84
		dw	0B52h
		db	13h
		dw	1EAh,-1
		dw	1C8h
		db	17h
		dw	2D3h,-1
		dw	297h
		db	21h
		dw	3BCh,-1
		dw	2DFh
		db	-1
;BootEXE_2
		db	85
		dw	13Ah
		db	13h
		dw	0,-1
		dw	204h
		db	-1
;InfoSys
		db	86
		dw	145h
		db	21h
		dw	473h,-1
		dw	422h
		db	-1
;TaiPan
		db	87
		dw	0Ch
		db	21h
		dw	0AFh,-1
		dw	0D0h
		db	-1
;Ripper
		db	88
		dw	40h
		db	13h
		dw	171h,-1
		dw	3CDh
		db	-1
;BUPT
		db	89
		dw	3Dh
		db	13h
		dw	1Fh,-1
		dw	2E9h
		db	-1
;LoveBuzz
		db	90
		dw	3Bh
		db	13h
		dw	0A5h,-1
		dw	8Fh
		db	21h
		dw	180h,-1
		dw	0A9h
		db	-1
;Snowfall2
		db	91
		dw	1FFh
		db	8
		dw	21Bh,-1
		dw	219h
		db	21h
		dw	4C0h,-1
		dw	2FFh
		db	-1
;Viktoria2
		db	92
		dw	161h
		db	21h
		dw	7Bh*4,0
		dw	18Bh
		db	-1
;NLA
		db	93
		dw	1D6h
		db	13h
		dw	7Dh*4,0
		dw	263h
		db	-1
;SVC_3
		db	94
		dw	20h
		db	21h
		dw	3DAh,-1
		dw	0EBh
		db	-1
;ATrace2
		db	95
		dw	30h
		db	21h
		dw	15Bh,-1
		dw	1E8h
		db	-1
;Snowfall3
		db	96
		dw	190h
		db	1Ch
		dw	20Ah,-1
		dw	208h
		db	21h
		dw	47Ah,-1
		dw	2EBh
		db	-1
;SVC_X
		db	97
		dw	0
		db	21h
		dw	0BA6h,-1
		dw	142h
		db	13h
		dw	0BA2h,-1
		dw	7A2h
		db	-1
;SVC_4_X
		db	98
		dw	29h
		db	21h
		dw	678h,-1
		dw	0EBh
		db	-1
;MRTI557
		db	99
		dw	15Ah
		db	17h
		dw	3FFh,-1
		dw	343h
		db	21h
		dw	2D0h,-1
		dw	1BBh
		db	27h
		dw	35Ah,-1
		dw	35Eh
		db	-1
;MRTI576
		db	100
		dw	14Dh
		db	17h
		dw	331h,-1
		dw	335h
		db	21h
		dw	2C2h,-1
		dw	1A5h
		db	27h
		dw	34Ch,-1
		dw	350h
		db	-1
;MRTI644
		db	101
		dw	14Dh
		db	17h
		dw	354h,-1
		dw	372h
		db	21h
		dw	2E5h,-1
		dw	1A3h
		db	27h
		dw	390h,-1
		dw	394h
		db	-1
;Metal400
		db	102
		dw	336h
		db	21h
		dw	32Fh,-1
		dw	200h
		db	-1
;Metal500
		db	103
		dw	392h
		db	21h
		dw	32Fh,-1
		dw	200h
		db	-1
;Licee944
		db	104
		dw	30h
		db	21h
		dw	3B0h,-1
		dw	9Ch
		db	-1
;Licee1888
		db	105
		dw	30h
		db	8
		dw	776h,-1
		dw	0D8h
		db	9
		dw	77Ah,-1
		dw	1D1h
		db	13h
		dw	77Eh,-1
		dw	1DDh
		db	21h
		dw	782h,-1
		dw	1FFh
		db	-1
;Info2
		db	106
		dw	148h
		db	21h
		dw	463h,-1
		dw	409h
		db	-1

		dw	-1			; end word

; Table of viruses for it cure

April1st_Table:
FlagCOM 	db	80h	;flag (80h - active)
OffEnt		dw	0	;offset entry point at begin for COM
NBytes		db	4	;number of saved bytes
				;if 0FFh then special COM table
				;else - normal
CTbl		dw	AprilCOM
FlagEXE 	db	80h	;EXE (flag)
OffEXE		dw	0	;offset entry point at begin for EXE
OffSP		dw	-1	;offset SP
EvnSP		db	0	;even byte
OffSS		dw	-1	;offset SS
EvnSS		db	0	;even byte
OffIP		dw	0A8h	;offset IP
EvnIP		db	0	;even byte
OffCS		dw	0AAh	;offset CS
EvnCS		db	0	;even byte
BrPi_Table	db	80h
		dw	0
		db	4
		dw	BrPICOM
		db	80h
		dw	0
		dw	-1
		db	0
		dw	-1
		db	0
		dw	4
		db	0
		dw	6
		db	0
AIW2_Table	db	80h
		dw	0
		db	10
		dw	AIW2COM
		db	0
Nutcracker_Table	db	80h
		dw	0
		db	3
		dw	AB3COM
		db	80h
		dw	0
		dw	1CEh
		db	0
		dw	1CCh
		db	0
		dw	191h
		db	0
		dw	193h
		db	0
BabyL_Table	db	80h
		dw	0
		db	5
		dw	ABCOM
		db	80h
		dw	0
		dw	29Fh
		db	0
		dw	29Dh
		db	0
		dw	0C8h
		db	0
		dw	0CAh
		db	0
Avenger_Table	db	80h
		dw	68h
		db	3
		dw	AvengerCOM
		db	80h
		dw	68h
		dw	701h-68h
		db	0
		dw	703h-68h
		db	0
		dw	6FDh-68h
		db	0
		dw	6FFh-68h
		db	0
Eddie_Table	db	80h
		dw	60h
		db	3
		dw	EddieCOM
		db	80h
		dw	60h
		dw	7B9h-60h
		db	0
		dw	7BBh-60h
		db	0
		dw	7B5h-60h
		db	0
		dw	7B7h-60h
		db	0
SNut_Table	db	80h
		dw	0A74h
		db	3
		dw	AB4COM
		db	80h
		dw	0A74h
		dw	3ADh-0A74h
		db	1
		dw	3ABh-0A74h
		db	1
		dw	0C18h-0A74h
		db	0
		dw	0C1Ah-0A74h
		db	0
Juny24th_Table	db	80h
		dw	0
		db	3
		dw	JunCOM
		db	0
October15th_Table	db	80h
		dw	0
		db	4
		dw	OctCOM
		db	80h
		dw	0
		dw	-1
		db	0
		dw	-1
		db	0
		dw	0ACh
		db	0
		dw	0AEh
		db	0
BrPi2_Table	db	80h
		dw	0
		db	4
		dw	BrPI2COM
		db	80h
		dw	0
		dw	-1
		db	0
		dw	-1
		db	0
		dw	4
		db	0
		dw	6
		db	0
Snowfall_Table	db	80h
		dw	0
		db	3
		dw	SnowCOM
		db	0
Snowfall2_Table db	80h
		dw	0
		db	3
		dw	Snow2COM
		db	0
Snowfall3_Table db	80h
		dw	0
		db	3
		dw	Snow3COM
		db	0
Radio_Table	db	0
		dw	0
		db	0
		dw	0
		db	80h
		dw	0
		dw	126h
		db	0
		dw	128h
		db	0
		dw	122h
		db	0
		dw	124h
		db	0
Coder_Table	db	80h
		dw	0
		db	-1
		dw	CoderCOM
		db	80h
		dw	0
		dw	6Bh
		db	0
		dw	77h
		db	0
		dw	95h
		db	0
		dw	7Dh
		db	0
Vienna_Table	db	80h
		dw	0
		db	3
		dw	ViennaCOM
		db	0
Yankee_Table	db	80h
		dw	7D1h
		db	20h
		dw	YankeeCOM
		db	80h
		dw	7D1h
		dw	-1
		db	0
		dw	-1
		db	0
		dw	-7D1h+1Eh
		db	1
		dw	-7D1h+20h
		db	1
SVC_Table	db	80h
		dw	0
		db	3
		dw	SVCCom
		db	80h
		dw	0
		dw	0BBAh
		db	0
		dw	0BB8h
		db	0
		dw	0BBEh
		db	0
		dw	0BC0h
		db	0
Cascade_Table	db	80h
		dw	1
		db	3
		dw	CascadeCOM
AB5_Table	db	80h
		dw	8B6h
		db	3
		dw	AB5COM
		db	80h
		dw	8B6h
		dw	15Dh-8B6h
		db	1
		dw	15Bh-8B6h
		db	1
		dw	161h-8B6h
		db	1
		dw	163h-8B6h
		db	1
Hope_Table	db	80h
		dw	91Fh
		db	3
		dw	HopeCOM
		db	80h
		dw	91Fh
		dw	14Bh+10h-91Fh
		db	1
		dw	14Bh+0Eh-91Fh
		db	1
		dw	14Bh+14h-91Fh
		db	1
		dw	14Bh+16h-91Fh
		db	1
Sv10_Table	db	80h
		dw	0
		db	3
		dw	Sv10COM
		db	80h
		dw	0
		dw	41Ch
		db	0
		dw	41Ah
		db	0
		dw	420h
		db	0
		dw	422h
		db	0
Sv11_Table	db	80h
		dw	0
		db	3
		dw	Sv11COM
		db	80h
		dw	0
		dw	72Bh
		db	0
		dw	729h
		db	0
		dw	72Fh
		db	0
		dw	731h
		db	0
Sv12_Table	db	80h
		dw	0
		db	3
		dw	Sv12COM
		db	80h
		dw	0
		dw	0C23h+10h
		db	0
		dw	0C23h+0Eh
		db	0
		dw	0C23h+14h
		db	0
		dw	0C23h+16h
		db	0
Sv13_Table	db	80h
		dw	0
		db	3
		dw	Sv13COM
		db	80h
		dw	0
		dw	114Fh+10h
		db	0
		dw	114Fh+0Eh
		db	0
		dw	114Fh+14h
		db	0
		dw	114Fh+16h
		db	0
AB5_1_Table	db	80h
		dw	942h
		db	3
		dw	AB5_1COM
		db	80h
		dw	942h
		dw	158h+10h-942h
		db	1
		dw	158h+0Eh-942h
		db	1
		dw	158h+14h-942h
		db	1
		dw	158h+16h-942h
		db	1
AB6_Table	db	80h
		dw	0B3Fh
		db	3
		dw	AB6_COM
		db	80h
		dw	0B3Fh
		dw	1E6h-0B3Fh+10h
		db	1
		dw	1E6h-0B3Fh+0Eh
		db	1
		dw	1E6h-0B3Fh+14h
		db	1
		dw	1E6h-0B3Fh+16h
		db	1
AB6_1_Table	db	80h
		dw	0B46h
		db	3
		dw	AB6_1_COM
		db	80h
		dw	0B46h
		dw	1E9h-0B46h+10h
		db	1
		dw	1E9h-0B46h+0Eh
		db	1
		dw	1E9h-0B46h+14h
		db	1
		dw	1E9h-0B46h+16h
		db	1
AB6_2_Table	db	80h
		dw	0B61h
		db	3
		dw	AB6_2_COM
		db	80h
		dw	0B61h
		dw	182h-0B61h+10h
		db	1
		dw	182h-0B61h+0Eh
		db	1
		dw	182h-0B61h+14h
		db	1
		dw	182h-0B61h+16h
		db	1
AB6_3_Table	db	80h
		dw	0B42h
		db	3
		dw	AB6_3_COM
		db	80h
		dw	0B42h
		dw	198h-0B42h+10h
		db	1
		dw	198h-0B42h+0Eh
		db	1
		dw	198h-0B42h+14h
		db	1
		dw	198h-0B42h+16h
		db	1
XAM_Table	db	80h
		dw	0
		db	-1
		dw	XAM_COM
		db	80h
		dw	74h
		dw	32Dh-74h
		db	0
		dw	32Bh-74h
		db	0
		dw	331h-74h
		db	0
		dw	333h-74h
		db	0
ZAK_table	db	80h
		dw	318h
		db	3
		dw	ZAK_COM
		db	80h
		dw	318h
		dw	-1
		db	0
		dw	27h-318h
		db	1
		dw	23h-318h
		db	1
		dw	25h-318h
		db	1
Case_table	db	80h
		dw	0
		db	3
		dw	Case_COM
		db	0
Hymn_table	db	80h
		dw	5
		db	3
		dw	Hymn_COM
		db	80h
		dw	5
		dw	855h-5
		db	0
		dw	857h-5
		db	0
		dw	851h-5
		db	0
		dw	853h-5
		db	0
Atn_table	db	80h
		dw	11h
		db	10h
		dw	Atn_COM
		db	0
Jmp165_Table	db	80h
		dw	0
		db	3
		dw	Jmp165_COM
		db	0
Retn155_Table	db	80h
		dw	0
		db	4
		dw	Retn155_COM
		db	0
Tiny141_Table	db	80h
		dw	0
		db	3
		dw	Tiny141_COM
		db	0
Tiny132_Table	db	80h
		dw	0
		db	3
		dw	Tiny132_COM
		db	0
AT_Table	db	80h
		dw	0
		db	3
		dw	AT_COM
		db	0
MSmall_Table	db	80h
		dw	4
		db	4
		dw	MSmallCOM
		db	0
KosKon_Table	db	80h
		dw	0
		db	4
		dw	KosKonCOM
		db	0
Exit_Table	db	80h
		dw	0
		db	5
		dw	ExitCOM
		db	0
ATrace_Table	db	80h
		dw	0
		db	0Dh
		dw	ATraceCOM
		db	0
ATrace1_Table	db	80h
		dw	0
		db	0Dh
		dw	ATrace1COM
		db	0
ATrace2_Table	db	80h
		dw	0
		db	0Dh
		dw	ATrace2COM
		db	0
FBug_Table	db	80h
		dw	0
		db	3
		dw	FBugCOM
		db	0
DM_Table	db	80h
		dw	127h
		db	4
		dw	DM_COM
		db	0
Vien534_Table	db	80h
		dw	0
		db	3
		dw	Vien534_COM
		db	0
ALEX_Table	db	80h
		dw	0
		db	3
		dw	ALEX_COM
		db	0
Ambul_Table	db	80h
		dw	0
		db	3
		dw	Ambul_COM
		db	0
Frodo_Table	db	80h
		dw	6Ch
		db	3
		dw	Frodo_COM
		db	0
Noril_Table	db	80h
		dw	0
		db	3
		dw	Noril_COM
		db	0
SVC_4_Table	db	80h
		dw	0
		db	3
		dw	SVC_4_COM
		db	80h
		dw	0
		dw	659h
		db	0
		dw	657h
		db	0
		dw	65Dh
		db	0
		dw	65Fh
		db	0
SVC_4_X_Table	db	80h
		dw	0
		db	3
		dw	SVC_4_X_COM
		db	80h
		dw	0
		dw	67Ch+10h
		db	0
		dw	67Ch+0Eh
		db	0
		dw	67Ch+14h
		db	0
		dw	67Ch+16h
		db	0
SVC_3_Table	db	80h
		dw	0
		db	3
		dw	SVC_3_COM
		db	80h
		dw	0
		dw	3EEh
		db	0
		dw	3ECh
		db	0
		dw	3F2h
		db	0
		dw	3F4h
		db	0
Wishes_Table	db	80h
		dw	133h
		db	3
		dw	Wishes_COM
		db	80h
		dw	133h
		dw	-1
		db	0
		dw	-1
		db	0
		dw	0Bh-133h
		db	1
		dw	9-133h
		db	1
Ninja_Table	db	80h
		dw	0
		db	4
		dw	NinjaCOM
		db	80h
		dw	0
		dw	0B4h+0Ch
		db	0
		dw	0B2h+0Ch
		db	0
		dw	0AEh+0Ch
		db	0
		dw	0B0h+0Ch
		db	0
NoEXEC_Table	db	80h
		dw	0
		db	-1
		dw	NoEXEC_COM
		db	0
TaiPan_Table	db	0
		dw	0
		db	0
		dw	0
		db	80h
		dw	0
		dw	1AEh
		db	0
		dw	1ACh
		db	0
		dw	1B2h
		db	0
		dw	1B4h
		db	0
LoveBuzz_Table	db	80h
		dw	0
		db	4
		dw	LoveCOM
		db	0
MRTI557_table	db	80h
		dw	0
		db	3
		dw	MRTI557_COM
		db	0
MRTI576_table	db	80h
		dw	0
		db	4
		dw	MRTI576_COM
		db	0
MRTI644_table	db	80h
		dw	0
		db	4
		dw	MRTI644_COM
		db	0
Metal400_table	db	80h
		dw	137h
		db	3
		dw	Metal400_COM
		db	0
Metal500_table	db	80h
		dw	192h
		db	3
		dw	Metal400_COM
		db	80h
		dw	1A8h
		dw	-1
		db	0
		dw	-1
		db	0
		dw	1B2h-1A8h
		db	0
		dw	1ABh-1A8h
		db	0
Licee944_table	db	80h
		dw	0
		db	3
		dw	Licee944_COM
		db	80h
		dw	0
		dw	388h+10h
		db	0
		dw	388h+0Eh
		db	0
		dw	388h+14h
		db	0
		dw	388h+16h
		db	0
Licee1888_table db	80h
		dw	0
		db	3
		dw	Licee1888_COM
		db	80h
		dw	0
		dw	743h+10h
		db	0
		dw	743h+0Eh
		db	0
		dw	743h+14h
		db	0
		dw	743h+16h
		db	0

; COM tables

AprilCOM:
OffCOM		dw	0ACh	;offset for COM
EvtCOM		db	0	;event byte
BrPICOM:
		dw	0ADh
		db	0
AIW2COM:
		dw	1B7h
		db	0
AB3COM:
		dw	1B8h
		db	0
NinjaCOM:
		dw	492h+0Ch
		db	0
ABCOM:
		dw	29Dh
		db	0
AvengerCOM:
		dw	705h-68h
		db	0
EddieCOM:
		dw	7BDh-60h
		db	0
AB4COM:
		dw	39Dh-0A74h
		db	1
JunCOM:
		dw	8Fh
		db	0
LoveCOM:
		dw	241h
		db	0
OctCOM:
		dw	0B0h
		db	0
BrPI2COM:
		dw	91h
		db	0
SnowCOM:
		dw	111h
		db	0
Snow2COM:
		dw	116h
		db	0
Snow3COM:
		dw	105h
		db	0
CoderCOM:
		db	4
		dw	0A4h
		db	0
		dw	0A5h
		db	0
		dw	0ABh
		db	0
		dw	0ACh
		db	0
NoEXEC_COM:
		db	4
		dw	4
		db	0
		dw	5
		db	0
		dw	0Ah
		db	0
		dw	0Bh
		db	0
MSmallCOM:
		dw	12Fh-4
		db	0
Tiny141_COM:
		dw	33h
		db	0
Tiny132_COM:
		dw	2Eh
		db	0
AT_COM:
		dw	37h
		db	0
KosKonCOM:
		dw	83h
		db	0
ExitCOM:
		dw	16Ch
		db	0
ATraceCOM:
		dw	0DCh
		db	0
ATrace1COM:
		dw	0B7h
		db	0
ATrace2COM:
		dw	129h
		db	0
FBugCOM:
		dw	2B6h
		db	0
DM_COM:
		dw	42h
		db	0
ViennaCOM:
		dw	203h
		db	0
YankeeCOM:
		dw	-7D1h+0Ah
		db	1
SVCCom:
		dw	0BAAh
		db	0
CascadeCOM:
		dw	2Eh-1
		db	0
AB5COM:
		dw	14Dh-8B6h
		db	1
Sv10COM:
		dw	40Ch
		db	0
Sv11COM:
		dw	71Bh
		db	0
Sv12COM:
		dw	0C23h
		db	0
Sv13COM:
		dw	114Fh
		db	0
AB5_1COM:
		dw	158h-942h
		db	1
HopeCOM:
		dw	14Bh-91Fh
		db	1
AB6_COM:
		dw	1E6h-0B3Fh
		db	1
AB6_1_COM:
		dw	1E9h-0B46h
		db	1
AB6_2_COM:
		dw	182h-0B61h
		db	1
AB6_3_COM:
		dw	198h-0B42h
		db	1
XAM_COM:
		db	3
		dw	9
		db	0
		dw	0Ah
		db	0
		dw	0Eh
		db	0
ZAK_COM:
		dw	1-318h
		db	1
Case_COM:
		dw	39Ah
		db	0
Hymn_COM:
		dw	859h-5
		db	0
Atn_COM:
		dw	-10h
		db	1
Jmp165_COM:
		dw	0A1h
		db	0
Retn155_COM:
		dw	22h
		db	0
Vien534_COM:
		dw	165h
		db	0
ALEX_COM:
		dw	247h
		db	0
Ambul_COM:
		dw	319h
		db	0
Frodo_COM:
		dw	12-78h
		db	1
Noril_COM:
		dw	1E5h
		db	0
SVC_4_COM:
		dw	649h
		db	0
SVC_4_X_COM:
		dw	67Ch
		db	0
SVC_3_COM:
		dw	3DEh
		db	0
Wishes_COM:
		dw	4-133h
		db	1
MRTI557_COM:
		dw	1B8h
		db	0
MRTI576_COM:
		dw	1B7h
		db	0
MRTI644_COM:
		dw	1DAh
		db	0
Metal400_COM:
		dw	-3
		db	1
Licee944_COM:
		dw	388h
		db	0
Licee1888_COM:
		dw	743h
		db	0

; Block Cure for self-encryption viruses

Radio_Ens	dw	0E3h		;bytes of read from file
		dw	7Eh		;offset (add)
		db	0		;even byte
		dw	SubRadio
		db	2		;ID (see 1st Table)
		dw	Radio_Table
Coder_Ens	dw	1922
		dw	0
		db	0
		dw	SubCoder
		db	2
		dw	Coder_Table
SVC_Ens 	dw	72h
		dw	0BAAh
		db	0
		dw	SubSVC
		db	2
		dw	SVC_Table
Cascade_Ens	dw	50h
		dw	22h
		db	0
		dw	SubCascade
		db	2
		dw	Cascade_Table
Sv10_Ens	dw	18h
		dw	40Ch
		db	0
		dw	Sub_Sv
		db	2
		dw	Sv10_Table
Sv11_Ens	dw	18h
		dw	71Bh
		db	0
		dw	Sub_Sv
		db	2
		dw	Sv11_Table
Sv12_Ens	dw	18h
		dw	0C23h
		db	0
		dw	Sub_Sv
		db	2
		dw	Sv12_Table
Sv13_Ens	dw	18h
		dw	114Fh
		db	0
		dw	Sub_Sv
		db	2
		dw	Sv13_Table
ZAK_Ens 	dw	4
		dw	25h-318h
		db	1
		dw	Sub_ZAK
		db	2
		dw	ZAK_table
Case_Ens	dw	388h
		dw	17h
		db	0
		dw	Sub_Case
		db	2
		dw	Case_table
Hymn_Ens	dw	2144
		dw	-5
		db	1
		dw	Sub_Hymn
		db	2
		dw	Hymn_table
Ninja_Ens	dw	1376
		dw	0
		db	0
		dw	Sub_Ninja
		db	2
		dw	Ninja_Table
ATrace2_Ens	dw	13
		dw	129h
		db	0
		dw	Sub_ATrace2
		db	2
		dw	ATrace2_Table

; Standard Master Boot Record loader

MBR		db	0FAh,33h,0C0h,8Eh,0D0h,0BCh,0,7Ch,8Bh,0F4h,50h,7,50h,1Fh,0FBh,0FCh
		db	0BFh,0,6,0B9h,0,1,0F2h,0A5h,0EAh,1Dh,6,0,0,0BEh,0BEh,7
		db	0B3h,4,80h,3Ch,80h,74h,0Eh,80h,3Ch,0,75h,1Ch,83h,0C6h,10h,0FEh
		db	0CBh,75h,0EFh,0CDh,18h,8Bh,14h,8Bh,4Ch,2,8Bh,0EEh,83h,0C6h,10h,0FEh
		db	0CBh,74h,1Ah,80h,3Ch,0,74h,0F4h,0BEh,8Bh,6,0ACh,3Ch,0,74h,0Bh
		db	56h,0BBh,7,0,0B4h,0Eh,0CDh,10h,5Eh,0EBh,0F0h,0EBh,0FEh,0BFh,5,0
		db	0BBh,0,7Ch,0B8h,1,2,57h,0CDh,13h,5Fh,73h,0Ch,33h,0C0h,0CDh,13h
		db	4Fh,75h,0EDh,0BEh,0A3h,6,0EBh,0D3h,0BEh,0C2h,6,0BFh,0FEh,7Dh,81h,3Dh
		db	55h,0AAh,75h,0C7h,8Bh,0F5h,0EAh,0,7Ch,0,0,49h,6Eh,76h,61h,6Ch
		db	69h,64h,20h,70h,61h,72h,74h,69h,74h,69h,6Fh,6Eh,20h,74h,61h,62h
		db	6Ch,65h,0,45h,72h,72h,6Fh,72h,20h,6Ch,6Fh,61h,64h,69h,6Eh,67h
		db	20h,6Fh,70h,65h,72h,61h,74h,69h,6Eh,67h,20h,73h,79h,73h,74h,65h
		db	6Dh,0,4Dh,69h,73h,73h,69h,6Eh,67h,20h,6Fh,70h,65h,72h,61h,74h
		db	69h,6Eh,67h,20h,73h,79h,73h,74h,65h,6Dh,0,0,97h,68h,8,1Dh,0F2h
		db	15 dup (0)
		db	16*16 dup (0)
		db	14 dup (0),55h,0AAh

Boot		db	0EBh,3Eh,90h,50h,43h,20h,54h,6Fh,6Fh,6Ch,73h,0,2,2,1,0
		db	2,7,0,0D0h,2,0FDh,2,0,9,0,2,0,0,0,0,0
		db	0,0,0,0,0Fh,0,0,0,0,1,0,0,0,0,0,0
		db	0,0,6,0,1,4,0Ch,0,0,0,0,0,0,0,0,0
		db	0FAh,0FCh,33h,0C0h,8Eh,0D0h,0BCh,0,7Ch,36h,0C5h,36h,78h,0,1Eh,56h
		db	8Eh,0C0h,8Dh,3Eh,20h,7Ch,0B9h,0Bh,0,0ACh,26h,80h,3Dh,0,74h,3
		db	26h,8Ah,5,0AAh,0E2h,0F3h,33h,0C0h,8Eh,0D8h,0A3h,7Ah,0,0C7h,6,78h
		db	0,20h,7Ch,0FBh,0CDh,13h,73h,3,0E9h,0B4h,0,8Ah,2Eh,30h,7Ch,8Ah
		db	0Eh,32h,7Ch,8Ah,36h,31h,7Ch,0B2h,0,0BBh,0,5,0B8h,1,2,0CDh
		db	13h,72h,0E5h,8Dh,36h,62h,7Dh,8Bh,0FBh,0B9h,0Bh,0,0F3h,0A6h,75h,0Dh
		db	0BFh,20h,5,0B9h,0Bh,0,0F3h,0A6h,74h,1Ah,0E9h,89h,0,8Dh,36h,78h
		db	7Dh,8Bh,0FBh,0B9h,0Bh,0,0F3h,0A6h,75h,7Ch,0BFh,20h,5h,0B9h,0Bh,0
		db	0F3h,0A6h,75h,72h,33h,0D2h,0A1h,1Ch,5,0F7h,36h,0Bh,7Ch,0FEh,0C0h,0A2h
		db	38h,7Ch,0BBh,0,7,8Ah,2Eh,33h,7Ch,8Ah,0Eh,35h,7Ch,8Ah,36h,34h
		db	7Ch,0B2h,0,0A1h,18h,7Ch,2Ah,0C1h,0FEh,0C0h,50h,0B4h,2,0CDh,13h,58h
		db	72h,3Dh,28h,6,38h,7Ch,76h,1Ah,0B4h,0,52h,0F7h,26h,0Bh,7Ch,5Ah
		db	3h,0D8h,0B1h,1,0FEh,0C6h,3Ah,36h,1Ah,7Ch,72h,0D7h,0FEh,0C5h,0B6h,0
		db	0EBh,0D1h,0CDh,11h,0D0h,0C0h,0D0h,0C0h,25h,3,0,75h,1,40h,40h,8Bh
		db	0C8h,0B8h,0,0,0B2h,0,8Bh,1Eh,36h,7Ch,0EAh,0,0,70h,0,8Dh
		db	36h,8Eh,7Dh,0EBh,5,90h,8Dh,36h,0A2h,7Dh,0ACh,0Ah,0C0h,74h,9,0BBh
		db	7,0,0B4h,0Eh,0CDh,10h,0EBh,0F2h,8Dh,1Eh,0C2h,7Dh,3Bh,0F3h,77h,4
		db	8Bh,0F3h,0EBh,0E6h,32h,0E4h,0CDh,16h,8Fh,6h,78h,0,8Fh,6,7Ah,0
		db	0CDh,19h,49h,42h,4Dh,42h,49h,4Fh,20h,20h,43h,4Fh,4Dh,49h,42h,4Dh
		db	44h,4Fh,53h,20h,20h,43h,4Fh,4Dh,49h,4Fh,20h,20h,20h,20h,20h,20h
		db	53h,59h,53h,4Dh,53h,44h,4Fh,53h,20h,20h,20h,53h,59h,53h,0Ah,0Dh
		db	44h,69h,73h,6Bh,20h,42h,6Fh,6Fh,74h,20h,46h,61h,69h,6Ch,75h,72h
		db	65h,0,0Ah,0Dh,4Eh,6Fh,6Eh,2Dh,53h,79h,73h,74h,65h,6Dh,20h,64h
		db	69h,73h,6Bh,20h,6Fh,72h,20h,64h,69h,73h,6Bh,20h,65h,72h,72h,6Fh
		db	72h,0,0Ah,0Dh,52h,65h,70h,6Ch,61h,63h,65h,20h,61h,6Eh,64h,20h
		db	70h,72h,65h,73h,73h,20h,61h,6Eh,79h,20h,6Bh,65h,79h,20h,77h,68h
		db	65h,6Eh,20h,72h,65h,61h,64h,79h,0Ah,0Dh,20 dup (0),55h,0AAh

