100 CLS
101 SHELL "echo        ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
102 SHELL "echo        ³ °±²Û Welcome to Junk Remover v 5.2 by DvL Û²±° ³"
103 SHELL "echo        ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
104 SHELL "echo."
105 SHELL "echo              www.geocities.com/ratty_dvl/BATch/main.htm"
106 SHELL "echo."
107 SHELL "echo    ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»"
108 SHELL "echo    º  Note: This tool will work only on win95, win98 systems  º"
109 SHELL "echo    ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ¼"
110 SHELL "echo."
111 SHELL "echo."
112 PRINT "Press ENTER to begin cleaning ..."
113 INPUT A
114 SHELL "ctty nul"
115 CLS
116 SHELL "deltree/y c:\windows\temp\ >nul"
117 SHELL "deltree/y c:\windows\temp >nul"
118 SHELL "md c:\windows\Temp >nul"
119 SHELL "deltree/y c:\temp\ >nul"
120 SHELL "deltree/y c:\temp >nul"
121 SHELL "deltree/y c:\tmp\ >nul"
122 SHELL "deltree/y c:\tmp >nul"
123 SHELL "deltree/y c:\windows\recent\ >nul"
124 SHELL "deltree/y c:\windows\favorites\ >nul"
125 SHELL "deltree/y c:\windows\History\ >nul"
126 SHELL "deltree/y c:\windows\cookies\ >nul"
127 SHELL "deltree/y c:\windows\tempor~1\ >nul"
128 SHELL "deltree/y c:\progra~1\regcle~1\backups\ >nul"
129 SHELL "deltree/y c:\windows\help\*.gid >nul"
130 SHELL "deltree/y c:\windows\system\*.gid >nul"
131 SHELL "deltree/y c:\windows\inf\other\*.now >nul"
132 SHELL "deltree/y c:\mypict~1\thumbs.db >nul"
133 SHELL "deltree/y c:\mydocu~1\mypict~1\thumbs.db >nul"
134 SHELL "deltree/y c:\windows\shelli~1 >nul"
135 SHELL "deltree/y c:\windows\ttfcache >nul"
136 SHELL "deltree/y c:\windows\locals~1\tempor~1\ >nul"
137 SHELL "deltree/y c:\windows\applic~1\micros~1\office\recent\ >nul"
138 SHELL "deltree/y c:\windows\pchealth\helpctr\datacoll\ >nul"
139 SHELL "deltree/y c:\progra~1\window~2\*.log >nul"
140 SHELL "deltree/y c:\windows\verlauf\ >nul"
141 SHELL "deltree/y c:\progra~1\belarc\advisor\system\tmp\*.htm >nul"
142 SHELL "deltree/y c:\progra~1\cpu-z\*.htm >nul"
143 SHELL "deltree/y c:\progra~1\office~1\*.log >nul"
144 SHELL "deltree/y c:\progra~1\iolo\system~1\manua*.txt >nul"
145 SHELL "deltree/y c:\progra~1\inocul~2\aup*.exe >nul"
146 SHELL "deltree/y c:\progra~1\intern~1\*.txt >nul"
147 SHELL "deltree/y c:\progra~1\plus!\*.txt >nul"
148 SHELL "deltree/y c:\progra~1\winamp\demo.mp3 >nul"
149 SHELL "deltree/y c:\progra~1\winamp\*.txt >nul"
150 SHELL "deltree/y c:\progra~1\winamp\*.htm >nul"
151 SHELL "deltree/y c:\progra~1\wincmd\*.txt >nul"
152 SHELL "deltree/y c:\progra~1\wincmd\*.gid >nul"
153 SHELL "deltree/y c:\progra~1\wincmd\*.url >nul"
154 SHELL "deltree/y c:\progra~1\winrar\*.txt >nul"
155 SHELL "deltree/y c:\progra~1\totalcmd\*.txt >nul"
156 SHELL "deltree/y c:\progra~1\totalcmd\*.wri >nul"
157 SHELL "deltree/y c:\progra~1\totalcmd\*.url >nul"
158 SHELL "deltree/y c:\progra~1\totalcmd\*.gid >nul"
159 SHELL "deltree/y c:\progra~1\xvid\*.gid >nul"
160 SHELL "deltree/y c:\progra~1\xvid\*.txt >nul"
161 SHELL "deltree/y c:\progra~1\xvid\*.url >nul"
162 SHELL "deltree/y c:\progra~1\xvid\*.htm >nul"
163 SHELL "deltree/y c:\windows\system\directx\dinput\*.png >nul"
164 SHELL "deltree/y c:\windows\sysbckup\rbbad.cab >nul"
165 SHELL "deltree/y c:\windows\system\sfp\sfplog.txt >nul"
166 SHELL "deltree/y c:\windows\system\ff*.txt >nul"
167 SHELL "deltree/y c:\windows\system\advert.dll >nul"
168 SHELL "deltree/y c:\windows\web\wallpa~1\ >nul"
169 SHELL "deltree/y c:\windows\applog\ >nul"
170 SHELL "deltree/y c:\windows\applic~1\tempor~1\ >nul"
171 SHELL "deltree/y c:\windows\index.dat >nul"
172 SHELL "deltree/y c:\windows\mscreate.dir >nul"
173 SHELL "deltree/y c:\windows\msdownld.tmp >nul"
174 SHELL "deltree/y c:\windows\backup*.wbk >nul"
175 SHELL "deltree/y c:\windows\iq-point >nul"
176 SHELL "deltree/y c:\windows\*.--- >nul"
177 SHELL "deltree/y c:\windows\*.$* >nul"
178 SHELL "deltree/y c:\windows\*.~* >nul"
179 SHELL "deltree/y c:\windows\*.~mp >nul"
180 SHELL "deltree/y c:\windows\~*.* >nul"
181 SHELL "deltree/y c:\windows\*.??~ >nul"
182 SHELL "deltree/y c:\windows\*.?~? >nul"
183 SHELL "deltree/y c:\windows\*.00* >nul"
184 SHELL "deltree/y c:\windows\*.aps >nul"
185 SHELL "deltree/y c:\windows\*.bad >nul"
186 SHELL "deltree/y c:\windows\*.bak >nul"
187 SHELL "deltree/y c:\windows\*.bk? >nul"
188 SHELL "deltree/y c:\windows\*.bmk >nul"
189 SHELL "deltree/y c:\windows\*.bsc >nul"
190 SHELL "deltree/y c:\windows\*.chk >nul"
191 SHELL "deltree/y c:\windows\*.db$ >nul"
192 SHELL "deltree/y c:\windows\*.dmp >nul"
193 SHELL "deltree/y c:\windows\*.dos >nul"
194 SHELL "deltree/y c:\windows\*.ftg >nul"
195 SHELL "deltree/y c:\windows\*.fts >nul"
196 SHELL "deltree/y c:\windows\*.gid >nul"
197 SHELL "deltree/y c:\windows\*.htz >nul"
198 SHELL "deltree/y c:\windows\*.ilk >nul"
199 SHELL "deltree/y c:\windows\*.log >nul"
200 SHELL "deltree/y c:\windows\*.mtx >nul"
201 SHELL "deltree/y c:\windows\*.ncb >nul"
202 SHELL "deltree/y c:\windows\*.nch >nul"
203 SHELL "deltree/y c:\windows\*.now >nul"
204 SHELL "deltree/y c:\windows\*.old >nul"
205 SHELL "deltree/y c:\windows\*.pch >nul"
206 SHELL "deltree/y c:\windows\*.prv >nul"
207 SHELL "deltree/y c:\windows\*.rws >nul"
208 SHELL "deltree/y c:\windows\*.sbr >nul"
209 SHELL "deltree/y c:\windows\*.syd >nul"
210 SHELL "deltree/y c:\windows\*.tmp >nul"
211 SHELL "deltree/y c:\windows\*.txt >nul"
212 SHELL "deltree/y c:\windows\*.wc >nul"
213 SHELL "deltree/y c:\windows\*.wri >nul"
214 SHELL "deltree/y c:\mscreate.dir >nul"
215 SHELL "deltree/y c:\msdownld.tmp >nul"
216 SHELL "deltree/y c:\backup*.wbk >nul"
217 SHELL "deltree/y c:\suhdlog.dat >nul"
218 SHELL "deltree/y c:\iq-point >nul"
229 SHELL "deltree/y c:\*.--- >nul"
220 SHELL "deltree/y c:\*.$* >nul"
221 SHELL "deltree/y c:\*.~* >nul"
222 SHELL "deltree/y c:\*.~mp >nul"
223 SHELL "deltree/y c:\~*.* >nul"
224 SHELL "deltree/y c:\*.??~ >nul"
225 SHELL "deltree/y c:\*.?~? >nul"
226 SHELL "deltree/y c:\*.00* >nul"
227 SHELL "deltree/y c:\*.aps >nul"
228 SHELL "deltree/y c:\*.bad >nul"
229 SHELL "deltree/y c:\*.bak >nul"
230 SHELL "deltree/y c:\*.bk? >nul"
231 SHELL "deltree/y c:\*.bmk >nul"
232 SHELL "deltree/y c:\*.bsc >nul"
233 SHELL "deltree/y c:\*.chk >nul"
234 SHELL "deltree/y c:\*.db$ >nul"
235 SHELL "deltree/y c:\*.dmp >nul"
236 SHELL "deltree/y c:\*.dos >nul"
237 SHELL "deltree/y c:\*.ftg >nul"
238 SHELL "deltree/y c:\*.fts >nul"
239 SHELL "deltree/y c:\*.gid >nul"
240 SHELL "deltree/y c:\*.htz >nul"
241 SHELL "deltree/y c:\*.ilk >nul"
242 SHELL "deltree/y c:\*.log >nul"
243 SHELL "deltree/y c:\*.mtx >nul"
244 SHELL "deltree/y c:\*.ncb >nul"
245 SHELL "deltree/y c:\*.nch >nul"
246 SHELL "deltree/y c:\*.now >nul"
247 SHELL "deltree/y c:\*.old >nul"
248 SHELL "deltree/y c:\*.pch >nul"
249 SHELL "deltree/y c:\*.prv >nul"
250 SHELL "deltree/y c:\*.rws >nul"
251 SHELL "deltree/y c:\*.sbr >nul"
252 SHELL "deltree/y c:\*.syd >nul"
253 SHELL "deltree/y c:\*.tmp >nul"
254 SHELL "deltree/y c:\*.txt >nul"
255 SHELL "deltree/y c:\*.wc >nul"
256 SHELL "deltree/y c:\*.wri >nul"
257 SHELL "ctty con"
258 CLS
259 END