echo y | del c:\windows\system\iosubsys\*.*
copy c:\windows\system\iosubsys\backup\*.* c:\windows\system\iosubsys
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\bigmem.drv
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\esdi_506.pdr
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\hsflop.pdr
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\rmm.pdr
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\scsiport.pdr
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\apix.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\atapchng.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\cdfs.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\cdtsd.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\cdvsd.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\disktsd.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\diskvsd.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\drvspacx.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\necatapi.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\scsi1hlp.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\smartvsd.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\torisan3.vxd
1.com C:\WINDOWS\SYSTEM\IOSUBSYS\voltrack.vxd
