.AUTODEPEND

#               *Translator Definitions*
CC = bcc +SCAN.CFG
TASM = TASM
TLIB = tlib
TLINK = tlink
LIBPATH = D:\BC\LIB
INCLUDEPATH = D:\BC\INCLUDE


#               *Implicit Rules*
.c.obj:
  $(CC) -c {$< }

.cpp.obj:
  $(CC) -c {$< }

.asm.obj:
  $(TASM) -c {$< }

#               *List Macros*


EXE_dependencies =  \
 vscanner.obj \
 memory.obj \
 xscanner.obj \
 ratcatch.obj \
 scanner.obj \
 sysdos.obj \
 cmdline.obj \
 crc32.obj

#               *Explicit Rules*
build: flycatch.com clean

flycatch.com: flycatch.obj
  tlink /t flycatch.obj

flycatch.obj: flycatch.asm
  tasm /m3 flycatch.asm

clean:
  del *.obj
  del *.map

